# 单个词报告

In [1]:
import pandas as pd
import json

from collections import defaultdict

In [2]:
import sys
sys.path.append('..')

## 原始数据

In [3]:
df_raw = pd.read_excel('data/mayday_songs.xlsx', sheet_name='Sheet1')
df_raw['song_name'] = df_raw['song_name'].astype(str)
df_raw

,album_order,album_id,album_name,album_type,release_date,song_order,song_id,song_name,album_fixed,has_lyric,is_duplicate
0,1,38315,第一张创作专辑,录音室专辑,1999-07-07,1,386925,疯狂世界,第一张创作专辑,1,0
1,1,38315,第一张创作专辑,录音室专辑,1999-07-07,2,386927,拥抱,第一张创作专辑,1,0
2,1,38315,第一张创作专辑,录音室专辑,1999-07-07,3,386929,透露,第一张创作专辑,1,0
3,1,38315,第一张创作专辑,录音室专辑,1999-07-07,4,386930,生活,第一张创作专辑,1,0
4,1,38315,第一张创作专辑,录音室专辑,1999-07-07,5,386931,爱情的模样,第一张创作专辑,1,0
...,...,...,...,...,...,...,...,...,...,...,...
185,11,2740205,步步 自选作品辑,精选辑,2013-12-30,26,28181124,雌雄同体,步步 自选作品辑,1,1
186,11,2740205,步步 自选作品辑,精选辑,2013-12-30,27,28181126,生命有一种绝对,步步 自选作品辑,1,1
187,11,2740205,步步 自选作品辑,精选辑,2013-12-30,28,28181128,诺亚方舟,步步 自选作品辑,1,1
188,11,2740205,步步 自选作品辑,精选辑,2013-12-30,29,28181130,我心中尚未崩坏的地方,步步 自选作品辑,1,1
189,11,2740205,步步 自选作品辑,精选辑,2013-12-30,30,28181132,憨人,步步 自选作品辑,1,1

In [4]:
df_lyric_raw = pd.read_csv('output/mayday_lyric_word.csv')
df_lyric_raw

,song_id,word,pos,freq,album_order,album_id,album_name,album_type,release_date,song_order,song_name,album_fixed,has_lyric,is_duplicate
0,386925,我,r,18,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0
1,386925,好想,v,18,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0
2,386925,那么,r,12,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0
3,386925,多,m,12,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0
4,386925,的,uj,12,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13130,28181110,长大,v,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0
13131,28181110,难道,d,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0
13132,28181110,人,n,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0
13133,28181110,必经,d,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0
13134,28181110,溃烂,v,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0

In [5]:
# 曲目，专辑添加唯一id
df_lyric = df_lyric_raw.copy()
df_lyric['song_id_unique'] = 'song' + df_lyric['song_id'].astype(str)
df_album_fixed = df_lyric[['album_id', 'album_fixed']].drop_duplicates(subset=['album_fixed'], keep='first').reset_index(drop=True)
df_album_fixed['album_id_unique'] = 'album' + df_album_fixed['album_id'].astype(int).astype(str)
df_album_fixed = df_album_fixed[['album_id_unique', 'album_fixed']]
df_lyric= df_lyric.merge(df_album_fixed, on='album_fixed', how='left')
df_lyric

,song_id,word,pos,freq,album_order,album_id,album_name,album_type,release_date,song_order,song_name,album_fixed,has_lyric,is_duplicate,song_id_unique,album_id_unique
0,386925,我,r,18,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0,song386925,album38315
1,386925,好想,v,18,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0,song386925,album38315
2,386925,那么,r,12,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0,song386925,album38315
3,386925,多,m,12,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0,song386925,album38315
4,386925,的,uj,12,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0,song386925,album38315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13130,28181110,长大,v,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0,song28181110,album2740205
13131,28181110,难道,d,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0,song28181110,album2740205
13132,28181110,人,n,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0,song28181110,album2740205
13133,28181110,必经,d,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0,song28181110,album2740205
13134,28181110,溃烂,v,1,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,19.0,盛夏光年,步步 自选作品辑,1.0,0.0,song28181110,album2740205

# 词分析

In [26]:
# 词
word = "时间"
df_word = df_lyric[df_lyric['word'] == word]
df_word

,song_id,word,pos,freq,album_order,album_id,album_name,album_type,release_date,song_order,song_name,album_fixed,has_lyric,is_duplicate,song_id_unique,album_id_unique
245,386930,时间,n,3,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,4.0,生活,第一张创作专辑,1.0,0.0,song386930,album38315
2018,386691,时间,n,2,3.0,38297.0,人生海海,录音室专辑,2001-07-06,1.0,一颗苹果,人生海海,1.0,0.0,song386691,album38297
4126,386476,时间,n,1,4.0,38276.0,时光机,录音室专辑,2003-11-11,12.0,在这一秒,时光机,1.0,0.0,song386476,album38276
4275,386482,时间,n,2,4.0,38276.0,时光机,录音室专辑,2003-11-11,14.0,王子面,时光机,1.0,0.0,song386482,album38276
4546,386173,时间,n,1,5.0,38259.0,神的孩子都在跳舞,录音室专辑,2004-11-05,1.0,孙悟空,神的孩子都在跳舞,1.0,0.0,song386173,album38259
5072,386185,时间,n,1,5.0,38259.0,神的孩子都在跳舞,录音室专辑,2004-11-05,7.0,回来吧,神的孩子都在跳舞,1.0,0.0,song386185,album38259
7577,22198023,时间,n,1,7.0,38235.0,后青春期的诗,录音室专辑,2008-10-23,10.0,如烟,后青春期的诗,1.0,0.0,song22198023,album38235
8217,22197001,时间,n,1,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,3.0,星空,第二人生,1.0,0.0,song22197001,album2040001
8306,22197003,时间,n,3,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,4.0,洗衣机,第二人生,1.0,0.0,song22197003,album2040001
8504,22197004,时间,n,2,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,5.0,三个傻瓜,第二人生,1.0,0.0,song22197004,album2040001
8752,22197007,时间,n,6,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,7.0,干杯,第二人生,1.0,0.0,song22197007,album2040001
9033,22197008,时间,n,1,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,8.0,仓颉,第二人生,1.0,0.0,song22197008,album2040001
9090,22197009,时间,n,1,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,9.0,2012,第二人生,1.0,0.0,song22197009,album2040001
9575,2008204010,时间,n,2,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,14.0,T1213121,第二人生,1.0,0.0,song2008204010,album2040001
9772,417953659,时间,n,1,9.0,34746073.0,自传,录音室专辑,2016-07-21,1.0,如果我们不曾相遇,自传,1.0,0.0,song417953659,album34746073
10026,422094253,时间,n,2,9.0,34746073.0,自传,录音室专辑,2016-07-21,3.0,好好 (想把你写成一首歌),自传,1.0,0.0,song422094253,album34746073
11560,422094257,时间,n,1,9.0,34746073.0,自传,录音室专辑,2016-07-21,13.0,转眼,自传,1.0,0.0,song422094257,album34746073

In [27]:
song_ids = df_word['song_id'].unique()
song_ids

array([    386930,     386691,     386476,     386482,     386173,
           386185,   22198023,   22197001,   22197003,   22197004,
         22197007,   22197008,   22197009, 2008204010,  417953659,
        422094253,  422094257])

In [28]:
with open('output/mayday_lyric_260124.json', 'r', encoding='utf-8') as f:
    lyric_raw = json.load(f)
lyric_dict = defaultdict(dict)
for i in lyric_raw:
    if i:
        lyric_dict[i['song_id']] = i
        lyric_dict[i['song_id']]['lyric_splited'] = i['歌词'].split('。')
lyric_dict

defaultdict(dict,
            {'386925': {'歌名': '疯狂世界',
              'song_id': '386925',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '如果说了后悔，是不是一切就能倒退。回忆多么美，活着多么狼狈。为什么这个世界，总要叫人尝伤悲。我不能了解，也不想了解。我好想好想飞。逃离这个疯狂世界。那么多苦，那么多累。那么多莫名的泪水。我好想好想飞。逃离这个疯狂的世界。如果是你，发现了我。也别将我挽回。想了你一整夜，再也想不起你的脸。你是一种感觉，写在夏夜晚风里面。青春是挽不回的水，转眼消失在指间。用力的浪费，再用力的后悔。我好想好想飞。我好想好想飞。逃离这个疯狂世界。那么多苦，那么多累。那么多莫名的泪水。我好想好想飞，逃离这个疯狂的世界。如果是你，发现了我。也别将我挽回。~~~~~~。我好想好想飞。逃离这个疯狂世界。那么多苦，那么多累。那么多莫名的泪水。我好想好想飞。逃离这个疯狂的世界。如果是你，发现了我。也别将我挽回。我好想好想飞。逃离这个疯狂世界。那么多苦，那么多累。那么多莫名的伤悲。我好想好想飞。逃离这个疯狂的世界。如果是你，发现了我。也别将我挽回。',
              'lyric_splited': ['如果说了后悔，是不是一切就能倒退',
               '回忆多么美，活着多么狼狈',
               '为什么这个世界，总要叫人尝伤悲',
               '我不能了解，也不想了解',
               '我好想好想飞',
               '逃离这个疯狂世界',
               '那么多苦，那么多累',
               '那么多莫名的泪水',
               '我好想好想飞',
               '逃离这个疯狂的世界',
               '如果是你，发现了我',
               '也别将我挽回',
               '想了你一整夜，再也想不起你的脸',
               '你是一种感觉，写在夏夜晚风里面',
               '青春是挽不回的水，转眼消失在指间',
               '用力的浪费，再用力的后悔',
               '我好想好想飞',
               '我好想好想飞',
               '逃离这个疯狂世界',
               '那么多苦，那么多累',
               '那么多莫名的泪水',
               '我好想好想飞，逃离这个疯狂的世界',
               '如果是你，发现了我',
               '也别将我挽回',
               '~~~~~~',
               '我好想好想飞',
               '逃离这个疯狂世界',
               '那么多苦，那么多累',
               '那么多莫名的泪水',
               '我好想好想飞',
               '逃离这个疯狂的世界',
               '如果是你，发现了我',
               '也别将我挽回',
               '我好想好想飞',
               '逃离这个疯狂世界',
               '那么多苦，那么多累',
               '那么多莫名的伤悲',
               '我好想好想飞',
               '逃离这个疯狂的世界',
               '如果是你，发现了我',
               '也别将我挽回',
               '']},
             '386927': {'歌名': '拥抱',
              'song_id': '386927',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '脱下长日的假面。奔向梦幻的疆界。南瓜马车的午夜。换上童话的玻璃鞋。让我享受这感觉。我是孤傲的蔷薇。让我品尝这滋味。纷乱世界的不了解。昨天太近，明天太远。默默聆听那黑夜。晚风吻尽，荷花叶。任我醉倒在池边。等你清楚看见我的美。月光晒干眼泪。那一个人，爱我。将我的手，紧握。抱紧我，吻我，爱，别走。隐藏自己的疲倦。表达自己的狼狈。放纵自己的狂野。找寻自己的明天。向你要求的誓言。就算是你的谎言。我需要爱的慰藉。就算那爱已如潮水。昨天太近，明天太远。默默聆听那黑夜。晚风吻尽，荷花叶。任我醉倒在池边。等你清楚看见我的美。月光晒干眼泪。那一个人，爱我。将我的手，紧握。抱紧我，吻我，爱，别走。那一个人，爱我。将我的手，紧握。抱紧我，吻我，爱，别走。抱紧我，吻我，爱，别走。抱紧我，吻我，爱。',
              'lyric_splited': ['脱下长日的假面',
               '奔向梦幻的疆界',
               '南瓜马车的午夜',
               '换上童话的玻璃鞋',
               '让我享受这感觉',
               '我是孤傲的蔷薇',
               '让我品尝这滋味',
               '纷乱世界的不了解',
               '昨天太近，明天太远',
               '默默聆听那黑夜',
               '晚风吻尽，荷花叶',
               '任我醉倒在池边',
               '等你清楚看见我的美',
               '月光晒干眼泪',
               '那一个人，爱我',
               '将我的手，紧握',
               '抱紧我，吻我，爱，别走',
               '隐藏自己的疲倦',
               '表达自己的狼狈',
               '放纵自己的狂野',
               '找寻自己的明天',
               '向你要求的誓言',
               '就算是你的谎言',
               '我需要爱的慰藉',
               '就算那爱已如潮水',
               '昨天太近，明天太远',
               '默默聆听那黑夜',
               '晚风吻尽，荷花叶',
               '任我醉倒在池边',
               '等你清楚看见我的美',
               '月光晒干眼泪',
               '那一个人，爱我',
               '将我的手，紧握',
               '抱紧我，吻我，爱，别走',
               '那一个人，爱我',
               '将我的手，紧握',
               '抱紧我，吻我，爱，别走',
               '抱紧我，吻我，爱，别走',
               '抱紧我，吻我，爱',
               '']},
             '386929': {'歌名': '透露',
              'song_id': '386929',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '我不知不觉不经意的被你占有。那是心里爱你的初衷。在我心深处无处可躲，向你透露。而全世界的寂寞即将被摆脱。梦不到昨日的恶梦。在我心深处扰攘的沉默，不再沉默。这是全天下最完美的阵容。我和你，你和我。狂飙爱意突然变得好猛。在此刻向你，完全透露。你的眼睛，你的双颊，你的笑容。你的秘密，和你的星座。在我心深处建造一个，你的王国。到底有或没有发现我的不同。看着我最真实的赤裸。在你心深处可否接受。不再退缩，不再保留，我的透露。这是全天下最完美的阵容。我和你，你和我。狂飙爱意突然变得好猛。在此刻向你，完全透露。这是全天下最完美的阵容。我和你，你和我。狂飙爱意突然变得好猛。在此刻向你，完全透露。DaDaDaDaDaDaDa。',
              'lyric_splited': ['我不知不觉不经意的被你占有',
               '那是心里爱你的初衷',
               '在我心深处无处可躲，向你透露',
               '而全世界的寂寞即将被摆脱',
               '梦不到昨日的恶梦',
               '在我心深处扰攘的沉默，不再沉默',
               '这是全天下最完美的阵容',
               '我和你，你和我',
               '狂飙爱意突然变得好猛',
               '在此刻向你，完全透露',
               '你的眼睛，你的双颊，你的笑容',
               '你的秘密，和你的星座',
               '在我心深处建造一个，你的王国',
               '到底有或没有发现我的不同',
               '看着我最真实的赤裸',
               '在你心深处可否接受',
               '不再退缩，不再保留，我的透露',
               '这是全天下最完美的阵容',
               '我和你，你和我',
               '狂飙爱意突然变得好猛',
               '在此刻向你，完全透露',
               '这是全天下最完美的阵容',
               '我和你，你和我',
               '狂飙爱意突然变得好猛',
               '在此刻向你，完全透露',
               'DaDaDaDaDaDaDa',
               '']},
             '386930': {'歌名': '生活',
              'song_id': '386930',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': "有场战争，就在眼前。斗志斗不过温暖棉被。水龙头里，流出眼泪。又是残酷的美好一天。眼前有一千件事，正等着解决。Everybody，想要改变。Everything，won't，be，OK。七点的一杯咖啡，八点的红绿灯，斑马线。A，busy，game，Everyday。活在疯狂世界，活在美好的明天。重重考验，来到今天。不知不觉改变，远离每个昨天。那些笑和眼泪，没有时间说再见。喜怒哀乐，苦辣酸甜。终于了解，这就是生活的滋味。生活太近，梦想太远。午餐是吃饭还是吃面。喜欢忙碌，搞得很累。电话吵醒的星期天。珍惜的浪费时间，换来了的生命的缺。理想划过天边，爱情呀与我擦肩。分不清东南西北，分不清我的地，我的天。A，crying，game，Everyday。活在疯狂世界，活在美好的明天。重重考验，来到今天。不知不觉改变，远离每个昨天。那些笑和眼泪，没有时间说再见。喜怒哀乐，苦辣酸甜。终于了解，这就是生活的滋味。是不是会有答案，在终点后面。当初的我的信念，现在的我又是谁。狂奔的每个白天，寂寞的每个夜。慢慢发现，I'm，superman。Everyday。活在疯狂世界，活在美好的明天。重重考验，来到今天。不知不觉改变，远离每个昨天。那些笑和眼泪，没有时间说再见。梦的边缘，我在徘徊。终于了解，这就是生活的滋味。",
              'lyric_splited': ['有场战争，就在眼前',
               '斗志斗不过温暖棉被',
               '水龙头里，流出眼泪',
               '又是残酷的美好一天',
               '眼前有一千件事，正等着解决',
               'Everybody，想要改变',
               "Everything，won't，be，OK",
               '七点的一杯咖啡，八点的红绿灯，斑马线',
               'A，busy，game，Everyday',
               '活在疯狂世界，活在美好的明天',
               '重重考验，来到今天',
               '不知不觉改变，远离每个昨天',
               '那些笑和眼泪，没有时间说再见',
               '喜怒哀乐，苦辣酸甜',
               '终于了解，这就是生活的滋味',
               '生活太近，梦想太远',
               '午餐是吃饭还是吃面',
               '喜欢忙碌，搞得很累',
               '电话吵醒的星期天',
               '珍惜的浪费时间，换来了的生命的缺',
               '理想划过天边，爱情呀与我擦肩',
               '分不清东南西北，分不清我的地，我的天',
               'A，crying，game，Everyday',
               '活在疯狂世界，活在美好的明天',
               '重重考验，来到今天',
               '不知不觉改变，远离每个昨天',
               '那些笑和眼泪，没有时间说再见',
               '喜怒哀乐，苦辣酸甜',
               '终于了解，这就是生活的滋味',
               '是不是会有答案，在终点后面',
               '当初的我的信念，现在的我又是谁',
               '狂奔的每个白天，寂寞的每个夜',
               "慢慢发现，I'm，superman",
               'Everyday',
               '活在疯狂世界，活在美好的明天',
               '重重考验，来到今天',
               '不知不觉改变，远离每个昨天',
               '那些笑和眼泪，没有时间说再见',
               '梦的边缘，我在徘徊',
               '终于了解，这就是生活的滋味',
               '']},
             '386931': {'歌名': '爱情的模样',
              'song_id': '386931',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '你是巨大的海洋，我是雨下在你身上。我失去了自己的形状。我看到远方，爱情的模样。曾经孤单的彷徨，曾经相信曾经失望。你穿过了重重的迷惘。那爱的慌张，终于要解放。你是谁，教我狂恋。教我勇敢地挑战全世界。在一样的身体里面，一样有爱与被爱的感觉。我爱谁，已无所谓。没有谁能将爱情划界限。在一样的身体里面，迷样的魔力却是更强烈。星星在夜空中闪亮，星空下我不停流浪。此生我无知的奔忙。因为你眼光，都化成了光亮。这世界全部的漂亮。不过你的可爱模样，你让我举双手投降。跨出了城墙，长出了翅膀。你是谁，教我狂恋。教我勇敢地挑战全世界。在一样的身体里面，一样有爱与被爱的感觉。我爱谁，已无所谓。没有谁能将爱情划界限。在一样的身体里面，迷样的魔力却是更强烈。你是巨大的海洋，我是雨下在你身上。我失去了自己的形状。我看到远方，爱情的模样。',
              'lyric_splited': ['你是巨大的海洋，我是雨下在你身上',
               '我失去了自己的形状',
               '我看到远方，爱情的模样',
               '曾经孤单的彷徨，曾经相信曾经失望',
               '你穿过了重重的迷惘',
               '那爱的慌张，终于要解放',
               '你是谁，教我狂恋',
               '教我勇敢地挑战全世界',
               '在一样的身体里面，一样有爱与被爱的感觉',
               '我爱谁，已无所谓',
               '没有谁能将爱情划界限',
               '在一样的身体里面，迷样的魔力却是更强烈',
               '星星在夜空中闪亮，星空下我不停流浪',
               '此生我无知的奔忙',
               '因为你眼光，都化成了光亮',
               '这世界全部的漂亮',
               '不过你的可爱模样，你让我举双手投降',
               '跨出了城墙，长出了翅膀',
               '你是谁，教我狂恋',
               '教我勇敢地挑战全世界',
               '在一样的身体里面，一样有爱与被爱的感觉',
               '我爱谁，已无所谓',
               '没有谁能将爱情划界限',
               '在一样的身体里面，迷样的魔力却是更强烈',
               '你是巨大的海洋，我是雨下在你身上',
               '我失去了自己的形状',
               '我看到远方，爱情的模样',
               '']},
             '386932': {'歌名': '嘿！我要走了',
              'song_id': '386932',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '轻轻闭上眼睛此刻我觉得清醒。已经不需要一些挽留字句。这绚烂新世纪深情已不受欢迎。爱你那么用力却好像一场闹剧。嘿我要走了。昨天的对白已不再重要。我已见过最美的一幕。只是在此刻。都要结束。都要结束。你我不断找寻然后再不断放弃。不断的犯错然后再不断远离。如果你还肯听。我想说声我爱你。反正自做多情是我看家本领。嘿我要走了。昨天的对白已不再重要。我已见过最美的一幕。只是在此刻。都要结束。嘿我要走了。昨天的对白已不再重要。我已见过最美的一幕。只是在此刻。都要结束。轻轻闭上眼睛此刻我觉得清醒。已经不需要一些挽留字句。这绚烂新世纪深情已不受欢迎。收拾我的行李去找寻新的自己。都要结束。都要结束。都要结束。都要结束。',
              'lyric_splited': ['轻轻闭上眼睛此刻我觉得清醒',
               '已经不需要一些挽留字句',
               '这绚烂新世纪深情已不受欢迎',
               '爱你那么用力却好像一场闹剧',
               '嘿我要走了',
               '昨天的对白已不再重要',
               '我已见过最美的一幕',
               '只是在此刻',
               '都要结束',
               '都要结束',
               '你我不断找寻然后再不断放弃',
               '不断的犯错然后再不断远离',
               '如果你还肯听',
               '我想说声我爱你',
               '反正自做多情是我看家本领',
               '嘿我要走了',
               '昨天的对白已不再重要',
               '我已见过最美的一幕',
               '只是在此刻',
               '都要结束',
               '嘿我要走了',
               '昨天的对白已不再重要',
               '我已见过最美的一幕',
               '只是在此刻',
               '都要结束',
               '轻轻闭上眼睛此刻我觉得清醒',
               '已经不需要一些挽留字句',
               '这绚烂新世纪深情已不受欢迎',
               '收拾我的行李去找寻新的自己',
               '都要结束',
               '都要结束',
               '都要结束',
               '都要结束',
               '']},
             '386934': {'歌名': '轧车',
              'song_id': '386934',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '是按怎阿花和阿娇，拢无佳意我。我撇车技术一流，无人甲我轧。是按怎学校的老师，拢无疼痛我。是不是ABCD看无卡憨就拢免教。老爸老母，整天底骂。喋喋喋念，不知念啥。是按怎哪会按呢，身边的问题一摊。这时阵上好作阵来去轧车。作阵来轧车，作阵来轧车。不管伊警察底抓，不管伊父母底骂。只要我引擎催落，无人可当甲我轧。在这我最快最趴最大。是按怎今日的观众拢底打拍仔。大家看我一个那像，Super，Star。La，La，La，La，La，La，La，La。愈骑愈紧愈爽，我想欲唱歌。头脑底飞，身躯底颤。风底吹我，心底流汗。是按怎那会这爽，要了解我的感觉。这时阵上好作阵来去轧车。作阵来轧车，作阵来轧车。不管伊警察底抓，不管伊父母底骂。只要我引擎催落，无人可当甲我轧。在这我最快最趴最大。作阵来轧车，作阵来轧车。不管伊警察底抓，不管伊父母底骂。只要我引擎催落，无人可当甲我轧。在这我最快最趴最大。',
              'lyric_splited': ['是按怎阿花和阿娇，拢无佳意我',
               '我撇车技术一流，无人甲我轧',
               '是按怎学校的老师，拢无疼痛我',
               '是不是ABCD看无卡憨就拢免教',
               '老爸老母，整天底骂',
               '喋喋喋念，不知念啥',
               '是按怎哪会按呢，身边的问题一摊',
               '这时阵上好作阵来去轧车',
               '作阵来轧车，作阵来轧车',
               '不管伊警察底抓，不管伊父母底骂',
               '只要我引擎催落，无人可当甲我轧',
               '在这我最快最趴最大',
               '是按怎今日的观众拢底打拍仔',
               '大家看我一个那像，Super，Star',
               'La，La，La，La，La，La，La，La',
               '愈骑愈紧愈爽，我想欲唱歌',
               '头脑底飞，身躯底颤',
               '风底吹我，心底流汗',
               '是按怎那会这爽，要了解我的感觉',
               '这时阵上好作阵来去轧车',
               '作阵来轧车，作阵来轧车',
               '不管伊警察底抓，不管伊父母底骂',
               '只要我引擎催落，无人可当甲我轧',
               '在这我最快最趴最大',
               '作阵来轧车，作阵来轧车',
               '不管伊警察底抓，不管伊父母底骂',
               '只要我引擎催落，无人可当甲我轧',
               '在这我最快最趴最大',
               '']},
             '386936': {'歌名': '志明与春娇',
              'song_id': '386936',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': 'u~Yeah~。志明真正毋知欲按怎。为啥物。爱人毋愿佫再相倚。春娇已经早着无咧听。讲遮济。其实拢总拢无较縒。aha~，行到淡水海岸。两个侬的爱情。已经无侬看。已经无侬听。aha~，我佮汝上好着到遮。汝对我已经无感觉。到遮挡定。汝也免爱我。我佮汝上好着到遮。汝对我已经无感觉。莫佫伤心。莫佫我遮爱汝。汝无爱我。Yeah~。志明心情真正有影寒。风遮大。汝也真正拢无心肝。春娇汝哪无欲和我搬。这场电影。咱着行到这位准拄煞。aha~，行到淡水海岸。两个侬的爱情。已经无侬看。已经无侬听。aha~，我佮汝上好着到遮。汝对我已经无感觉。到遮挡定。汝也免爱我。我佮汝上好着到遮。汝对我已经无感觉。莫佫伤心。莫佫我遮爱汝。汝无爱我。行到淡水海岸。两个侬的爱情。已经无侬看。已经无侬听。aha~，我佮汝上好着到遮。汝对我已经无感觉。到遮挡定。汝也免爱我。ha~，我佮汝上好着到遮。汝对我已经无感觉。莫佫伤心。莫佫我遮爱汝。汝无爱我。我佮汝上好着到遮。汝对我已经无感觉。到遮挡定。汝也免爱我。ha~，我佮汝上好着到遮。汝对我已经无感觉。莫佫伤心。莫佫我遮爱汝。汝无爱我。Yeah~。',
              'lyric_splited': ['u~Yeah~',
               '志明真正毋知欲按怎',
               '为啥物',
               '爱人毋愿佫再相倚',
               '春娇已经早着无咧听',
               '讲遮济',
               '其实拢总拢无较縒',
               'aha~，行到淡水海岸',
               '两个侬的爱情',
               '已经无侬看',
               '已经无侬听',
               'aha~，我佮汝上好着到遮',
               '汝对我已经无感觉',
               '到遮挡定',
               '汝也免爱我',
               '我佮汝上好着到遮',
               '汝对我已经无感觉',
               '莫佫伤心',
               '莫佫我遮爱汝',
               '汝无爱我',
               'Yeah~',
               '志明心情真正有影寒',
               '风遮大',
               '汝也真正拢无心肝',
               '春娇汝哪无欲和我搬',
               '这场电影',
               '咱着行到这位准拄煞',
               'aha~，行到淡水海岸',
               '两个侬的爱情',
               '已经无侬看',
               '已经无侬听',
               'aha~，我佮汝上好着到遮',
               '汝对我已经无感觉',
               '到遮挡定',
               '汝也免爱我',
               '我佮汝上好着到遮',
               '汝对我已经无感觉',
               '莫佫伤心',
               '莫佫我遮爱汝',
               '汝无爱我',
               '行到淡水海岸',
               '两个侬的爱情',
               '已经无侬看',
               '已经无侬听',
               'aha~，我佮汝上好着到遮',
               '汝对我已经无感觉',
               '到遮挡定',
               '汝也免爱我',
               'ha~，我佮汝上好着到遮',
               '汝对我已经无感觉',
               '莫佫伤心',
               '莫佫我遮爱汝',
               '汝无爱我',
               '我佮汝上好着到遮',
               '汝对我已经无感觉',
               '到遮挡定',
               '汝也免爱我',
               'ha~，我佮汝上好着到遮',
               '汝对我已经无感觉',
               '莫佫伤心',
               '莫佫我遮爱汝',
               '汝无爱我',
               'Yeah~',
               '']},
             '386939': {'歌名': 'HoSee',
              'song_id': '386939',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '枪子无声钻来钻去。打破今眠的空气。半眠一点的巷仔内。在播一出戏。哪会按呢我想来想去。活得真不舒适。稍微一点风吹草动。把仔抓紧紧。Hosee，Hosee。呼伊死。看谁人先倒下去。Hosee，Hosee。呼伊死。看谁人的卡大支。Hosee，Hosee，呼伊死。Hosee，呼伊死。Hosee，Hosee，呼伊死。不爽就，Hosee，Hosee。世界哪会颠三倒四。人生过甲亲像战争。委屈若是吞不下去。一声就翻脸。江湖变甲这没义气。朋友变甲这歹逗阵。真正若是发生事情。人拢溜紧紧。Hosee，Hosee。呼伊死。看谁人先倒下去。Hosee，Hosee。呼伊死。看谁人的卡大支。Hosee，Hosee，呼伊死。Hosee，呼伊死。Hosee，Hosee，呼伊死。不爽就，Hosee，Hosee。（我手拿黑星走三关。一天到晚惊乎抬。兄弟啊，你要是太嚣张。我就送你苏州卖鸭蛋）。Hosee，Hosee。呼伊死。看谁人先倒下去。Hosee，Hosee。呼伊死。看谁人的卡大支。Hosee，Hosee，呼伊死。Hosee，呼伊死。Hosee，Hosee，呼伊死。不爽就，Hosee，Hosee。昨眠阁再梦到伊。牵手散步的日子。甘知当初的男儿。变甲按呢生。四面八方团团包围。右边左边撞不出去。我嘛不知。过了今眠。是生还是死。',
              'lyric_splited': ['枪子无声钻来钻去',
               '打破今眠的空气',
               '半眠一点的巷仔内',
               '在播一出戏',
               '哪会按呢我想来想去',
               '活得真不舒适',
               '稍微一点风吹草动',
               '把仔抓紧紧',
               'Hosee，Hosee',
               '呼伊死',
               '看谁人先倒下去',
               'Hosee，Hosee',
               '呼伊死',
               '看谁人的卡大支',
               'Hosee，Hosee，呼伊死',
               'Hosee，呼伊死',
               'Hosee，Hosee，呼伊死',
               '不爽就，Hosee，Hosee',
               '世界哪会颠三倒四',
               '人生过甲亲像战争',
               '委屈若是吞不下去',
               '一声就翻脸',
               '江湖变甲这没义气',
               '朋友变甲这歹逗阵',
               '真正若是发生事情',
               '人拢溜紧紧',
               'Hosee，Hosee',
               '呼伊死',
               '看谁人先倒下去',
               'Hosee，Hosee',
               '呼伊死',
               '看谁人的卡大支',
               'Hosee，Hosee，呼伊死',
               'Hosee，呼伊死',
               'Hosee，Hosee，呼伊死',
               '不爽就，Hosee，Hosee',
               '（我手拿黑星走三关',
               '一天到晚惊乎抬',
               '兄弟啊，你要是太嚣张',
               '我就送你苏州卖鸭蛋）',
               'Hosee，Hosee',
               '呼伊死',
               '看谁人先倒下去',
               'Hosee，Hosee',
               '呼伊死',
               '看谁人的卡大支',
               'Hosee，Hosee，呼伊死',
               'Hosee，呼伊死',
               'Hosee，Hosee，呼伊死',
               '不爽就，Hosee，Hosee',
               '昨眠阁再梦到伊',
               '牵手散步的日子',
               '甘知当初的男儿',
               '变甲按呢生',
               '四面八方团团包围',
               '右边左边撞不出去',
               '我嘛不知',
               '过了今眠',
               '是生还是死',
               '']},
             '386942': {'歌名': '黑白讲',
              'song_id': '386942',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '踅过了一摆佫一摆的街仔路。规工是拢无意义的走傱。天光到天乌，万事拢照常。无聊叫侬欲起狂。忍受着一摆佫一摆的啰嗦。汝予我的世界只有一条路。爱拼则会赢，我毋是听无。前途，我拢看袂着。哪会世界拢无声音。青春是战争，我渴望流血。有啥物绝招，做汝变。我的好兄弟，我拍拢袂死。我想欲行路有风。我想欲做真真正正的英雄。汝叫我，莫戆，莫戆，莫戆。我听汝咧乌白讲。踅过了一摆佫一摆的街仔路。规工是拢无意义的走傱。天光到天乌，万事拢照常。无聊叫侬欲起狂。忍受着一摆佫一摆的啰嗦。汝予我的世界只有一条路。爱拼则会赢，我毋是听无。前途，我拢看袂着。哪会世界拢无声音。青春是战争，我渴望流血。有啥物绝招，做汝变。我的好兄弟，我拍拢袂死。我想欲行路有风。我想欲做真真正正的英雄。汝叫我，莫戆，莫戆，莫戆。我听汝咧乌白讲。哪会世界拢无声音。青春是战争，我渴望流血。有啥物绝招，做汝变。我的好兄弟，我拍拢袂死。我想欲行路有风。我想欲做真真正正的英雄。汝叫我，莫戆，莫戆，莫戆。我听汝咧乌白讲。汝叫我，莫戆，莫戆，莫戆。我听汝咧乌白。汝叫我，莫戆，莫戆，莫戆。我听汝咧乌白讲。',
              'lyric_splited': ['踅过了一摆佫一摆的街仔路',
               '规工是拢无意义的走傱',
               '天光到天乌，万事拢照常',
               '无聊叫侬欲起狂',
               '忍受着一摆佫一摆的啰嗦',
               '汝予我的世界只有一条路',
               '爱拼则会赢，我毋是听无',
               '前途，我拢看袂着',
               '哪会世界拢无声音',
               '青春是战争，我渴望流血',
               '有啥物绝招，做汝变',
               '我的好兄弟，我拍拢袂死',
               '我想欲行路有风',
               '我想欲做真真正正的英雄',
               '汝叫我，莫戆，莫戆，莫戆',
               '我听汝咧乌白讲',
               '踅过了一摆佫一摆的街仔路',
               '规工是拢无意义的走傱',
               '天光到天乌，万事拢照常',
               '无聊叫侬欲起狂',
               '忍受着一摆佫一摆的啰嗦',
               '汝予我的世界只有一条路',
               '爱拼则会赢，我毋是听无',
               '前途，我拢看袂着',
               '哪会世界拢无声音',
               '青春是战争，我渴望流血',
               '有啥物绝招，做汝变',
               '我的好兄弟，我拍拢袂死',
               '我想欲行路有风',
               '我想欲做真真正正的英雄',
               '汝叫我，莫戆，莫戆，莫戆',
               '我听汝咧乌白讲',
               '哪会世界拢无声音',
               '青春是战争，我渴望流血',
               '有啥物绝招，做汝变',
               '我的好兄弟，我拍拢袂死',
               '我想欲行路有风',
               '我想欲做真真正正的英雄',
               '汝叫我，莫戆，莫戆，莫戆',
               '我听汝咧乌白讲',
               '汝叫我，莫戆，莫戆，莫戆',
               '我听汝咧乌白',
               '汝叫我，莫戆，莫戆，莫戆',
               '我听汝咧乌白讲',
               '']},
             '386948': {'歌名': 'I Love You 无望',
              'song_id': '386948',
              '作词': '五月天 阿信',
              '作曲': '五月天 阿信',
              '编曲': '五月天',
              '歌词': '是汝的形影。叫我逐工做眠梦。梦中可爱的侬。伊毋是别侬。我的每一工。一分钟也袂当轻松。汝是阮爱的侬。将阮来戏弄。九月的风咧吹。哪会寒到心肝底。希望变无望。决定我的一世侬。I，LOVE，YOU，无望。汝敢是这款侬。无法度来做阵。也无法度将阮放。I，LOVE，YOU，无望。我着是这款侬。我身边无半项。只有对汝的思念。陪伴我的每一工。是汝的形影。叫我逐工做眠梦。梦中可爱的侬。伊毋是别侬。我的每一工。一分钟也袂当轻松。汝是阮爱的侬。将阮来戏弄。九月的风咧吹。哪会寒到心肝底。希望变无望。决定我的一世侬。I，LOVE，YOU，无望。汝敢是这款侬。无法度来做阵。也无法度将阮放。I，LOVE，YOU，无望。我着是这款侬。我身边无半项。只有对汝的思念。陪伴我的每一工。I，LOVE，YOU，无望。汝敢是这款侬。无法度来做阵。也无法度将阮放。I，LOVE，YOU，无望。我着是这款侬。我身边无半项。只有对汝的思念。I，LOVE，YOU，无望。汝敢是这款侬。无法度来做阵。也无法度将阮放。I，LOVE，YOU，无望。我就是这款侬。我身边无半项。只有对汝的思念。陪伴我的每一工。',
              'lyric_splited': ['是汝的形影',
               '叫我逐工做眠梦',
               '梦中可爱的侬',
               '伊毋是别侬',
               '我的每一工',
               '一分钟也袂当轻松',
               '汝是阮爱的侬',
               '将阮来戏弄',
               '九月的风咧吹',
               '哪会寒到心肝底',
               '希望变无望',
               '决定我的一世侬',
               'I，LOVE，YOU，无望',
               '汝敢是这款侬',
               '无法度来做阵',
               '也无法度将阮放',
               'I，LOVE，YOU，无望',
               '我着是这款侬',
               '我身边无半项',
               '只有对汝的思念',
               '陪伴我的每一工',
               '是汝的形影',
               '叫我逐工做眠梦',
               '梦中可爱的侬',
               '伊毋是别侬',
               '我的每一工',
               '一分钟也袂当轻松',
               '汝是阮爱的侬',
               '将阮来戏弄',
               '九月的风咧吹',
               '哪会寒到心肝底',
               '希望变无望',
               '决定我的一世侬',
               'I，LOVE，YOU，无望',
               '汝敢是这款侬',
               '无法度来做阵',
               '也无法度将阮放',
               'I，LOVE，YOU，无望',
               '我着是这款侬',
               '我身边无半项',
               '只有对汝的思念',
               '陪伴我的每一工',
               'I，LOVE，YOU，无望',
               '汝敢是这款侬',
               '无法度来做阵',
               '也无法度将阮放',
               'I，LOVE，YOU，无望',
               '我着是这款侬',
               '我身边无半项',
               '只有对汝的思念',
               'I，LOVE，YOU，无望',
               '汝敢是这款侬',
               '无法度来做阵',
               '也无法度将阮放',
               'I，LOVE，YOU，无望',
               '我就是这款侬',
               '我身边无半项',
               '只有对汝的思念',
               '陪伴我的每一工',

In [ ]:
word_dict = defaultdict(list)
for song_id in song_ids:
    word_lyric = []
    song_id = str(song_id)
    for i in lyric_dict[song_id]['lyric_splited']:
        if word in i:
            word_lyric.append(i)
    word_dict[song_id] = list(set(word_lyric))
word_dict

defaultdict(list,
            {'386930': ['那些笑和眼泪，没有时间说再见', '珍惜的浪费时间，换来了的生命的缺'],
             '386691': ['那时间忘记挽留最美时候', '时间如果可以倒流我想'],
             '386476': ['时间它虽然重要，也不必抓的太牢'],
             '386482': ['用意大利式的，浪费时间，美好事物瞬间', '时间倒带闭上眼睛倒带时间'],
             '386173': ['好色本性多隽永，好像时间从来没走'],
             '386185': ['所有的人都说时间是魔法'],
             '22198023': ['时间是贼偷走一切'],
             '22197001': ['时间偷走初衷，只留下了苦衷'],
             '22197003': ['多少年了，旋转又旋转，时间一眨眼过去'],
             '22197004': ['傻不傻瓜，时间一样追杀'],
             '22197007': ['时间都停了他们都回来了', '会不会有一天时间真的能倒退'],
             '22197008': ['想逆转时间，回到，最开始，有你的世界'],
             '22197009': ['再没有时间，能去延后'],
             '2008204010': ['时间都停了，他们都回来了'],
             '417953659': ['无数时间线无尽可能性'],
             '422094253': ['忘了时间有脚', '时间的电影，结局才知道'],
             '422094257': ['时间就是，最巨大的谎']})

In [10]:
len(word_dict)

51

In [11]:
# 个别修正
word_dict_mannul_fix = {
    '386925': ['为什么这个世界，总要叫人尝伤悲', '我好想好想飞，逃离这个疯狂世界', '我好想好想飞，逃离这个疯狂的世界'],
    '422094256': [
        '你问我全世界是哪里最美，答案是你身边', '平凡的我们，也将回到，平凡的世界',
        '每个梦都，像任意门，往不同世界，而你的故事，现在正是起点', '我们曾走过，无数地方，和无尽岁月，搭着肩环游，无法遗忘，的光辉世界'
    ],
    '385976': [
        '世界若是，那么大，为何我要忘你，无处逃',
        '世界若是，那么小，为何我的真心，你听不到',
    ],
    '385787': ['这世界笑了，于是你合群的一起笑了'],
    '422094253': ['世界再大不过，你我凝视的微笑'],
    '385887': ['我来到这个世界，这个人生为你而生存'],
    '386479': ['想要征服的世界，始终都没有改变'],
    '386717': ['就算是整个世界，把我抛弃', '就算真的整个世界，把我抛弃'],
    '22198023': ['有没有那么一个世界，永远不天黑'],
    '385891': ['不管世界变得怎麽样，只要有你就会是天堂'],
    '385798': ['一生能有几次，跟世界宣战'],
}

In [12]:
for k, v in word_dict_mannul_fix.items():
    word_dict[k] = v
word_dict

defaultdict(list,
            {'386925': ['为什么这个世界，总要叫人尝伤悲',
              '我好想好想飞，逃离这个疯狂世界',
              '我好想好想飞，逃离这个疯狂的世界'],
             '386927': ['纷乱世界的不了解'],
             '386930': ['活在疯狂世界，活在美好的明天'],
             '386931': ['教我勇敢地挑战全世界', '这世界全部的漂亮'],
             '386939': ['世界哪会颠三倒四'],
             '386942': ['汝予我的世界只有一条路', '哪会世界拢无声音'],
             '386846': ['纵然是世界辽阔，外面的精彩好多'],
             '386848': ['开伤济气力，在这个世界，有小可仔无彩'],
             '386851': ['扰乱我原本平静的世界'],
             '386854': ['梦中的许个世界'],
             '386863': ['多希望世界就快要消失，好让我俩享受没有明天', '有一个漩涡，让我们躲避，真实世界，有什么刺激'],
             '386866': ['没有关系，你的世界，就让你拥有'],
             '386691': ['这世界给我的幽默'],
             '386700': ['世界就睡在梦里'],
             '386702': ['世界欲共汝捙拚'],
             '386715': ['世界被你掌握', '世界的纯真此刻为你有迷惑', '我以为世界是座宁静的宇宙'],
             '386717': ['就算是整个世界，把我抛弃', '就算真的整个世界，把我抛弃'],
             '386443': ['人在江湖心不由己这世界又烦又粘腻'],
             '386445': ['你要是落泪滴，世界都要下雨'],
             '386451': ['世界很大，（而我们应该长大）'],
             '386479': ['想要征服的世界，始终都没有改变'],
             '386485': ['风雨却让世界不同', '其实等在前面还有一整个世界'],
             '386175': ['当，我和世界不一样'],
             '386183': ['Ok，再来，要世界为我们感动', '整个世界，曾经，都跟着你作梦'],
             '386191': ['世界如果被残酷攻击，只要给我一个电话亭', '世界如果被残酷攻击，谁来接手我的超能力'],
             '386195': ['感谢有你，让平淡的世界，加了分'],
             '385887': ['我来到这个世界，这个人生为你而生存'],
             '385891': ['不管世界变得怎麽样，只要有你就会是天堂'],
             '385897': ['献上快乐，献上伤悲，献上自我，献上世界',
              '啦啦啦啦啦，你想要世界，啦啦啦啦啦，就给你世界',
              '为你献上快乐伤悲，为你献上我的世界'],
             '385905': ['世界纷纷扰扰喧喧闹闹'],
             '385921': ['醒了世界依然残酷'],
             '385787': ['这世界笑了，于是你合群的一起笑了'],
             '385791': ['整个世界只剩下你听我说话'],
             '385798': ['一生能有几次，跟世界宣战'],
             '22198018': ['黯淡的月照亮世界'],
             '22198023': ['有没有那么一个世界，永远不天黑'],
             '22196002': ['我不愿让你一个人承受这世界的残忍'],
             '22197004': ['世界如果平的，为何人们，都要往上爬'],
             '22197007': ['现在就是那个未来那个世界', '一起走到未来的世界', '也许会有一天世界真的有终点'],
             '22197008': ['能不能飞越过，猜忌和冷漠，世界', '想逆转时间，回到，最开始，有你的世界'],
             '22197011': ['还是要告别，还是放弃海拔以下的世界'],
             '422094253': ['世界再大不过，你我凝视的微笑'],
             '422094254': ['曾以为世界，想怎样就怎样'],
             '422094255': ['如果世界只剩你我存在'],
             '422094256': ['你问我全世界是哪里最美，答案是你身边',
              '平凡的我们，也将回到，平凡的世界',
              '每个梦都，像任意门，往不同世界，而你的故事，现在正是起点',
              '我们曾走过，无数地方，和无尽岁月，搭着肩环游，无法遗忘，的光辉世界'],
             '422094257': ['世界曾疯狂，爱情曾绽放'],
             '385970': ['漂浮吧，飞过混乱世界', '漂浮吧，飞过混乱世界的逻辑'],
             '385976': ['世界若是，那么大，为何我要忘你，无处逃', '世界若是，那么小，为何我的真心，你听不到'],
             '386001': ['没有关系你的世界，就让你拥有'],
             '386025': ['世界要和你车拼'],
             '28181103': ['世界已灰飞烟灭', '你却占据了整个世界']})

In [13]:
df_word = df_word.sort_values(by=['release_date', 'song_order'], )
df_word

,song_id,word,pos,freq,album_order,album_id,album_name,album_type,release_date,song_order,song_name,album_fixed,has_lyric,is_duplicate,song_id_unique,album_id_unique
6,386925,世界,n,9,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,1.0,疯狂世界,第一张创作专辑,1.0,0.0,song386925,album38315
129,386927,世界,n,1,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,2.0,拥抱,第一张创作专辑,1.0,0.0,song386927,album38315
232,386930,世界,n,3,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,4.0,生活,第一张创作专辑,1.0,0.0,song386930,album38315
419,386931,世界,n,1,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,5.0,爱情的模样,第一张创作专辑,1.0,0.0,song386931,album38315
718,386939,世界,n,1,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,9.0,HoSee,第一张创作专辑,1.0,0.0,song386939,album38315
802,386942,世界,n,5,1.0,38315.0,第一张创作专辑,录音室专辑,1999-07-07,10.0,黑白讲,第一张创作专辑,1.0,0.0,song386942,album38315
1211,386846,世界,n,2,2.0,38308.0,爱情万岁,录音室专辑,2000-07-07,3.0,明白,爱情万岁,1.0,0.0,song386846,album38308
1329,386848,世界,n,1,2.0,38308.0,爱情万岁,录音室专辑,2000-07-07,4.0,心中无别人,爱情万岁,1.0,0.0,song386848,album38308
1409,386851,世界,n,2,2.0,38308.0,爱情万岁,录音室专辑,2000-07-07,5.0,有你的将来,爱情万岁,1.0,0.0,song386851,album38308
1438,386854,世界,n,3,2.0,38308.0,爱情万岁,录音室专辑,2000-07-07,6.0,憨人,爱情万岁,1.0,0.0,song386854,album38308
1789,386863,世界,n,1,2.0,38308.0,爱情万岁,录音室专辑,2000-07-07,9.0,罗密欧与茱丽叶,爱情万岁,1.0,0.0,song386863,album38308
1883,386866,世界,n,1,2.0,38308.0,爱情万岁,录音室专辑,2000-07-07,10.0,温柔,爱情万岁,1.0,0.0,song386866,album38308
2065,386691,世界,n,1,3.0,38297.0,人生海海,录音室专辑,2001-07-06,1.0,一颗苹果,人生海海,1.0,0.0,song386691,album38297
2391,386700,世界,n,1,3.0,38297.0,人生海海,录音室专辑,2001-07-06,4.0,相信,人生海海,1.0,0.0,song386700,album38297
2494,386702,世界,n,1,3.0,38297.0,人生海海,录音室专辑,2001-07-06,5.0,Ok啦,人生海海,1.0,0.0,song386702,album38297
2873,386715,世界,n,3,3.0,38297.0,人生海海,录音室专辑,2001-07-06,10.0,纯真,人生海海,1.0,0.0,song386715,album38297
3097,386717,世界,n,3,3.0,38297.0,人生海海,录音室专辑,2001-07-06,12.0,人生海海,人生海海,1.0,0.0,song386717,album38297
3207,386443,世界,n,1,4.0,38276.0,时光机,录音室专辑,2003-11-11,1.0,轻功,时光机,1.0,0.0,song386443,album38276
3274,386445,世界,n,1,4.0,38276.0,时光机,录音室专辑,2003-11-11,2.0,恒星的恒心,时光机,1.0,0.0,song386445,album38276
3582,386451,世界,n,1,4.0,38276.0,时光机,录音室专辑,2003-11-11,5.0,而我知道,时光机,1.0,0.0,song386451,album38276
4166,386479,世界,n,4,4.0,38276.0,时光机,录音室专辑,2003-11-11,13.0,生命有一种绝对,时光机,1.0,0.0,song386479,album38276
4384,386485,世界,n,2,4.0,38276.0,时光机,录音室专辑,2003-11-11,15.0,小时候,时光机,1.0,0.0,song386485,album38276
4602,386175,世界,n,1,5.0,38259.0,神的孩子都在跳舞,录音室专辑,2004-11-05,2.0,倔强,神的孩子都在跳舞,1.0,0.0,song386175,album38259
4938,386183,世界,n,2,5.0,38259.0,神的孩子都在跳舞,录音室专辑,2004-11-05,6.0,约翰蓝侬,神的孩子都在跳舞,1.0,0.0,song386183,album38259
5332,386191,世界,n,2,5.0,38259.0,神的孩子都在跳舞,录音室专辑,2004-11-05,10.0,超人,神的孩子都在跳舞,1.0,0.0,song386191,album38259
5469,386195,世界,n,1,5.0,38259.0,神的孩子都在跳舞,录音室专辑,2004-11-05,12.0,圣诞夜惊魂,神的孩子都在跳舞,1.0,0.0,song386195,album38259
11795,385970,世界,n,4,10.0,38247.0,知足 最真杰作选,精选辑,2005-08-26,3.0,乱世浮生,知足 最真杰作选,1.0,0.0,song385970,album38247
11953,385976,世界,n,6,10.0,38247.0,知足 最真杰作选,精选辑,2005-08-26,5.0,听不到,知足 最真杰作选,1.0,0.0,song385976,album38247
12105,386001,世界,n,1,10.0,38247.0,知足 最真杰作选,精选辑,2005-08-26,17.0,温柔 (还你自由版),知足 最真杰作选,1.0,0.0,song386001,album38247
12281,386025,世界,n,1,10.0,38247.0,知足 最真杰作选,精选辑,2005-08-26,24.0,OK 啦,知足 最真杰作选,1.0,0.0,song386025,album38247
5577,385887,世界,n,4,6.0,38241.0,为爱而生,录音室专辑,2006-12-29,2.0,为爱而生,为爱而生,1.0,0.0,song385887,album38241
5674,385891,世界,n,2,6.0,38241.0,为爱而生,录音室专辑,2006-12-29,3.0,天使,为爱而生,1.0,0.0,song385891,album38241
5756,385897,世界,n,9,6.0,38241.0,为爱而生,录音室专辑,2006-12-29,5.0,香水,为爱而生,1.0,0.0,song385897,album38241
5991,385905,世界,n,4,6.0,38241.0,为爱而生,录音室专辑,2006-12-29,7.0,最重要的小事,为爱而生,1.0,0.0,song385905,album38241
6288,385921,世界,n,2,6.0,38241.0,为爱而生,录音室专辑,2006-12-29,11.0,米老鼠,为爱而生,1.0,0.0,song385921,album38241
6803,385787,世界,n,1,7.0,38235.0,后青春期的诗,录音室专辑,2008-10-23,3.0,你不是真正的快乐,后青春期的诗,1.0,0.0,song385787,album38235
6980,385791,世界,n,1,7.0,38235.0,后青春期的诗,录音室专辑,2008-10-23,5.0,噢买尬,后青春期的诗,1.0,0.0,song385791,album38235
7286,385798,世界,n,4,7.0,38235.0,后青春期的诗,录音室专辑,2008-10-23,8.0,春天的呐喊,后青春期的诗,1.0,0.0,song385798,album38235
7461,22198018,世界,n,1,7.0,38235.0,后青春期的诗,录音室专辑,2008-10-23,9.0,夜访吸血鬼,后青春期的诗,1.0,0.0,song22198018,album38235
7632,22198023,世界,n,1,7.0,38235.0,后青春期的诗,录音室专辑,2008-10-23,10.0,如烟,后青春期的诗,1.0,0.0,song22198023,album38235
8071,22196002,世界,n,2,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,2.0,我不愿让你一个人,第二人生,1.0,0.0,song22196002,album2040001
8580,22197004,世界,n,1,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,5.0,三个傻瓜,第二人生,1.0,0.0,song22197004,album2040001
8753,22197007,世界,n,6,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,7.0,干杯,第二人生,1.0,0.0,song22197007,album2040001
8963,22197008,世界,n,2,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,8.0,仓颉,第二人生,1.0,0.0,song22197008,album2040001
9451,22197011,世界,n,1,8.0,2040001.0,第二人生 (明日版),录音室专辑,2011-12-16,11.0,诺亚方舟,第二人生,1.0,0.0,song22197011,album2040001
12503,28181103,世界,n,2,11.0,2740205.0,步步 自选作品辑,精选辑,2013-12-30,1.0,步步,步步 自选作品辑,1.0,0.0,song28181103,album2740205
10060,422094253,世界,n,1,9.0,34746073.0,自传,录音室专辑,2016-07-21,3.0,好好 (想把你写成一首歌),自传,1.0,0.0,song422094253,album34746073
10242,422094254,世界,n,1,9.0,34746073.0,自传,录音室专辑,2016-07-21,4.0,兄弟,自传,1.0,0.0,song422094254,album34746073
11034,422094255,世界,n,1,9.0,34746073.0,自传,录音室专辑,2016-07-21,10.0,少年他的奇幻漂流,自传,1.0,0.0,song422094255,album34746073
11246,422094256,世界,n,5,9.0,34746073.0,自传,录音室专辑,2016-07-21,12.0,任意门,自传,1.0,0.0,song422094256,album34746073
11493,422094257,世界,n,1,9.0,34746073.0,自传,录音室专辑,2016-07-21,13.0,转眼,自传,1.0,0.0,song422094257,album34746073

In [14]:
res_df = df_word[['song_id', 'song_name', 'album_fixed', 'release_date']].copy().reset_index(drop=True)
res_df['song_id'] = res_df['song_id'].astype(str)
res_df

      song_id      song_name album_fixed release_date
0      386925           疯狂世界     第一张创作专辑   1999-07-07
1      386927             拥抱     第一张创作专辑   1999-07-07
2      386930             生活     第一张创作专辑   1999-07-07
3      386931          爱情的模样     第一张创作专辑   1999-07-07
4      386939          HoSee     第一张创作专辑   1999-07-07
5      386942            黑白讲     第一张创作专辑   1999-07-07
6      386846             明白        爱情万岁   2000-07-07
7      386848          心中无别人        爱情万岁   2000-07-07
8      386851          有你的将来        爱情万岁   2000-07-07
9      386854             憨人        爱情万岁   2000-07-07
10     386863        罗密欧与茱丽叶        爱情万岁   2000-07-07
11     386866             温柔        爱情万岁   2000-07-07
12     386691           一颗苹果        人生海海   2001-07-06
13     386700             相信        人生海海   2001-07-06
14     386702            Ok啦        人生海海   2001-07-06
15     386715             纯真        人生海海   2001-07-06
16     386717           人生海海        人生海海   2001-07-06
17     386443             轻功         时光机   2003-11-11
18     386445          恒星的恒心         时光机   2003-11-11
19     386451           而我知道         时光机   2003-11-11
20     386479        生命有一种绝对         时光机   2003-11-11
21     386485            小时候         时光机   2003-11-11
22     386175             倔强    神的孩子都在跳舞   2004-11-05
23     386183           约翰蓝侬    神的孩子都在跳舞   2004-11-05
24     386191             超人    神的孩子都在跳舞   2004-11-05
25     386195          圣诞夜惊魂    神的孩子都在跳舞   2004-11-05
26     385970           乱世浮生    知足 最真杰作选   2005-08-26
27     385976            听不到    知足 最真杰作选   2005-08-26
28     386001     温柔 (还你自由版)    知足 最真杰作选   2005-08-26
29     386025           OK 啦    知足 最真杰作选   2005-08-26
30     385887           为爱而生        为爱而生   2006-12-29
31     385891             天使        为爱而生   2006-12-29
32     385897             香水        为爱而生   2006-12-29
33     385905         最重要的小事        为爱而生   2006-12-29
34     385921            米老鼠        为爱而生   2006-12-29
35     385787       你不是真正的快乐      后青春期的诗   2008-10-23
36     385791            噢买尬      后青春期的诗   2008-10-23
37     385798          春天的呐喊      后青春期的诗   2008-10-23
38   22198018          夜访吸血鬼      后青春期的诗   2008-10-23
39   22198023             如烟      后青春期的诗   2008-10-23
40   22196002       我不愿让你一个人        第二人生   2011-12-16
41   22197004           三个傻瓜        第二人生   2011-12-16
42   22197007             干杯        第二人生   2011-12-16
43   22197008             仓颉        第二人生   2011-12-16
44   22197011           诺亚方舟        第二人生   2011-12-16
45   28181103             步步    步步 自选作品辑   2013-12-30
46  422094253  好好 (想把你写成一首歌)          自传   2016-07-21
47  422094254             兄弟          自传   2016-07-21
48  422094255       少年他的奇幻漂流          自传   2016-07-21
49  422094256            任意门          自传   2016-07-21
50  422094257             转眼          自传   2016-07-21

In [15]:
res_df['lyric'] = res_df['song_id'].map(word_dict)
res_df

,song_id,song_name,album_fixed,release_date,lyric
0,386925,疯狂世界,第一张创作专辑,1999-07-07,"[为什么这个世界，总要叫人尝伤悲, 我好想好想飞，逃离这个疯狂世界, 我好想好想飞，逃离这个..."
1,386927,拥抱,第一张创作专辑,1999-07-07,[纷乱世界的不了解]
2,386930,生活,第一张创作专辑,1999-07-07,[活在疯狂世界，活在美好的明天]
3,386931,爱情的模样,第一张创作专辑,1999-07-07,"[教我勇敢地挑战全世界, 这世界全部的漂亮]"
4,386939,HoSee,第一张创作专辑,1999-07-07,[世界哪会颠三倒四]
5,386942,黑白讲,第一张创作专辑,1999-07-07,"[汝予我的世界只有一条路, 哪会世界拢无声音]"
6,386846,明白,爱情万岁,2000-07-07,[纵然是世界辽阔，外面的精彩好多]
7,386848,心中无别人,爱情万岁,2000-07-07,[开伤济气力，在这个世界，有小可仔无彩]
8,386851,有你的将来,爱情万岁,2000-07-07,[扰乱我原本平静的世界]
9,386854,憨人,爱情万岁,2000-07-07,[梦中的许个世界]
10,386863,罗密欧与茱丽叶,爱情万岁,2000-07-07,"[多希望世界就快要消失，好让我俩享受没有明天, 有一个漩涡，让我们躲避，真实世界，有什么刺激]"
11,386866,温柔,爱情万岁,2000-07-07,[没有关系，你的世界，就让你拥有]
12,386691,一颗苹果,人生海海,2001-07-06,[这世界给我的幽默]
13,386700,相信,人生海海,2001-07-06,[世界就睡在梦里]
14,386702,Ok啦,人生海海,2001-07-06,[世界欲共汝捙拚]
15,386715,纯真,人生海海,2001-07-06,"[世界被你掌握, 世界的纯真此刻为你有迷惑, 我以为世界是座宁静的宇宙]"
16,386717,人生海海,人生海海,2001-07-06,"[就算是整个世界，把我抛弃, 就算真的整个世界，把我抛弃]"
17,386443,轻功,时光机,2003-11-11,[人在江湖心不由己这世界又烦又粘腻]
18,386445,恒星的恒心,时光机,2003-11-11,[你要是落泪滴，世界都要下雨]
19,386451,而我知道,时光机,2003-11-11,[世界很大，（而我们应该长大）]
20,386479,生命有一种绝对,时光机,2003-11-11,[想要征服的世界，始终都没有改变]
21,386485,小时候,时光机,2003-11-11,"[风雨却让世界不同, 其实等在前面还有一整个世界]"
22,386175,倔强,神的孩子都在跳舞,2004-11-05,[当，我和世界不一样]
23,386183,约翰蓝侬,神的孩子都在跳舞,2004-11-05,"[Ok，再来，要世界为我们感动, 整个世界，曾经，都跟着你作梦]"
24,386191,超人,神的孩子都在跳舞,2004-11-05,"[世界如果被残酷攻击，只要给我一个电话亭, 世界如果被残酷攻击，谁来接手我的超能力]"
25,386195,圣诞夜惊魂,神的孩子都在跳舞,2004-11-05,[感谢有你，让平淡的世界，加了分]
26,385970,乱世浮生,知足 最真杰作选,2005-08-26,"[漂浮吧，飞过混乱世界, 漂浮吧，飞过混乱世界的逻辑]"
27,385976,听不到,知足 最真杰作选,2005-08-26,"[世界若是，那么大，为何我要忘你，无处逃, 世界若是，那么小，为何我的真心，你听不到]"
28,386001,温柔 (还你自由版),知足 最真杰作选,2005-08-26,[没有关系你的世界，就让你拥有]
29,386025,OK 啦,知足 最真杰作选,2005-08-26,[世界要和你车拼]
30,385887,为爱而生,为爱而生,2006-12-29,[我来到这个世界，这个人生为你而生存]
31,385891,天使,为爱而生,2006-12-29,[不管世界变得怎麽样，只要有你就会是天堂]
32,385897,香水,为爱而生,2006-12-29,"[献上快乐，献上伤悲，献上自我，献上世界, 啦啦啦啦啦，你想要世界，啦啦啦啦啦，就给你世界,..."
33,385905,最重要的小事,为爱而生,2006-12-29,[世界纷纷扰扰喧喧闹闹]
34,385921,米老鼠,为爱而生,2006-12-29,[醒了世界依然残酷]
35,385787,你不是真正的快乐,后青春期的诗,2008-10-23,[这世界笑了，于是你合群的一起笑了]
36,385791,噢买尬,后青春期的诗,2008-10-23,[整个世界只剩下你听我说话]
37,385798,春天的呐喊,后青春期的诗,2008-10-23,[一生能有几次，跟世界宣战]
38,22198018,夜访吸血鬼,后青春期的诗,2008-10-23,[黯淡的月照亮世界]
39,22198023,如烟,后青春期的诗,2008-10-23,[有没有那么一个世界，永远不天黑]
40,22196002,我不愿让你一个人,第二人生,2011-12-16,[我不愿让你一个人承受这世界的残忍]
41,22197004,三个傻瓜,第二人生,2011-12-16,[世界如果平的，为何人们，都要往上爬]
42,22197007,干杯,第二人生,2011-12-16,"[现在就是那个未来那个世界, 一起走到未来的世界, 也许会有一天世界真的有终点]"
43,22197008,仓颉,第二人生,2011-12-16,"[能不能飞越过，猜忌和冷漠，世界, 想逆转时间，回到，最开始，有你的世界]"
44,22197011,诺亚方舟,第二人生,2011-12-16,[还是要告别，还是放弃海拔以下的世界]
45,28181103,步步,步步 自选作品辑,2013-12-30,"[世界已灰飞烟灭, 你却占据了整个世界]"
46,422094253,好好 (想把你写成一首歌),自传,2016-07-21,[世界再大不过，你我凝视的微笑]
47,422094254,兄弟,自传,2016-07-21,[曾以为世界，想怎样就怎样]
48,422094255,少年他的奇幻漂流,自传,2016-07-21,[如果世界只剩你我存在]
49,422094256,任意门,自传,2016-07-21,"[你问我全世界是哪里最美，答案是你身边, 平凡的我们，也将回到，平凡的世界, 每个梦都，像任..."
50,422094257,转眼,自传,2016-07-21,[世界曾疯狂，爱情曾绽放]

In [16]:
res_dict = res_df.to_dict('records')
res_dict

[{'song_id': '386925',
  'song_name': '疯狂世界',
  'album_fixed': '第一张创作专辑',
  'release_date': '1999-07-07',
  'lyric': ['为什么这个世界，总要叫人尝伤悲', '我好想好想飞，逃离这个疯狂世界', '我好想好想飞，逃离这个疯狂的世界']},
 {'song_id': '386927',
  'song_name': '拥抱',
  'album_fixed': '第一张创作专辑',
  'release_date': '1999-07-07',
  'lyric': ['纷乱世界的不了解']},
 {'song_id': '386930',
  'song_name': '生活',
  'album_fixed': '第一张创作专辑',
  'release_date': '1999-07-07',
  'lyric': ['活在疯狂世界，活在美好的明天']},
 {'song_id': '386931',
  'song_name': '爱情的模样',
  'album_fixed': '第一张创作专辑',
  'release_date': '1999-07-07',
  'lyric': ['教我勇敢地挑战全世界', '这世界全部的漂亮']},
 {'song_id': '386939',
  'song_name': 'HoSee',
  'album_fixed': '第一张创作专辑',
  'release_date': '1999-07-07',
  'lyric': ['世界哪会颠三倒四']},
 {'song_id': '386942',
  'song_name': '黑白讲',
  'album_fixed': '第一张创作专辑',
  'release_date': '1999-07-07',
  'lyric': ['汝予我的世界只有一条路', '哪会世界拢无声音']},
 {'song_id': '386846',
  'song_name': '明白',
  'album_fixed': '爱情万岁',
  'release_date': '2000-07-07',
  'lyric': ['纵然是世界辽阔，外面的精彩好多']},
 {'song_id': '386848',
  'song_name': '心中无别人',
  'album_fixed': '爱情万岁',
  'release_date': '2000-07-07',
  'lyric': ['开伤济气力，在这个世界，有小可仔无彩']},
 {'song_id': '386851',
  'song_name': '有你的将来',
  'album_fixed': '爱情万岁',
  'release_date': '2000-07-07',
  'lyric': ['扰乱我原本平静的世界']},
 {'song_id': '386854',
  'song_name': '憨人',
  'album_fixed': '爱情万岁',
  'release_date': '2000-07-07',
  'lyric': ['梦中的许个世界']},
 {'song_id': '386863',
  'song_name': '罗密欧与茱丽叶',
  'album_fixed': '爱情万岁',
  'release_date': '2000-07-07',
  'lyric': ['多希望世界就快要消失，好让我俩享受没有明天', '有一个漩涡，让我们躲避，真实世界，有什么刺激']},
 {'song_id': '386866',
  'song_name': '温柔',
  'album_fixed': '爱情万岁',
  'release_date': '2000-07-07',
  'lyric': ['没有关系，你的世界，就让你拥有']},
 {'song_id': '386691',
  'song_name': '一颗苹果',
  'album_fixed': '人生海海',
  'release_date': '2001-07-06',
  'lyric': ['这世界给我的幽默']},
 {'song_id': '386700',
  'song_name': '相信',
  'album_fixed': '人生海海',
  'release_date': '2001-07-06',
  'lyric': ['世界就睡在梦里']},
 {'song_id': '386702',
  'song_name': 'Ok啦',
  'album_fixed': '人生海海',
  'release_date': '2001-07-06',
  'lyric': ['世界欲共汝捙拚']},
 {'song_id': '386715',
  'song_name': '纯真',
  'album_fixed': '人生海海',
  'release_date': '2001-07-06',
  'lyric': ['世界被你掌握', '世界的纯真此刻为你有迷惑', '我以为世界是座宁静的宇宙']},
 {'song_id': '386717',
  'song_name': '人生海海',
  'album_fixed': '人生海海',
  'release_date': '2001-07-06',
  'lyric': ['就算是整个世界，把我抛弃', '就算真的整个世界，把我抛弃']},
 {'song_id': '386443',
  'song_name': '轻功',
  'album_fixed': '时光机',
  'release_date': '2003-11-11',
  'lyric': ['人在江湖心不由己这世界又烦又粘腻']},
 {'song_id': '386445',
  'song_name': '恒星的恒心',
  'album_fixed': '时光机',
  'release_date': '2003-11-11',
  'lyric': ['你要是落泪滴，世界都要下雨']},
 {'song_id': '386451',
  'song_name': '而我知道',
  'album_fixed': '时光机',
  'release_date': '2003-11-11',
  'lyric': ['世界很大，（而我们应该长大）']},
 {'song_id': '386479',
  'song_name': '生命有一种绝对',
  'album_fixed': '时光机',
  'release_date': '2003-11-11',
  'lyric': ['想要征服的世界，始终都没有改变']},
 {'song_id': '386485',
  'song_name': '小时候',
  'album_fixed': '时光机',
  'release_date': '2003-11-11',
  'lyric': ['风雨却让世界不同', '其实等在前面还有一整个世界']},
 {'song_id': '386175',
  'song_name': '倔强',
  'album_fixed': '神的孩子都在跳舞',
  'release_date': '2004-11-05',
  'lyric': ['当，我和世界不一样']},
 {'song_id': '386183',
  'song_name': '约翰蓝侬',
  'album_fixed': '神的孩子都在跳舞',
  'release_date': '2004-11-05',
  'lyric': ['Ok，再来，要世界为我们感动', '整个世界，曾经，都跟着你作梦']},
 {'song_id': '386191',
  'song_name': '超人',
  'album_fixed': '神的孩子都在跳舞',
  'release_date': '2004-11-05',
  'lyric': ['世界如果被残酷攻击，只要给我一个电话亭', '世界如果被残酷攻击，谁来接手我的超能力']},
 {'song_id': '386195',
  'song_name': '圣诞夜惊魂',
  'album_fixed': '神的孩子都在跳舞',
  'release_date': '2004-11-05',
  'lyric': ['感谢有你，让平淡的世界，加了分']},
 {'song_id': '385970',
  'song_name': '乱世浮生',
  'album_fixed': '知足 最真杰作选',
  'release_date': '2005-08-26',
  'lyric': ['漂浮吧，飞过混乱世界', '漂浮吧，飞过混乱世界的逻辑']},
 {'song_id': '385976',
  'song_name': '听不到',
  'album_fixed': '知足 最真杰作选',
  'release_date': '2005-08-26',
  'lyric': ['世界若是，那么大，为何我要忘你，无处逃', '世界若是，那么小，为何我的真心，你听不到']},
 {'song_id': '386001',
  'song_name': '温柔 (还你自由版)',
  'album_fixed': '知足 最真杰作选',
  'release_date': '2005-08-26',
  'lyric': ['没有关系你的世界，就让你拥有']},
 {'song_id': '386025',
  'song_name': 'OK 啦',
  'album_fixed': '知足 最真杰作选',
  'release_date': '2005-08-26',
  'lyric': ['世界要和你车拼']},
 {'song_id': '385887',
  'song_name': '为爱而生',
  'album_fixed': '为爱而生',
  'release_date': '2006-12-29',
  'lyric': ['我来到这个世界，这个人生为你而生存']},
 {'song_id': '385891',
  'song_name': '天使',
  'album_fixed': '为爱而生',
  'release_date': '2006-12-29',
  'lyric': ['不管世界变得怎麽样，只要有你就会是天堂']},
 {'song_id': '385897',
  'song_name': '香水',
  'album_fixed': '为爱而生',
  'release_date': '2006-12-29',
  'lyric': ['献上快乐，献上伤悲，献上自我，献上世界',
   '啦啦啦啦啦，你想要世界，啦啦啦啦啦，就给你世界',
   '为你献上快乐伤悲，为你献上我的世界']},
 {'song_id': '385905',
  'song_name': '最重要的小事',
  'album_fixed': '为爱而生',
  'release_date': '2006-12-29',
  'lyric': ['世界纷纷扰扰喧喧闹闹']},
 {'song_id': '385921',
  'song_name': '米老鼠',
  'album_fixed': '为爱而生',
  'release_date': '2006-12-29',
  'lyric': ['醒了世界依然残酷']},
 {'song_id': '385787',
  'song_name': '你不是真正的快乐',
  'album_fixed': '后青春期的诗',
  'release_date': '2008-10-23',
  'lyric': ['这世界笑了，于是你合群的一起笑了']},
 {'song_id': '385791',
  'song_name': '噢买尬',
  'album_fixed': '后青春期的诗',
  'release_date': '2008-10-23',
  'lyric': ['整个世界只剩下你听我说话']},
 {'song_id': '385798',
  'song_name': '春天的呐喊',
  'album_fixed': '后青春期的诗',
  'release_date': '2008-10-23',
  'lyric': ['一生能有几次，跟世界宣战']},
 {'song_id': '22198018',
  'song_name': '夜访吸血鬼',
  'album_fixed': '后青春期的诗',
  'release_date': '2008-10-23',
  'lyric': ['黯淡的月照亮世界']},
 {'song_id': '22198023',
  'song_name': '如烟',
  'album_fixed': '后青春期的诗',
  'release_date': '2008-10-23',
  'lyric': ['有没有那么一个世界，永远不天黑']},
 {'song_id': '22196002',
  'song_name': '我不愿让你一个人',
  'album_fixed': '第二人生',
  'release_date': '2011-12-16',
  'lyric': ['我不愿让你一个人承受这世界的残忍']},
 {'song_id': '22197004',
  'song_name': '三个傻瓜',
  'album_fixed': '第二人生',
  'release_date': '2011-12-16',
  'lyric': ['世界如果平的，为何人们，都要往上爬']},
 {'song_id': '22197007',
  'song_name': '干杯',
  'album_fixed': '第二人生',
  'release_date': '2011-12-16',
  'lyric': ['现在就是那个未来那个世界', '一起走到未来的世界', '也许会有一天世界真的有终点']},
 {'song_id': '22197008',
  'song_name': '仓颉',
  'album_fixed': '第二人生',
  'release_date': '2011-12-16',
  'lyric': ['能不能飞越过，猜忌和冷漠，世界', '想逆转时间，回到，最开始，有你的世界']},
 {'song_id': '22197011',
  'song_name': '诺亚方舟',
  'album_fixed': '第二人生',
  'release_date': '2011-12-16',
  'lyric': ['还是要告别，还是放弃海拔以下的世界']},
 {'song_id': '28181103',
  'song_name': '步步',
  'album_fixed': '步步 自选作品辑',
  'release_date': '2013-12-30',
  'lyric': ['世界已灰飞烟灭', '你却占据了整个世界']},
 {'song_id': '422094253',
  'song_name': '好好 (想把你写成一首歌)',
  'album_fixed': '自传',
  'release_date': '2016-07-21',
  'lyric': ['世界再大不过，你我凝视的微笑']},
 {'song_id': '422094254',
  'song_name': '兄弟',
  'album_fixed': '自传',
  'release_date': '2016-07-21',
  'lyric': ['曾以为世界，想怎样就怎样']},
 {'song_id': '422094255',
  'song_name': '少年他的奇幻漂流',
  'album_fixed': '自传',
  'release_date': '2016-07-21',
  'lyric': ['如果世界只剩你我存在']},
 {'song_id': '422094256',
  'song_name': '任意门',
  'album_fixed': '自传',
  'release_date': '2016-07-21',
  'lyric': ['你问我全世界是哪里最美，答案是你身边',
   '平凡的我们，也将回到，平凡的世界',
   '每个梦都，像任意门，往不同世界，而你的故事，现在正是起点',
   '我们曾走过，无数地方，和无尽岁月，搭着肩环游，无法遗忘，的光辉世界']},
 {'song_id': '422094257',
  'song_name': '转眼',
  'album_fixed': '自传',
  'release_date': '2016-07-21',
  'lyric': ['世界曾疯狂，爱情曾绽放']}]

In [17]:
with open('output/single_word_data.json', 'w', encoding='utf-8') as f:
    json.dump(res_dict, f, ensure_ascii=False, indent=4)