# 电影圈数据

In [1]:
import pandas as pd
import numpy as np
import networkx as nx
import scipy
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['Heiti TC']
plt.rcParams['axes.unicode_minus'] = False
from networkx.algorithms import bipartite

In [2]:
import sys
sys.path.append("..")

# 数据处理

## 原始数据

In [3]:
df_raw = pd.read_csv("dwd_cast_works.csv")
df_raw.head()

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,k_genres,is_rating,rating_num,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray
0,1007816,凌玲,女,10767181,演员,是,5,10767181,妙手千金,电影,...,喜剧/动作,无评分,NaN,暂无评分,NaN,NaN,21534411,2015681,1,NaN
1,1003352,金焰,男,10618303,演员,是,1,10618303,失去的爱情,电影,...,爱情,无评分,NaN,暂无评分,NaN,NaN,21236655,2006753,2,NaN
2,1003352,金焰,男,10601198,演员,是,1,10601198,人道,电影,...,剧情,无评分,NaN,暂无评分,NaN,NaN,21202445,2006753,3,NaN
3,1003352,金焰,男,10566664,演员,是,2,10566664,母亲,电影,...,剧情,无评分,NaN,暂无评分,NaN,NaN,21133377,2006753,4,老邓
4,1013885,阿美莉嘉·奥利沃,女,10727641,演员,是,21,10727641,碟中谍5：神秘国度,电影,...,动作/惊悚/冒险,有评分,7.8,292193,292193.0,1510.0,21455331,2027819,5,Turandot

## 数据筛选
过滤条件
1. 电影
2. 有评分
3. 地区不含其他合拍

In [4]:
# df_movie = df_raw.loc[(df_raw['k_type'] == '电影')
#                       & (df_raw['k_region'].str.contains('中国'))].copy()
df_movie = df_raw.loc[(df_raw['k_region'] != '其他合拍')].copy()
# k_cast_id转为str
df_movie['k_cast_id'] = df_movie['k_cast_id'].apply(lambda x: str(x))
# 仅保留演员，导演，编剧数据
df_movie = df_movie[df_movie['k_role'].isin(['演员', '导演', '编剧'])]
df_movie = df_movie.reset_index(drop=True).copy(deep=True)
# 添加新的movie_id_m列
df_movie['movie_id_m'] = df_movie['k_movie_id'].apply(lambda x: 'm' + str(x))
df_movie

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,is_rating,rating_num,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray,movie_id_m
0,1007816,凌玲,女,10767181,演员,是,5,10767181,妙手千金,电影,...,无评分,NaN,暂无评分,NaN,NaN,21534411,2015681,1,NaN,m21534411
1,1003352,金焰,男,10618303,演员,是,1,10618303,失去的爱情,电影,...,无评分,NaN,暂无评分,NaN,NaN,21236655,2006753,2,NaN,m21236655
2,1003352,金焰,男,10601198,演员,是,1,10601198,人道,电影,...,无评分,NaN,暂无评分,NaN,NaN,21202445,2006753,3,NaN,m21202445
3,1003352,金焰,男,10566664,演员,是,2,10566664,母亲,电影,...,无评分,NaN,暂无评分,NaN,NaN,21133377,2006753,4,老邓,m21133377
4,1003424,蒋君超,男,10777680,演员,是,2,10777680,影坛风月,电影,...,无评分,NaN,暂无评分,NaN,NaN,21555409,2006897,6,NaN,m21555409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494104,34951835,李卿,男,36744438,演员,是,17,36744438,书卷一梦,电视剧,...,无评分,NaN,暂无评分,NaN,NaN,73488925,69903719,608471,断山虎,m73488925
494105,35415094,张可,女,7053738,演员,否,999,7053738,樱桃,电视剧,...,有评分,5.7,2003,2003.0,107.0,14107525,70830237,608472,NaN,m14107525
494106,1314059,徐小凤,女,26901136,演员,否,999,26901136,天龙酒店,电影,...,无评分,NaN,暂无评分,NaN,NaN,53802321,2628167,608473,NaN,m53802321
494107,1385616,马英智,男,34925531,演员,是,3,34925531,小戏骨：红色娘子军,电视剧,...,无评分,NaN,暂无评分,NaN,NaN,69851111,2771281,608474,南霸天,m69851111
494108,1425269,郭莹莹,女,2053668,演员,否,999,2053668,寄生人,电影,...,有评分,5.4,1965,1965.0,103.0,4107385,2850587,608476,NaN,m4107385

In [5]:
df_movie[df_movie['k_title'] == '让子弹飞']

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,is_rating,rating_num,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray,movie_id_m
25771,30276936,陈磊,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,60553921,31108,受辱民女夫,m7484769
57316,27504347,杨奇雨,男,3742360,演员,是,21,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008743,69834,胡百,m7484769
94695,27250655,周润发,男,3742360,演员,是,3,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54501359,115968,黄四郎 / 杨万楼,m7484769
106624,27238280,胡军,男,3742360,演员,是,14,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54476609,130630,假张麻子,m7484769
112259,27504256,述平,男,3742360,编剧,是,2,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008561,137532,NaN,m7484769
128910,27481219,冯小刚,男,3742360,演员,是,13,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54962487,158077,汤师爷,m7484769
131480,30276937,沙瑀,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,60553923,161321,鹅人,m7484769
156272,27504255,朱苏进,男,3742360,编剧,是,1,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008559,191744,NaN,m7484769
172038,27495331,郭俊立,男,3742360,编剧,是,4,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54990711,211396,NaN,m7484769
172900,27232187,张默,男,3742360,演员,是,6,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54464423,212475,老六,m7484769
179571,27243602,周韵,女,3742360,演员,是,8,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54487253,220678,花姐,m7484769
217540,27206595,葛优,男,3742360,演员,是,2,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54413239,267740,马邦德,m7484769
221613,27504343,马珂,男,3742360,演员,是,15,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008735,272727,八岁,m7484769
223321,27554161,姜洪齐,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55108371,274858,搓麻老头,m7484769
252302,27548156,文祥,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55096361,310570,杨万楼,m7484769
252935,27547738,马元,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55095525,311361,牧师,m7484769
265933,27480657,姜武,男,3742360,演员,是,7,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54961363,327353,武智冲,m7484769
290296,27504346,胡明,男,3742360,演员,是,19,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008741,357413,孙守义,m7484769
291540,27504340,危笑,男,3742360,演员,是,20,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008729,358971,老七,m7484769
291541,27504340,危笑,男,3742360,编剧,是,5,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008729,358972,NaN,m7484769
302924,27242654,刘嘉玲,女,3742360,演员,是,4,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54485357,373068,县长夫人,m7484769
338395,27227726,姜文,男,3742360,演员,是,1,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54455501,416676,张牧之,m7484769
338396,27227726,姜文,男,3742360,编剧,是,3,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54455501,416677,NaN,m7484769
338397,27227726,姜文,男,3742360,导演,是,1,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54455501,416678,NaN,m7484769
397592,27504293,白冰,女,3742360,演员,是,16,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008635,489544,黛玉晴雯,m7484769
406799,27213092,廖凡,男,3742360,演员,是,9,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54426233,500848,老三,m7484769
414017,27259386,陈坤,男,3742360,演员,是,5,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54518821,509608,胡万,m7484769
422037,27480671,李静,男,3742360,演员,是,18,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54961391,519532,老五,m7484769
422133,27495323,邵兵,男,3742360,演员,是,11,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54990695,519647,老二,m7484769
454541,27480664,姚橹,男,3742360,演员,是,10,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54961377,559491,胡千,m7484769
454929,27504009,赵铭,女,3742360,演员,是,22,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008067,559975,民女,m7484769
472467,27504344,杜奕衡,男,3742360,演员,是,17,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008737,581706,老四,m7484769
472982,27239591,苗圃,女,3742360,演员,是,12,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54479231,582328,陕西老婆,m7484769
476521,27222251,绀野千春,女,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,54444551,586698,鼓女,m7484769
477909,30276938,吴昔果,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,60553925,588425,军官,m7484769
488040,27504341,李不空,男,3742360,编剧,是,6,3742360,让子弹飞,电影,...,有评分,9.0,1571537,1571537.0,3761.0,7484769,55008731,600904,NaN,m7484769

## 影人职责合并

In [6]:
# 合并影人职责
df_cast = df_movie[['k_cast_id', 'cast_name', 'k_role']].drop_duplicates()
df_cast_agg = df_cast.groupby(['k_cast_id', 'cast_name'])['k_role'].apply(lambda x: '/'.join(sorted(x.unique()))).reset_index()
df_cast_agg

      k_cast_id cast_name k_role
0       2000437       李香凝     演员
1       2000457    吉娜·卡拉诺     演员
2       2000515   理查德·格里克     演员
3       2000941        司汗     演员
4       2001011    凯文·格劳特     导演
...         ...       ...    ...
61324  76124367       张若伊     编剧
61325  76135081       何田田     演员
61326  76349227       方誉媛     演员
61327  76350573       景德军     导演
61328  76350605       谢十三     编剧

[61329 rows x 3 columns]

In [7]:
df_movie['cast_role_agg'] = df_movie['k_cast_id'].map(
    df_cast_agg.set_index('k_cast_id')['k_role']
)
df_movie

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,rating_num,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray,movie_id_m,cast_role_agg
0,1007816,凌玲,女,10767181,演员,是,5,10767181,妙手千金,电影,...,NaN,暂无评分,NaN,NaN,21534411,2015681,1,NaN,m21534411,演员
1,1003352,金焰,男,10618303,演员,是,1,10618303,失去的爱情,电影,...,NaN,暂无评分,NaN,NaN,21236655,2006753,2,NaN,m21236655,演员
2,1003352,金焰,男,10601198,演员,是,1,10601198,人道,电影,...,NaN,暂无评分,NaN,NaN,21202445,2006753,3,NaN,m21202445,演员
3,1003352,金焰,男,10566664,演员,是,2,10566664,母亲,电影,...,NaN,暂无评分,NaN,NaN,21133377,2006753,4,老邓,m21133377,演员
4,1003424,蒋君超,男,10777680,演员,是,2,10777680,影坛风月,电影,...,NaN,暂无评分,NaN,NaN,21555409,2006897,6,NaN,m21555409,导演/演员
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494104,34951835,李卿,男,36744438,演员,是,17,36744438,书卷一梦,电视剧,...,NaN,暂无评分,NaN,NaN,73488925,69903719,608471,断山虎,m73488925,演员
494105,35415094,张可,女,7053738,演员,否,999,7053738,樱桃,电视剧,...,5.7,2003,2003.0,107.0,14107525,70830237,608472,NaN,m14107525,演员
494106,1314059,徐小凤,女,26901136,演员,否,999,26901136,天龙酒店,电影,...,NaN,暂无评分,NaN,NaN,53802321,2628167,608473,NaN,m53802321,演员
494107,1385616,马英智,男,34925531,演员,是,3,34925531,小戏骨：红色娘子军,电视剧,...,NaN,暂无评分,NaN,NaN,69851111,2771281,608474,南霸天,m69851111,演员
494108,1425269,郭莹莹,女,2053668,演员,否,999,2053668,寄生人,电影,...,5.4,1965,1965.0,103.0,4107385,2850587,608476,NaN,m4107385,演员

In [8]:
df_movie[df_movie['cast_name'] == '张艺谋']

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,rating_num,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray,movie_id_m,cast_role_agg
729,27260166,张艺谋,男,1292365,导演,是,1,1292365,活着,电影,...,9.3,678477,678477.0,2512.0,2584779,54520381,762,NaN,m2584779,导演/演员/编剧
3939,27260166,张艺谋,男,1294963,导演,是,1,1294963,一个都不能少,电影,...,7.7,120767,120767.0,964.0,2589975,54520381,4254,NaN,m2589975,导演/演员/编剧
7799,27260166,张艺谋,男,35294995,演员,是,40,35294995,我和我的父辈,电影,...,6.9,175739,175739.0,1101.0,70590039,54520381,9029,电视台台长,m70590039,导演/演员/编剧
15527,27260166,张艺谋,男,1294007,导演,是,1,1294007,我的父亲母亲,电影,...,8.2,116620,116620.0,978.0,2588063,54520381,18493,NaN,m2588063,导演/演员/编剧
27119,27260166,张艺谋,男,1308070,演员,是,1,1308070,老井,电影,...,8.0,16354,16354.0,362.0,2616189,54520381,32761,孙旺泉,m2616189,导演/演员/编剧
38566,27260166,张艺谋,男,26694491,导演,是,1,26694491,大红灯笼高高挂,电影,...,8.8,3372,3372.0,172.0,53389031,54520381,46781,NaN,m53389031,导演/演员/编剧
42327,27260166,张艺谋,男,1297879,演员,否,999,1297879,大阅兵,电影,...,6.8,1946,1946.0,115.0,2595807,54520381,51418,军官,m2595807,导演/演员/编剧
107457,27260166,张艺谋,男,35215390,编剧,是,2,35215390,狙击手,电影,...,7.7,340264,340264.0,1619.0,70430829,54520381,131623,NaN,m70430829,导演/演员/编剧
107458,27260166,张艺谋,男,35215390,导演,是,1,35215390,狙击手,电影,...,7.7,340264,340264.0,1619.0,70430829,54520381,131624,NaN,m70430829,导演/演员/编剧
107469,27260166,张艺谋,男,33447633,导演,是,1,33447633,坚如磐石,电影,...,6.0,344998,344998.0,1439.0,66895315,54520381,131636,NaN,m66895315,导演/演员/编剧
126490,27260166,张艺谋,男,32493124,编剧,是,2,32493124,悬崖之上,电影,...,7.6,597494,597494.0,2131.0,64986297,54520381,155013,NaN,m64986297,导演/演员/编剧
126491,27260166,张艺谋,男,32493124,导演,是,1,32493124,悬崖之上,电影,...,7.6,597494,597494.0,2131.0,64986297,54520381,155014,NaN,m64986297,导演/演员/编剧
134134,27260166,张艺谋,男,1296436,演员,是,8,1296436,有话好好说,电影,...,8.3,170972,170972.0,1191.0,2592921,54520381,164582,收废品的,m2592921,导演/演员/编剧
134135,27260166,张艺谋,男,1296436,导演,是,1,1296436,有话好好说,电影,...,8.3,170972,170972.0,1191.0,2592921,54520381,164583,NaN,m2592921,导演/演员/编剧
157165,27260166,张艺谋,男,3718447,导演,是,1,3718447,三枪拍案惊奇,电影,...,4.7,105825,105825.0,705.0,7436943,54520381,192848,NaN,m7436943,导演/演员/编剧
164710,27260166,张艺谋,男,30257787,导演,是,1,30257787,一秒钟,电影,...,7.7,221244,221244.0,1305.0,60515623,54520381,202206,NaN,m60515623,导演/演员/编剧
164711,27260166,张艺谋,男,30257787,编剧,是,1,30257787,一秒钟,电影,...,7.7,221244,221244.0,1305.0,60515623,54520381,202207,NaN,m60515623,导演/演员/编剧
179956,27260166,张艺谋,男,1499008,编剧,是,1,1499008,满城尽带黄金甲,电影,...,5.7,215173,215173.0,1107.0,2998065,54520381,221152,NaN,m2998065,导演/演员/编剧
179957,27260166,张艺谋,男,1499008,导演,是,1,1499008,满城尽带黄金甲,电影,...,5.7,215173,215173.0,1107.0,2998065,54520381,221153,NaN,m2998065,导演/演员/编剧
187640,27260166,张艺谋,男,34952523,导演,是,1,34952523,张艺谋导演团队竖屏美学系列微电影,电视剧,...,NaN,暂无评分,NaN,NaN,69905095,54520381,230648,NaN,m69905095,导演/演员/编剧
191441,27260166,张艺谋,男,1306505,导演,是,1,1306505,红高粱,电影,...,8.4,208700,208700.0,1324.0,2613059,54520381,235344,NaN,m2613059,导演/演员/编剧
191453,27260166,张艺谋,男,1300082,演员,是,1,1300082,古今大战秦俑情,电影,...,7.0,42560,42560.0,546.0,2600213,54520381,235359,NaN,m2600213,导演/演员/编剧
195409,27260166,张艺谋,男,21352814,导演,是,1,21352814,归来,电影,...,8.0,343231,343231.0,1657.0,42705677,54520381,240245,NaN,m42705677,导演/演员/编剧
241444,27260166,张艺谋,男,1300108,导演,是,1,1300108,秋菊打官司,电影,...,8.1,82892,82892.0,819.0,2600265,54520381,297095,NaN,m2600265,导演/演员/编剧
252791,27260166,张艺谋,男,2181930,演员,是,7,2181930,大宅门,电视剧,...,9.4,125227,125227.0,1085.0,4363909,54520381,311161,李莲英,m4363909,导演/演员/编剧
260483,27260166,张艺谋,男,1308722,编剧,是,3,1308722,十面埋伏,电影,...,6.3,181175,181175.0,1068.0,2617493,54520381,320632,NaN,m2617493,导演/演员/编剧
260484,27260166,张艺谋,男,1308722,导演,是,1,1308722,十面埋伏,电影,...,6.3,181175,181175.0,1068.0,2617493,54520381,320633,NaN,m2617493,导演/演员/编剧
268201,27260166,张艺谋,男,1306123,编剧,是,2,1306123,英雄,电影,...,7.5,256761,256761.0,1388.0,2612295,54520381,330150,NaN,m2612295,导演/演员/编剧
268202,27260166,张艺谋,男,1306123,导演,是,1,1306123,英雄,电影,...,7.5,256761,256761.0,1388.0,2612295,54520381,330151,NaN,m2612295,导演/演员/编剧
295063,27260166,张艺谋,男,1297743,导演,是,1,1297743,幸福时光,电影,...,7.1,20176,20176.0,378.0,2595535,54520381,363349,NaN,m2595535,导演/演员/编剧
337349,27260166,张艺谋,男,4151110,导演,是,1,4151110,山楂树之恋,电影,...,7.1,320035,320035.0,1507.0,8302269,54520381,415335,NaN,m8302269,导演/演员/编剧
391111,27260166,张艺谋,男,1301105,导演,是,1,1301105,代号美洲豹,电影,...,5.4,4464,4464.0,155.0,2602259,54520381,481589,NaN,m2602259,导演/演员/编剧
402763,27260166,张艺谋,男,35766491,导演,是,1,35766491,满江红,电影,...,7.0,1081340,1081340.0,2751.0,71533031,54520381,495911,NaN,m71533031,导演/演员/编剧
402764,27260166,张艺谋,男,35766491,编剧,是,2,35766491,满江红,电影,...,7.0,1081340,1081340.0,2751.0,71533031,54520381,495912,NaN,m71533031,导演/演员/编剧
406529,27260166,张艺谋,男,4864908,导演,是,1,4864908,影,电影,...,7.2,518996,518996.0,1933.0,9729865,54520381,500514,NaN,m9729865,导演/演员/编剧
406530,27260166,张艺谋,男,4864908,编剧,是,2,4864908,影,电影,...,7.2,518996,518996.0,1933.0,9729865,54520381,500515,NaN,m9729865,导演/演员/编剧
460430,27260166,张艺谋,男,36208094,导演,是,1,36208094,第二十条,电影,...,7.5,766017,766017.0,2397.0,72416237,54520381,566779,NaN,m72416237,导演/演员/编剧
460431,27260166,张艺谋,男,36208094,编剧,是,2,36208094,第二十条,电影,...,7.5,766017,766017.0,2397.0,72416237,54520381,566780,NaN,m72416237,导演/演员/编剧
468099,27260166,张艺谋,男,3649049,导演,是,1,3649049,金陵十三钗,电影,...,8.3,655195,655195.0,2332.0,7298147,54520381,576241,NaN,m7298147,导演/演员/编剧

## 主演数据

In [12]:
# 每部电影的主要演员，is_main_cast==‘是’， k_role==‘演员’, index小于=5
# 为每行添加一个main_cast列，按k_movie_id分组，按is_main_cast==‘是’，k_role=='演员'降序，index升序排序后，取前5个演员的cast_name连接起来
# 1. 筛选并排序：只保留“是演员”且“是主演”的行，按 index 升序
cast_sorted = df_movie[(df_movie['is_main_cast'] == '是') & (df_movie['k_role'] == '演员')] \
    .sort_values(by=['k_movie_id', 'index'], ascending=[True, True])

# 2. 分组聚合：取每个电影前5名，用逗号连接
main_cast_series = cast_sorted.groupby('k_movie_id')['cast_name'] \
    .apply(lambda x: ', '.join(x.head(5)))

# 3. 映射回原表：使用 map 匹配 k_movie_id，确保索引正确
df_movie['main_cast'] = df_movie['k_movie_id'].map(main_cast_series)
df_movie[df_movie['k_title'] == '让子弹飞']

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray,movie_id_m,cast_role_agg,main_cast
25771,30276936,陈磊,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,60553921,31108,受辱民女夫,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
57316,27504347,杨奇雨,男,3742360,演员,是,21,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008743,69834,胡百,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
94695,27250655,周润发,男,3742360,演员,是,3,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54501359,115968,黄四郎 / 杨万楼,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
106624,27238280,胡军,男,3742360,演员,是,14,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54476609,130630,假张麻子,m7484769,导演/演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
112259,27504256,述平,男,3742360,编剧,是,2,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008561,137532,NaN,m7484769,演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
128910,27481219,冯小刚,男,3742360,演员,是,13,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54962487,158077,汤师爷,m7484769,导演/演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
131480,30276937,沙瑀,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,60553923,161321,鹅人,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
156272,27504255,朱苏进,男,3742360,编剧,是,1,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008559,191744,NaN,m7484769,编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
172038,27495331,郭俊立,男,3742360,编剧,是,4,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54990711,211396,NaN,m7484769,导演/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
172900,27232187,张默,男,3742360,演员,是,6,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54464423,212475,老六,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
179571,27243602,周韵,女,3742360,演员,是,8,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54487253,220678,花姐,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
217540,27206595,葛优,男,3742360,演员,是,2,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54413239,267740,马邦德,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
221613,27504343,马珂,男,3742360,演员,是,15,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008735,272727,八岁,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
223321,27554161,姜洪齐,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55108371,274858,搓麻老头,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
252302,27548156,文祥,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55096361,310570,杨万楼,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
252935,27547738,马元,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55095525,311361,牧师,m7484769,导演/演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
265933,27480657,姜武,男,3742360,演员,是,7,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54961363,327353,武智冲,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
290296,27504346,胡明,男,3742360,演员,是,19,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008741,357413,孙守义,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
291540,27504340,危笑,男,3742360,演员,是,20,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008729,358971,老七,m7484769,演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
291541,27504340,危笑,男,3742360,编剧,是,5,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008729,358972,NaN,m7484769,演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
302924,27242654,刘嘉玲,女,3742360,演员,是,4,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54485357,373068,县长夫人,m7484769,导演/演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
338395,27227726,姜文,男,3742360,演员,是,1,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54455501,416676,张牧之,m7484769,导演/演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
338396,27227726,姜文,男,3742360,编剧,是,3,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54455501,416677,NaN,m7484769,导演/演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
338397,27227726,姜文,男,3742360,导演,是,1,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54455501,416678,NaN,m7484769,导演/演员/编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
397592,27504293,白冰,女,3742360,演员,是,16,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008635,489544,黛玉晴雯,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
406799,27213092,廖凡,男,3742360,演员,是,9,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54426233,500848,老三,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
414017,27259386,陈坤,男,3742360,演员,是,5,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54518821,509608,胡万,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
422037,27480671,李静,男,3742360,演员,是,18,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54961391,519532,老五,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
422133,27495323,邵兵,男,3742360,演员,是,11,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54990695,519647,老二,m7484769,导演/演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
454541,27480664,姚橹,男,3742360,演员,是,10,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54961377,559491,胡千,m7484769,导演/演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
454929,27504009,赵铭,女,3742360,演员,是,22,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008067,559975,民女,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
472467,27504344,杜奕衡,男,3742360,演员,是,17,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008737,581706,老四,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
472982,27239591,苗圃,女,3742360,演员,是,12,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54479231,582328,陕西老婆,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
476521,27222251,绀野千春,女,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,54444551,586698,鼓女,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
477909,30276938,吴昔果,男,3742360,演员,否,999,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,60553925,588425,军官,m7484769,演员,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"
488040,27504341,李不空,男,3742360,编剧,是,6,3742360,让子弹飞,电影,...,1571537,1571537.0,3761.0,7484769,55008731,600904,NaN,m7484769,编剧,"姜文, 葛优, 周润发, 刘嘉玲, 陈坤"

## 有评分数据

In [13]:
df_movie_rated = df_movie[df_movie['is_rating'] == '有评分'].copy()
df_movie_rated = df_movie_rated.reset_index(drop=True).copy(deep=True)
df_movie_rated

,cast_id,cast_name,gender,movie_id,k_role,is_main_cast,index,id,k_title,k_type,...,rating_people,k_rating_people,rating_index,k_movie_id,k_cast_id,uid,portray,movie_id_m,cast_role_agg,main_cast
0,1017182,陈燕燕,女,10771202,演员,是,1,10771202,深闺疑云,电影,...,92,92.0,27.0,21542453,2034413,54,赵兰,m21542453,演员,"陈燕燕, 谢添"
1,1043845,刘志荣,男,10581318,演员,是,11,10581318,四大家族之龙虎兄弟,电影,...,2290,2290.0,134.0,21162685,2087739,75,NaN,m21162685,导演/演员/编剧,"郑则仕, 吕良伟, 利智, 曾江, 黄光亮"
2,1050373,茅瑛,女,10573512,演员,是,1,10573512,鬼娘子,电影,...,235,235.0,37.0,21147073,2100795,79,NaN,m21147073,演员,"茅瑛, 林威"
3,1124360,利智,女,10581318,演员,是,3,10581318,四大家族之龙虎兄弟,电影,...,2290,2290.0,134.0,21162685,2248769,94,NaN,m21162685,演员,"郑则仕, 吕良伟, 利智, 曾江, 黄光亮"
4,1314471,王挺,男,10531190,演员,是,1,10531190,惊天动地,电视剧,...,326,326.0,53.0,21062429,2628991,147,NaN,m21062429,导演/演员/编剧,"王挺, 李易祥, 王双宝"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283251,1354509,林泳淘,女,26984991,演员,否,999,26984991,婚姻合伙人,电视剧,...,1259,1259.0,85.0,53970031,2709067,608462,邓秀玉,m53970031,演员,"黄淑仪, 杨明, 高海宁, 黄德斌, 陆永"
283252,27496534,刘芊蒂,女,2337597,演员,是,2,2337597,操行零分,电影,...,211,211.0,38.0,4675243,54993117,608466,NaN,m4675243,演员,"何启南, 刘芊蒂"
283253,27565771,董亚春,女,2270516,导演,是,2,2270516,八月一日,电影,...,1123,1123.0,85.0,4541081,55131591,608467,NaN,m4541081,导演,"刘劲, 侯勇, 吕良伟"
283254,35415094,张可,女,7053738,演员,否,999,7053738,樱桃,电视剧,...,2003,2003.0,107.0,14107525,70830237,608472,NaN,m14107525,演员,"沈春阳, 宋小宝, 小沈阳, 赵本山"
283255,1425269,郭莹莹,女,2053668,演员,否,999,2053668,寄生人,电影,...,1965,1965.0,103.0,4107385,2850587,608476,NaN,m4107385,演员,"张家辉, 黄秋生, 范冰冰, 陈红, 李芯逸"

## main

In [ ]:
def works_data_process(df_raw):
    df_movie = df_raw.loc[(df_raw['k_region'] != '其他合拍')].copy()
    # k_cast_id转为str
    df_movie['k_cast_id'] = df_movie['k_cast_id'].apply(lambda x: str(x))
    # 仅保留演员，导演，编剧数据
    df_movie = df_movie[df_movie['k_role'].isin(['演员', '导演', '编剧'])]
    df_movie = df_movie.reset_index(drop=True).copy(deep=True)
    # 添加新的movie_id_m列
    df_movie['movie_id_m'] = df_movie['k_movie_id'].apply(
        lambda x: 'm' + str(x))
    # 合并影人职责
    df_cast = df_movie[['k_cast_id', 'cast_name', 'k_role']].drop_duplicates()
    df_cast_agg = df_cast.groupby([
        'k_cast_id', 'cast_name'
    ])['k_role'].apply(lambda x: '/'.join(sorted(x.unique()))).reset_index()
    df_movie['cast_role_agg'] = df_movie['k_cast_id'].map(
        df_cast_agg.set_index('k_cast_id')['k_role'])
    # 每部电影的主要演员，is_main_cast==‘是’， k_role==‘演员’, index小于=5
    # 为每行添加一个main_cast列，按k_movie_id分组，按is_main_cast==‘是’，k_role=='演员'降序，index升序排序后，取前5个演员的cast_name连接起来
    # 1. 筛选并排序：只保留“是演员”且“是主演”的行，按 index 升序
    cast_sorted = df_movie[(df_movie['is_main_cast'] == '是')
                           & (df_movie['k_role'] == '演员')].sort_values(
                               by=['k_movie_id', 'index'],
                               ascending=[True, True])

    # 2. 分组聚合：取每个电影前5名，用逗号连接
    main_cast_series = cast_sorted.groupby('k_movie_id')['cast_name'].apply(
        lambda x: ', '.join(x.head(5)))

    # 3. 映射回原表：使用 map 匹配 k_movie_id，确保索引正确
    df_movie['main_cast'] = df_movie['k_movie_id'].map(main_cast_series)

    # 将int64类型的列转换为普通int类型
    # int64_cols = df_movie.select_dtypes(include=['int64']).columns
    # for col in int64_cols:
    #     df_movie[col] = df_movie[col].astype(int)
    return df_movie

## 保存为csv

In [18]:
file_name = "zwyg"
df_raw = pd.read_csv(f"../data/{file_name}.csv")
df_movie = works_data_process(df_raw)
df_movie_rated = df_movie[df_movie['is_rating'] == '有评分'].copy()
df_movie_rated = df_movie_rated.reset_index(drop=True).copy(deep=True)
df_movie.to_csv(f"../data/{file_name}_processed.csv", index=False)
df_movie_rated.to_csv(f"../data/{file_name}_rated_processed.csv", index=False)

# 数据统计

## 年度数据

In [ ]:
# 按年统计每年的电影数量
df_count_by_year = df_movie_rated.groupby('k_movie_year')['movie_id_m'].nunique().reset_index()
df_count_by_year.columns = ['year', 'movie_count']
df_count_by_year = df_count_by_year.sort_values('year')
df_count_by_year

In [ ]:
# 绘图
plt.figure(figsize=(10, 6))
plt.plot(df_count_by_year['year'], df_count_by_year['movie_count'], marker='o')
plt.title('年度电影数量统计')
plt.xlabel('年份')
plt.ylabel('电影数量')
plt.xticks(df_count_by_year['year'], rotation=45)
# plt.tight_layout()
plt.show()