# 歌词采集-QQ音乐
不需要按专辑采集

In [ ]:
import json
import pandas as pd

In [2]:
import sys

sys.path.append('..')

from data_crawler import  get_songs_data_raw, get_all_songs_lyric, clear_and_save_lyric
from songs_libs import format_timestamp, SongDataCleaner

# main

In [3]:
# file_path_prefix = "data/liuyuning/"
# singger = "刘宇宁"
# max_page = 14

# file_path_prefix = "data/liyuchun/"
# singer = "李宇春"
# max_page = 14

file_path_prefix = "data/wubai/"
singer = "伍佰"
max_page = 10

### 曲目采集

In [ ]:
# 原始曲目数据采集
song_data_raw = get_songs_data_raw(singger=singer, max_page=max_page)

In [ ]:
df_song_data_raw = pd.DataFrame(song_data_raw)
# 原始曲目保存
df_song_data_raw.to_csv(file_path_prefix + 'raw_song_data.csv', index=False)

In [4]:
# 重新读取数据
df_song_data_raw_read = pd.read_csv(file_path_prefix + 'raw_song_data.csv')
song_data_raw_read = df_song_data_raw_read.to_dict(orient='records')

In [5]:
df_song_data_raw_read

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time
0,4830318,002bChfZ1sw9ed,挪威的森林,NaN,伍佰,75,0036ERbx4IUm9V,滚石香港黄金十年 伍佰精选,96431,003QVFLh125yW3,392,1036080000
1,3337,002iuMFp4IQ8bN,泪桥,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,225,1070208000
2,393961,002YWMiQ2rB62Q,突然的自我 (Live),《散打》电影主题曲|《路边野餐》电影插曲,伍佰 & China Blue,5943,004OTPJW1frR0y,忘情1015精选辑,31798,004JF1BR18UKuH,215,1180627200
3,4928818,002eB80M3JAI55,Last Dance,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱情的尽头,95878,003S4zP93vJRib,271,833558400
4,3343,002zmbfl20fPlG,再度重相逢,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,209,1070208000
...,...,...,...,...,...,...,...,...,...,...,...,...
495,4717921,001QIEyr1lsciQ,太空弹 (Live),NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,生命的现场 Life Live,303582,004VBxyv36Wbc7,91,1325347200
496,458005984,001R285g4SF496,谁是老大,电影「奇门遁甲」主题曲,伍佰;大鹏;李治廷,75,0036ERbx4IUm9V,Mandopop Essential (Explicit),44914978,000npErO4DZX3r,344,1702656000
497,3583996,002noCPa39uGtf,上帝救救我 (Live),NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,生命的现场 Life Live,303582,004VBxyv36Wbc7,229,1325347200
498,200214325,001TKgQI3WOmh1,种子,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,钉子花,1791253,003cMUxV0DmHrg,317,1482854400
499,323678186,003ViXRJ15ofWE,浪人情歌 (2010快乐天堂・滚石30演唱会),NaN,"刘若英,伍佰","51,75","003jJGvv3C82KZ,0036ERbx4IUm9V",NaN,0,NaN,245,1290787200

In [ ]:
df_song_data_raw_read[df_song_data_raw_read['song_name'].str.contains('-')]

### 清洗

In [6]:
albums_to_delete = ['声生不息', '我歌', '中国梦', '谁是大歌神', '梦想的声音', '我是歌手', 'JJ的咖啡调调', '不凡的改变', '“17聚幸福”江苏卫视2017跨年演唱会', '江苏卫视', '湖南卫视', '浙江卫视', '启航2020', '2018中国蓝']

In [7]:
# 删除live歌曲
df_songs = SongDataCleaner.clear_live_songs(df_song_data_raw_read)
# 歌曲名清洗
df_songs = SongDataCleaner.clear_song_name(df_songs)
# 仅含歌手独唱歌曲
# df_songs = SongDataCleaner.clear_song_singer(df_songs, singer)
# 删除晚会歌曲
df_songs = SongDataCleaner.clear_song_tv_show(df_songs, albums_to_delete)
df_songs = df_songs.drop_duplicates(subset=['song_name_pure'], keep='first').reset_index(drop=True)
df_songs

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,song_name_unique,song_name_pure,album_name_pure
0,4830318,002bChfZ1sw9ed,挪威的森林,NaN,伍佰,75,0036ERbx4IUm9V,滚石香港黄金十年 伍佰精选,96431,003QVFLh125yW3,392,1036080000,挪威的森林,挪威的森林,滚石香港黄金十年 伍佰精选
1,3337,002iuMFp4IQ8bN,泪桥,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,225,1070208000,泪桥,泪桥,泪桥
2,4928818,002eB80M3JAI55,Last Dance,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱情的尽头,95878,003S4zP93vJRib,271,833558400,LastDance,lastdance,爱情的尽头
3,3343,002zmbfl20fPlG,再度重相逢,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,209,1070208000,再度重相逢,再度重相逢,泪桥
4,1498651,002HUkVn3dHcDe,梦醒时分,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,单程车票,81074,000g4Nnj3eOjer,226,1293811200,梦醒时分,梦醒时分,单程车票
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,106643844,002Xdm1K1wMPPw,海上的岛,NaN,"伍佰 & China Blue,范晓萱","5943,232","004OTPJW1frR0y,000CLIfb03b9k7",双面人,8517,0019IY7I2VPL00,388,1105027200,海上的岛,海上的岛,双面人
213,5580813,000gfD9R2N5IMp,太极,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,无尽闪亮的哀愁,521626,000eEVDh2o71Hp,249,1356969600,太极,太极,无尽闪亮的哀愁
214,4932418,000TQHvJ0kWoRH,秋风夜雨,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱你伍佰年,96367,000G9PkV0InFMu,259,1085587200,秋风夜雨,秋风夜雨,爱你伍佰年
215,4955988,001YQ4qY00fHEZ,停止的危险,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,单程车票,81074,000g4Nnj3eOjer,246,1293811200,停止的危险,停止的危险,单程车票
216,200214325,001TKgQI3WOmh1,种子,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,钉子花,1791253,003cMUxV0DmHrg,317,1482854400,种子,种子,钉子花

In [8]:
# 特别处理
df_songs = df_songs[~df_songs['song_name_pure'].str.contains('#MaydayBlue20th')]
df_songs

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,song_name_unique,song_name_pure,album_name_pure
0,4830318,002bChfZ1sw9ed,挪威的森林,NaN,伍佰,75,0036ERbx4IUm9V,滚石香港黄金十年 伍佰精选,96431,003QVFLh125yW3,392,1036080000,挪威的森林,挪威的森林,滚石香港黄金十年 伍佰精选
1,3337,002iuMFp4IQ8bN,泪桥,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,225,1070208000,泪桥,泪桥,泪桥
2,4928818,002eB80M3JAI55,Last Dance,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱情的尽头,95878,003S4zP93vJRib,271,833558400,LastDance,lastdance,爱情的尽头
3,3343,002zmbfl20fPlG,再度重相逢,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,209,1070208000,再度重相逢,再度重相逢,泪桥
4,1498651,002HUkVn3dHcDe,梦醒时分,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,单程车票,81074,000g4Nnj3eOjer,226,1293811200,梦醒时分,梦醒时分,单程车票
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,106643844,002Xdm1K1wMPPw,海上的岛,NaN,"伍佰 & China Blue,范晓萱","5943,232","004OTPJW1frR0y,000CLIfb03b9k7",双面人,8517,0019IY7I2VPL00,388,1105027200,海上的岛,海上的岛,双面人
213,5580813,000gfD9R2N5IMp,太极,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,无尽闪亮的哀愁,521626,000eEVDh2o71Hp,249,1356969600,太极,太极,无尽闪亮的哀愁
214,4932418,000TQHvJ0kWoRH,秋风夜雨,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱你伍佰年,96367,000G9PkV0InFMu,259,1085587200,秋风夜雨,秋风夜雨,爱你伍佰年
215,4955988,001YQ4qY00fHEZ,停止的危险,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,单程车票,81074,000g4Nnj3eOjer,246,1293811200,停止的危险,停止的危险,单程车票
216,200214325,001TKgQI3WOmh1,种子,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,钉子花,1791253,003cMUxV0DmHrg,317,1482854400,种子,种子,钉子花

In [16]:
# 前130首
songs_list_all = df_songs['song_name_pure'].to_list()
songs_list_130 = df_songs.head(130)['song_name_pure'].to_list()

## 歌单确认

In [20]:
# 李宇春
songs_to_add = [
    '皇后与梦想', '下雨', '冰菊物语', '我的王国', '漂浮地铁', '今天有朵云爱我', '您所拨打的电话号码是空号',
    '一而再再而三地喜欢你', '人间乐园', 'TMD我爱你', '口音', '木兰', '开放'
]
songs_to_delete = ['今夜你会不会来', '春风十里', '情书', '那女孩对我说', '南方姑娘', '爱你所爱', '无心睡眠', '莫过于此', '天黑黑', '张三的歌', '漂洋过海来看你', '城里的月光', '不要对他说', '下个,路口,见']
# 陈奕迅
songs_to_delete = ['新曲+精选', 'K歌之王AIR', '慢慢喜欢你', '最冷一天']
# 任贤齐
songs_to_delete = ['伤心太平洋+心太软+我是一只鱼+对面的女孩看过来', '桥边姑娘', '你知道我在等你吗', '我是一只小小鸟', '外婆的澎湖湾2015', '海阔天空', '爱的路上只有你和我', '爱的初体验', '美丽的坏女人']
# 林俊杰
# songs_to_delete = ['开场白', '无聊', '起风了']
# 陈信宏
# songs_to_delete = ['玫瑰少年-FromTHEFIRSTTAKE', '疯狂世界+候鸟', '2010离开地球表面', '盛夏光年×HIPHOPMAN', 'Paradise+倔强', 'Hosee', 'SHERO']
# 蔡依林
# songs_to_delete = ['看我七十二变', '爱情36计']
# 伍佰
songs_to_delete = ['少年吔,安啦！']

songs_list_final = songs_list_130.copy()

In [ ]:
# 添加
for i in songs_to_add:
    if i not in songs_list_final:
        print(i)
        songs_list_final.append(i)

In [21]:
# 删除
for i in songs_to_delete:
    if i in songs_list_final:
        print(i)
        songs_list_final.remove(i)

少年吔,安啦！

In [22]:
len(songs_list_final)

129

## 歌曲数据确认

In [23]:
df_songs_final = df_songs[df_songs['song_name_pure'].isin(
    songs_list_final)].reset_index(drop=True)

# df_songs_final = df_songs_final.drop(columns=['song_name_unique'])
# df_songs_final['song_name_unique'] = df_songs_final['song_name_pure']
df_songs_final['publish_date'] = df_songs_final['publish_time'].apply(
    lambda x: format_timestamp(x))
df_songs_final = df_songs_final[df_songs_final['publish_date'].str.contains('-')]
df_songs_final['publish_year'] = df_songs_final['publish_date'].apply(
    lambda x: x.split('-')[0])
df_songs_final

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,song_name_unique,song_name_pure,album_name_pure,publish_date,publish_year
0,4830318,002bChfZ1sw9ed,挪威的森林,NaN,伍佰,75,0036ERbx4IUm9V,滚石香港黄金十年 伍佰精选,96431,003QVFLh125yW3,392,1036080000,挪威的森林,挪威的森林,滚石香港黄金十年 伍佰精选,2002-11-01,2002
1,3337,002iuMFp4IQ8bN,泪桥,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,225,1070208000,泪桥,泪桥,泪桥,2003-12-01,2003
2,4928818,002eB80M3JAI55,Last Dance,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱情的尽头,95878,003S4zP93vJRib,271,833558400,LastDance,lastdance,爱情的尽头,1996-06-01,1996
3,3343,002zmbfl20fPlG,再度重相逢,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,209,1070208000,再度重相逢,再度重相逢,泪桥,2003-12-01,2003
4,1498651,002HUkVn3dHcDe,梦醒时分,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,单程车票,81074,000g4Nnj3eOjer,226,1293811200,梦醒时分,梦醒时分,单程车票,2011-01-01,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,3336,004CLqwk2jGMfL,街角的蔷薇,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,399,1070208000,街角的蔷薇,街角的蔷薇,泪桥,2003-12-01,2003
125,3335,004Zrdh32dx6DO,活下去,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,泪桥,310,000tXk9a4Jnf2G,213,1070208000,活下去,活下去,泪桥,2003-12-01,2003
126,393953,002GlfmL4cFmOT,忘情歌,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,忘情1015精选辑,31798,004JF1BR18UKuH,306,1180627200,忘情歌,忘情歌,忘情1015精选辑,2007-06-01,2007
127,4928896,004Ps9XB2NuJ2O,返去故乡,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,树枝孤鸟,95885,0041Z8ZE2d3QcM,347,886262400,返去故乡,返去故乡,树枝孤鸟,1998-02-01,1998
128,4928819,002amj5j02D3Gg,青春,NaN,伍佰 & China Blue,5943,004OTPJW1frR0y,爱情的尽头,95878,003S4zP93vJRib,210,833558400,青春,青春,爱情的尽头,1996-06-01,1996

In [24]:
df_songs_final.to_csv(file_path_prefix + 'cleared_song_data.csv', index=False)

## 歌词采集

In [13]:
get_all_songs_lyric(file_path_prefix+'raw_lyric_data.json', df_songs_final)

挪威的森林
泪桥
Last Dance
再度重相逢
梦醒时分
晚风
与你到永久
浪人情歌
我会好好的
爱你一万年
白鸽
你是我的花朵
夏夜晚风
风平浪静
如果这都不算爱
夜照亮了夜
青春与爱情
坚强的理由
Cherry Lover
枫叶
不确定
牵挂
妳是我的完美
随风而去
戒指
心爱的再会啦
彩虹
让水倒流
美丽新世界
一生最爱的人
暴雨
世界第一等
往事欲如何
然后你怎么说
春花秋月
不过是爱上你
黑色蒙太奇
爱情的尽头
梦的河流
钢铁男子
翅膀
单程车票
爱情限时批
一点点
接受我的爱
赴汤蹈火
爱你越来越多
深秋的祝褔
背叛
树枝孤鸟
白鹭鸶
亏欠
我们注定在一起
不曾在乎我
亲爱的你
我的名字
我想飞
少年吔，安啦！
纯白的起点
冰雨
最美的时刻
最后是温柔
爱上别人是快乐的事
纯真年代
雨一直下
无尽闪亮的哀愁
可爱的马
一个人
谁是老大
火山
你爱我
唯我独大
热泪暗班车
关于女人
抛弃
破碎的收音机
重生
煞到你
不要想太多
答案
飞在风中的小雨
爱妳一万年
一种女人
素兰小姐要出嫁
冲冲冲
傻情人
两个寂寞
蹦孔
蓝月
冬至
不满
上帝救救我
少年，安啦！
思念亲像一条河
没人爱的女孩
墓仔埔也敢去
结
钱的力量
放浪舞者
人生一场梦
钉子花
只要为你活一天
海浪
199玫瑰
我心内
上瘾了
Kiss Me
东石
晴天雨天
势
都是我的错
爱妳无目地
真世界
上海女孩
再来一杯
何时再见梦中人
终于
风火
小妹
烧火
风台心情
断肠诗
一亲红颜
一千万个理由
楼仔厝
街角的蔷薇
活下去
忘情歌
返去故乡
青春

## 歌词清洗

In [14]:
clear_and_save_lyric(file_path_prefix, df_songs_final)

In [15]:
# 歌词数据查验
df_lyric = pd.read_json(f"{file_path_prefix}cleared_lyric_data.json")
df_lyric['lyric_length'] = df_lyric['lyrics_text'].apply(lambda x: len(x))
df_lyric.sort_values(by='lyric_length')

,song_id,song_name,start_time,has_lyric,lyricist,composer,arranger,lyrics_text,lyric_length
109,204261615,势,NaT,0,,,,,0
89,208992906,冬至,2026-02-28 00:48:23,1,林夕,伍佰,,指尖以东，在你夹克深处游动。能抱拥便抱拥，下次用好友身份过冬。街灯以东，白雪吻湿双眼瞳孔。能...,83
114,1124679,再来一杯,2026-02-28 00:25:42,1,,,,吊在空中好多的酒杯。你的脸蛋红的像草莓。今夜大家不醉就不归。明朝太阳是我的棉被。再来一杯。吊...,90
111,204261614,爱妳无目地,2026-02-28 00:34:37,1,伍佰,伍佰,,天悬悬云咧飞。规条路媠芳花。天悬悬云咧飞。规条路媠芳花。只爱你一个哎呀。哎呀。哎呀。哎呀。只...,134
121,4928894,断肠诗,2026-02-28 00:17:40,1,伍佰,伍佰,,春夏交接的当时。蝉声哀啼响上天。蝴蝶折翅落大水。路边有断头的蜻蜓。下埔雷雨落满。日头犹原光晴...,156
...,...,...,...,...,...,...,...,...,...
69,3553002,火山,2026-02-28 00:16:42,1,伍佰,伍佰,,身上的拉链通通拉了起来，让你紧张让你紧张。黑夜里墨镜我要戴了起来，非常嚣张非常嚣张。心里的岩...,552
18,179511,Cherry Lover,2026-02-28 00:41:30,1,伍佰,伍佰,,我对你动了情移了心。不经意的话都说不停。彼此间的空气没有动静。我在等你给我答应。你圆润的嘴角...,563
101,1523367,只要为你活一天,2026-02-28 00:01:52,1,陈世杰,伍佰,,只要为你活一天。接近你是我唯一的愿望。只要为你活一天。我的生命才有价值和希望。敢有听到我的心...,565
19,4932444,枫叶,2026-02-28 00:16:21,1,伍佰/China blue,伍佰,Unknow,当秋天洒下最后一把枫叶时。正是我要离开的时候。看着收拾好的行李。想起远方的你。心里竟然有一股...,600
124,267550411,楼仔厝,2026-02-28 00:04:33,1,伍佰,伍佰,,坐着土脚底的铁路来到这。看隔壁阿财说的敢拢有影。看敢是世界上很有名。看敢是人人出门都驶轿车。...,847

In [ ]:
# 删除有问题的
song_ids_to_delete = [204261615, 434983, 235571, 764258]
df_lyric = df_lyric[~df_lyric['song_id'].isin(song_ids_to_delete)]
df_lyric

In [ ]:
# 覆盖原文件
df_lyric['start_time'] = df_lyric['start_time'].astype(str).apply(lambda x: x.split(' ')[1])
df_lyric_d = df_lyric.to_dict(orient='records')
with open(file_path_prefix + 'cleared_lyric_data.json', 'w',
              encoding='utf-8') as f:
        json.dump(df_lyric_d, f, ensure_ascii=False, indent=4)

## 特别处理

In [ ]:
df_lyric['lyricist'].unique()

In [ ]:
lyricist = ['阿信', '五月天阿信', '五月天 阿信', '阿信(五月天)']
df_lyric_flited = df_lyric[df_lyric['lyricist'].isin(lyricist)]
df_lyric_flited

In [ ]:
songs_to_delete_lyric = ['派对动物 + 离开地球表面 (live in the sky)', '伤心的人就听撑腰 (Life Live)', '明白 (后段) (Live)']
df_lyric_flited = df_lyric_flited[~df_lyric_flited['song_name'].isin(songs_to_delete_lyric)]
df_lyric_flited

In [ ]:
# 将df_lyric_flited保存为json
df_lyric_flited = df_lyric_flited.copy()
df_lyric_flited['start_time'] = df_lyric_flited['start_time'].astype(str).apply(lambda x: x.split(' ')[1])
df_lyric_flited_d = df_lyric_flited.to_dict(orient='records')
with open(file_path_prefix + 'cleared_lyric_data.json', 'w',
              encoding='utf-8') as f:
        json.dump(df_lyric_flited_d, f, ensure_ascii=False, indent=4)