# 歌词采集-QQ音乐
ost歌曲

In [1]:
import json
import pandas as pd

In [2]:
import sys

sys.path.append('..')

from data_crawler import  get_songs_data_raw, get_all_songs_lyric, clear_and_save_lyric
from songs_libs import format_timestamp, SongDataCleaner

# main

In [30]:
file_path_prefix = "data/zhoushen_pure/"
singer = "周深"
max_page = 10

### 曲目采集

In [4]:
# 原始曲目数据采集
song_data_raw = get_songs_data_raw(singger=singer, max_page=max_page)

正在获取第1页数据...
正在获取第2页数据...
正在获取第3页数据...
正在获取第4页数据...
正在获取第5页数据...
正在获取第6页数据...
正在获取第7页数据...
正在获取第8页数据...
正在获取第9页数据...
正在获取第10页数据...

In [5]:
df_song_data_raw = pd.DataFrame(song_data_raw)
# 原始曲目保存
df_song_data_raw.to_csv(file_path_prefix + 'raw_song_data.csv', index=False)

In [31]:
# 重新读取数据
df_song_data_raw_read = pd.read_csv(file_path_prefix + 'raw_song_data.csv')
song_data_raw_read = df_song_data_raw_read.to_dict(orient='records')

In [32]:
df_song_data_raw_read

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time
0,642763880,004VCyBy391azx,吉量,NaN,周深,199509,003fA5G40k6hKc,吉量,85387994,0010e79v0CExQN,236,1771257601
1,214188340,000wXRGx2u2NJ8,云裳羽衣曲,《云裳羽衣》手游首发主题曲,周深,199509,003fA5G40k6hKc,云裳羽衣曲,4096700,001uf8A626x0yY,296,1530028800
2,468749280,002QvWwX1BG9mr,小美满,《热辣滚烫》电影热辣陪伴曲,周深,199509,003fA5G40k6hKc,小美满,46467243,0002ATV00WcBgd,214,1707184800
3,106484214,004OQ5Mt0EmEzv,大鱼,《大鱼海棠》动画电影印象曲,周深,199509,003fA5G40k6hKc,大鱼,1387962,004Y7V4s3ug4cC,313,1463673600
4,643260797,003FYnmA2KmMXg,接财运,NaN,周深,199509,003fA5G40k6hKc,接财运,85582400,003Iw29j2lAefm,168,1771603200
...,...,...,...,...,...,...,...,...,...,...,...,...
495,248913982,001aEMHZ4EbOCO,永远同在 + 能解答一切的答案 (Live),NaN,周深,199509,003fA5G40k6hKc,bilibili晚会 二零一九最美的夜,9889041,000FXC0p3Y5eVW,488,1577721600
496,314402025,000kj4lV0HPCMz,大艺术家 (Live),NaN,周深,199509,003fA5G40k6hKc,快手616真心夜,20351106,0011JOFK0fbgKK,178,1623758400
497,312921648,002eWHdp0BLQaC,后来 (深龄其境演唱会live版),NaN,周深,199509,003fA5G40k6hKc,深龄其境演唱会live版,20103881,003TqDte1mJyGa,134,1614528000
498,325386493,000uslWZ0lckpk,大鱼 (3D环绕版),NaN,周深,199509,003fA5G40k6hKc,NaN,0,NaN,313,1463673600
499,247367296,004R1AJj0OeSQi,我爱他 (Live),NaN,"许魏洲,周深","1113420,199509","002ykHF42AYnsl,003fA5G40k6hKc",中国梦之声·我们的歌 第7期,9627468,0046cTap2Jv1up,215,1576414800

## 影视曲目识别

In [33]:
# song_subname含 《 的歌曲
df_songs_ost = df_song_data_raw_read[
    df_song_data_raw_read['song_subname'].fillna('无').str.contains('《')]

In [34]:
# 提取song_sub_name中《》内的内容作为 ost_name
df_songs_ost = df_songs_ost.copy()
df_songs_ost['ost_name'] = df_songs_ost['song_subname'].str.extract('《(.*?)》')
df_songs_ost

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,ost_name
1,214188340,000wXRGx2u2NJ8,云裳羽衣曲,《云裳羽衣》手游首发主题曲,周深,199509,003fA5G40k6hKc,云裳羽衣曲,4096700,001uf8A626x0yY,296,1530028800,云裳羽衣
2,468749280,002QvWwX1BG9mr,小美满,《热辣滚烫》电影热辣陪伴曲,周深,199509,003fA5G40k6hKc,小美满,46467243,0002ATV00WcBgd,214,1707184800,热辣滚烫
3,106484214,004OQ5Mt0EmEzv,大鱼,《大鱼海棠》动画电影印象曲,周深,199509,003fA5G40k6hKc,大鱼,1387962,004Y7V4s3ug4cC,313,1463673600,大鱼海棠
5,639981206,002LbZMr3NfNPI,选择,《惊蛰无声》电影主题曲,周深,199509,003fA5G40k6hKc,惊蛰无声 影视原声带,84974077,002jh3xv1whZS8,203,1771293600,惊蛰无声
6,297971384,002Id4Xd0F98go,若梦,《与君歌》电视剧主题曲,周深,199509,003fA5G40k6hKc,若梦,17590611,0025JWkx1h0vuU,244,1613268000,与君歌
...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,282719618,003UdafN3YLZnV,幸福里,《幸福里的故事》电视剧片尾曲,周深,199509,003fA5G40k6hKc,幸福里的故事 电视原声带,15346737,003Tezvc0ZHfM1,293,1604073600,幸福里的故事
480,215728440,003ncdTb2TmlSP,念,《剑网3·曲云传》舞台剧宣传曲,周深,199509,003fA5G40k6hKc,剑网3·曲云传 舞台剧音乐原声带,4839001,0046wfdW2UIKpi,275,1540051200,剑网3·曲云传
481,201946192,004L8t3224jyXs,黎明的翅膀,《阿拉德：宿命之门》动画片尾曲,周深,199509,003fA5G40k6hKc,阿拉德：宿命之门 DNF动画原声带,2016647,0003ccN51jwtqv,251,1492704000,阿拉德：宿命之门
490,356206575,000wy0xA0vexc3,传家,《传家》电视剧主题曲,周深,199509,003fA5G40k6hKc,传家 电视剧原声带,27786258,001aiNwE3C8RUh,260,1652925600,传家
494,274349881,003g6ndd2koyH4,幽灵公主 (Live),《青春环游记》第二季原声音乐,"周深,郎朗","199509,8524","003fA5G40k6hKc,001A2KKg0I4LmF",青春环游记第二季 原声碟,13081862,000Rx5WC0DulKX,229,1596902400,青春环游记

### 清洗

In [ ]:
albums_to_delete = ['声生不息', '我歌', '中国梦', '谁是大歌神', '梦想的声音', '我是歌手', 'JJ的咖啡调调', '不凡的改变', '“17聚幸福”江苏卫视2017跨年演唱会', '江苏卫视', '湖南卫视', '浙江卫视', '启航2020', '2018中国蓝']

In [38]:
# 删除live歌曲
df_songs = SongDataCleaner.clear_live_songs(df_songs_ost)
# 歌曲名清洗
df_songs = SongDataCleaner.clear_song_name(df_songs)
# 仅含歌手独唱歌曲
df_songs = SongDataCleaner.clear_song_singer(df_songs, singer)
# 删除晚会歌曲
# df_songs = SongDataCleaner.clear_song_tv_show(df_songs, albums_to_delete)
df_songs = df_songs.drop_duplicates(subset=['song_name_pure'], keep='first').reset_index(drop=True)
df_songs

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,ost_name,song_name_unique,song_name_pure
0,214188340,000wXRGx2u2NJ8,云裳羽衣曲,《云裳羽衣》手游首发主题曲,周深,199509,003fA5G40k6hKc,云裳羽衣曲,4096700,001uf8A626x0yY,296,1530028800,云裳羽衣,云裳羽衣曲,云裳羽衣曲
1,468749280,002QvWwX1BG9mr,小美满,《热辣滚烫》电影热辣陪伴曲,周深,199509,003fA5G40k6hKc,小美满,46467243,0002ATV00WcBgd,214,1707184800,热辣滚烫,小美满,小美满
2,106484214,004OQ5Mt0EmEzv,大鱼,《大鱼海棠》动画电影印象曲,周深,199509,003fA5G40k6hKc,大鱼,1387962,004Y7V4s3ug4cC,313,1463673600,大鱼海棠,大鱼,大鱼
3,639981206,002LbZMr3NfNPI,选择,《惊蛰无声》电影主题曲,周深,199509,003fA5G40k6hKc,惊蛰无声 影视原声带,84974077,002jh3xv1whZS8,203,1771293600,惊蛰无声,选择,选择
4,297971384,002Id4Xd0F98go,若梦,《与君歌》电视剧主题曲,周深,199509,003fA5G40k6hKc,若梦,17590611,0025JWkx1h0vuU,244,1613268000,与君歌,若梦,若梦
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,412264218,002JWfm42wvrqv,似夏,《岁岁青莲》影视剧主题曲,周深,199509,003fA5G40k6hKc,岁岁青莲 影视剧原声带,43624703,004NWrmR2hiMKj,277,1698804000,岁岁青莲,似夏,似夏
156,282719618,003UdafN3YLZnV,幸福里,《幸福里的故事》电视剧片尾曲,周深,199509,003fA5G40k6hKc,幸福里的故事 电视原声带,15346737,003Tezvc0ZHfM1,293,1604073600,幸福里的故事,幸福里,幸福里
157,215728440,003ncdTb2TmlSP,念,《剑网3·曲云传》舞台剧宣传曲,周深,199509,003fA5G40k6hKc,剑网3·曲云传 舞台剧音乐原声带,4839001,0046wfdW2UIKpi,275,1540051200,剑网3·曲云传,念,念
158,201946192,004L8t3224jyXs,黎明的翅膀,《阿拉德：宿命之门》动画片尾曲,周深,199509,003fA5G40k6hKc,阿拉德：宿命之门 DNF动画原声带,2016647,0003ccN51jwtqv,251,1492704000,阿拉德：宿命之门,黎明的翅膀,黎明的翅膀
159,356206575,000wy0xA0vexc3,传家,《传家》电视剧主题曲,周深,199509,003fA5G40k6hKc,传家 电视剧原声带,27786258,001aiNwE3C8RUh,260,1652925600,传家,传家,传家

In [39]:
# 前130首
songs_list_all = df_songs['song_name_pure'].to_list()
songs_list_130 = df_songs.head(130)['song_name_pure'].to_list()

## 歌单确认

In [40]:
# 李宇春
songs_to_add = [
    '皇后与梦想', '下雨', '冰菊物语', '我的王国', '漂浮地铁', '今天有朵云爱我', '您所拨打的电话号码是空号',
    '一而再再而三地喜欢你', '人间乐园', 'TMD我爱你', '口音', '木兰', '开放'
]
songs_to_delete = ['今夜你会不会来', '春风十里', '情书', '那女孩对我说', '南方姑娘', '爱你所爱', '无心睡眠', '莫过于此', '天黑黑', '张三的歌', '漂洋过海来看你', '城里的月光', '不要对他说', '下个,路口,见']
# 陈奕迅
songs_to_delete = ['新曲+精选', 'K歌之王AIR', '慢慢喜欢你', '最冷一天']
# 任贤齐
songs_to_delete = ['伤心太平洋+心太软+我是一只鱼+对面的女孩看过来', '桥边姑娘', '你知道我在等你吗', '我是一只小小鸟', '外婆的澎湖湾2015', '海阔天空', '爱的路上只有你和我', '爱的初体验', '美丽的坏女人']
# 林俊杰
# songs_to_delete = ['开场白', '无聊', '起风了']
# 陈信宏
# songs_to_delete = ['玫瑰少年-FromTHEFIRSTTAKE', '疯狂世界+候鸟', '2010离开地球表面', '盛夏光年×HIPHOPMAN', 'Paradise+倔强', 'Hosee', 'SHERO']
# 蔡依林
# songs_to_delete = ['看我七十二变', '爱情36计']
# 伍佰
songs_to_delete = ['少年吔,安啦！']

songs_list_final = songs_list_130.copy()

In [ ]:
# 添加
for i in songs_to_add:
    if i not in songs_list_final:
        print(i)
        songs_list_final.append(i)

In [ ]:
# 删除
for i in songs_to_delete:
    if i in songs_list_final:
        print(i)
        songs_list_final.remove(i)

In [20]:
len(songs_list_final)

130

## 歌曲数据确认

In [41]:
df_songs_final = df_songs[df_songs['song_name_pure'].isin(
    songs_list_final)].reset_index(drop=True)

# df_songs_final = df_songs_final.drop(columns=['song_name_unique'])
# df_songs_final['song_name_unique'] = df_songs_final['song_name_pure']
df_songs_final['publish_date'] = df_songs_final['publish_time'].apply(
    lambda x: format_timestamp(x))
df_songs_final = df_songs_final[df_songs_final['publish_date'].str.contains('-')]
df_songs_final['publish_year'] = df_songs_final['publish_date'].apply(
    lambda x: x.split('-')[0])

In [26]:
df_songs_final['song_name_unique'] = df_songs_final[
    'song_name_unique'] + "-" + df_songs_final['ost_name']
df_songs_final

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,ost_name,song_name_unique,song_name_pure,publish_date,publish_year
0,214188340,000wXRGx2u2NJ8,云裳羽衣曲,《云裳羽衣》手游首发主题曲,周深,199509,003fA5G40k6hKc,云裳羽衣曲,4096700,001uf8A626x0yY,296,1530028800,云裳羽衣,云裳羽衣曲-云裳羽衣,云裳羽衣曲,2018-06-27,2018
1,468749280,002QvWwX1BG9mr,小美满,《热辣滚烫》电影热辣陪伴曲,周深,199509,003fA5G40k6hKc,小美满,46467243,0002ATV00WcBgd,214,1707184800,热辣滚烫,小美满-热辣滚烫,小美满,2024-02-06,2024
2,106484214,004OQ5Mt0EmEzv,大鱼,《大鱼海棠》动画电影印象曲,周深,199509,003fA5G40k6hKc,大鱼,1387962,004Y7V4s3ug4cC,313,1463673600,大鱼海棠,大鱼-大鱼海棠,大鱼,2016-05-20,2016
3,639981206,002LbZMr3NfNPI,选择,《惊蛰无声》电影主题曲,周深,199509,003fA5G40k6hKc,惊蛰无声 影视原声带,84974077,002jh3xv1whZS8,203,1771293600,惊蛰无声,选择-惊蛰无声,选择,2026-02-17,2026
4,297971384,002Id4Xd0F98go,若梦,《与君歌》电视剧主题曲,周深,199509,003fA5G40k6hKc,若梦,17590611,0025JWkx1h0vuU,244,1613268000,与君歌,若梦-与君歌,若梦,2021-02-14,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,360994402,000WYGmR2DxPPg,万里挑一,《关于唐医生的一切》电视剧主题曲,周深,199509,003fA5G40k6hKc,关于唐医生的一切 电视原声带,28839736,001Zftkf4Yh2W2,222,1656172800,关于唐医生的一切,万里挑一-关于唐医生的一切,万里挑一,2022-06-26,2022
126,451400575,0016s8pN4cpBxw,I'm A Star,《星愿》电影许愿星之歌,周深,199509,003fA5G40k6hKc,I'm A Star,44068462,0007r8Wy0nIyAV,187,1700409600,星愿,I'mAStar-星愿,i'mastar,2023-11-20,2023
127,356161397,002cue0j1dvmxt,I See Us,《欢迎光临》电视剧主题曲,周深,199509,003fA5G40k6hKc,欢迎光临 电视剧原声带,28134589,003EADJV2YYcIe,256,1652839200,欢迎光临,ISeeUs-欢迎光临,iseeus,2022-05-18,2022
128,257720758,000Ji8co0G4eU3,启示,《地下城与勇士·逆转之轮》推广曲,周深,199509,003fA5G40k6hKc,DNF官方动画第二季推广曲,11296569,004A5e9i2qtWrZ,280,1586707200,地下城与勇士·逆转之轮,启示-地下城与勇士·逆转之轮,启示,2020-04-13,2020
129,353730842,0019oYqI1AgmOA,照耀星河,《良辰好景知几何》电视剧主题曲,周深,199509,003fA5G40k6hKc,良辰好景知几何 电视剧原声带,27466271,0023aWMA30ro5t,266,1652371200,良辰好景知几何,照耀星河-良辰好景知几何,照耀星河,2022-05-13,2022

In [42]:
df_songs_final.to_csv(file_path_prefix + 'cleared_song_data.csv', index=False)

## 歌词采集

In [23]:
get_all_songs_lyric(file_path_prefix+'raw_lyric_data.json', df_songs_final)

云裳羽衣曲
小美满
大鱼
选择
若梦
璀璨冒险人
万里
光亮
我的对
谜宫
借过一下
时间啊
和光同尘
Crush
遥遥
有我
人是_
梦见你
我以渺小爱你
心海里的光
等光来
消散人潮
触不可及
浮游
Rubia
冰凌花
铃芽之旅
芽
生活总该迎着光亮
浣花落
My Only
要一起
风吹过的晨曦
归来
随风
借梦
余情
若以尘埃
相拥不放
河
门
向光而行
焰火
愿
后来没有你
岁月尘埃
茧
光字片
独白
愿得一心人
不再流浪
来不及勇敢
悬崖之上
曼陀
海藏
玦恋
缘起
直破穹苍
旅途
与卿
雪花落下
画绢
问花
请笃信一个梦
行舟问柳
明月传说
【薛洋】 荒城渡
以无旁骛之吻
拙慕
明明
如你随行
一生一瞬
桂花谣
你的样子
追赶春天的人
相守
若仙
在意
许卿安
念归去
痕迹
曾经沧海
卡布叻船长
繁花依旧
水形物语
江湖觅知音
如果你爱我
时间之海
她说，老啦
迷途
人间星河
星鱼
归处
小舍得
说声你好
明暗之间
也很值得
鲛人之歌
心事
逐月
此生惟你
威凤吟
蜕
永恒孤独
最好的礼物
夏日友晴天
过客
彼岸花
非你所想
东游
浓情淡如你
一晌
她
战·永不言败
风起流年
天地为念
跳舞的月光
回到你身边
情意结
记得
Endless Sailing
请带着浪漫远航
繁星璀璨的天空
卿卿
不说话
万里挑一
I'm A Star
I See Us
启示
照耀星河

## 歌词清洗

In [24]:
clear_and_save_lyric(file_path_prefix, df_songs_final)

In [25]:
# 歌词数据查验
df_lyric = pd.read_json(f"{file_path_prefix}cleared_lyric_data.json")
df_lyric['lyric_length'] = df_lyric['lyrics_text'].apply(lambda x: len(x))
df_lyric.sort_values(by='lyric_length')

,song_id,song_name,start_time,has_lyric,lyricist,composer,arranger,lyrics_text,lyric_length
35,448839689,借梦,2026-03-02 00:16:22,1,龚淑均,衣睿,衣睿,用一段黑夜。一瞬烟火。借一半清醒梦给我。早知命运无对错。情深无因果。却不知那一天雪落，你来过...,155
125,360994402,万里挑一,2026-03-02 00:23:39,1,浅紫,浅紫,陈歆儒,万里那一颗星。撒手在夜空里。别躲在无人来访的狭小缝隙。我会守护着你。暴风眼上空的阳光。短暂的...,186
87,436399025,时间之海,2026-03-02 00:28:03,1,王以柚 Yiyo Wang,王以柚 Yiyo Wang,LUCAS,我们跌落在这个世界的第几个维度。沉溺在时间之海的迷途里辗转往复。日出，日落。现在，未来。光年...,186
43,247911752,愿,2026-03-02 00:27:43,1,田丁,崔博,谭伊哲,云随风翻涌。星流转心动。漫天姹紫嫣红。谁的愿，让人魂绕梦牵。在这一刻永恒搁浅。我听见，你的心...,196
92,294295801,归处,2026-03-02 00:21:35,1,尹约,钱雷,田汨/张羣 @SoundGrowthStudio,你是我全部视线的终点。山海间唯热爱无可遮掩。迎风踏雪沉星落月。向着背影如烟。何时能追寻回你身...,200
...,...,...,...,...,...,...,...,...,...
126,451400575,I'm A Star,2026-03-02 00:18:07,1,Julia Michaels,Benjamin Rice/Julia Michaels,陈牧荻,仰望天空你可曾。怀疑那里隐藏着秘密。时间凝聚为永恒。把你的过去打扮成记忆。是谁把海洋染成蓝。...,726
30,338704999,My Only,2026-03-02 00:14:33,1,王仕琳,金炫道,,You，are，the，only。The，only，one，who，heals，me。Whe...,753
120,392540369,Endless Sailing,2026-03-02 00:25:46,1,,,,I，don't，know，who，I，am，and，I，don't，know，where，I...,896
24,296021954,Rubia,2026-03-02 00:03:43,1,TetraCalyx,蔡近翰Zoe(HOYO-MiX),宫奇Gon(HOYO-MiX)/杨启翔Frex(HOYO-MiX),Life，blooms，like，a，flower。Far，away，or，by，the，r...,1119
127,356161397,I See Us,2026-03-02 00:16:18,1,杨禹萱,JIHU/李祎,JIHU,When，the，stars，start，to，shine。First，time，we，sa...,1179

In [ ]:
# 删除有问题的
song_ids_to_delete = [204261615, 434983, 235571, 764258]
df_lyric = df_lyric[~df_lyric['song_id'].isin(song_ids_to_delete)]
df_lyric

In [ ]:
# 覆盖原文件
df_lyric['start_time'] = df_lyric['start_time'].astype(str).apply(lambda x: x.split(' ')[1])
df_lyric_d = df_lyric.to_dict(orient='records')
with open(file_path_prefix + 'cleared_lyric_data.json', 'w',
              encoding='utf-8') as f:
        json.dump(df_lyric_d, f, ensure_ascii=False, indent=4)

## 特别处理

In [ ]:
df_lyric['lyricist'].unique()