# 歌词采集-QQ音乐
不需要按专辑采集

In [1]:
import json
import pandas as pd

import os

In [2]:
import sys

sys.path.append('..')

from data_crawler import  get_songs_data_raw, get_all_songs_lyric, clear_and_save_lyric
from songs_libs import format_timestamp, SongDataCleaner

In [3]:
albums_to_delete = ['声生不息', '我歌', '中国梦', '谁是大歌神', '梦想的声音', '我是歌手', 'JJ的咖啡调调', '不凡的改变', '“17聚幸福”江苏卫视2017跨年演唱会', '江苏卫视', '湖南卫视', '浙江卫视', '启航2020', '2018中国蓝', '时光音乐会']

# 批量数据采集

In [ ]:
singers = [('luodayou', '罗大佑'), ('lizongsheng', '李宗盛'), ('zhangxueyou', '张学友'), ('twins', 'Twins'), ('wangsulong', '汪苏泷'), ('panweibo', '潘玮柏'), ('dengziqi', 'G.E.M. 邓紫棋'), ('xuezhiqian', '薛之谦'), ('xusong', '许嵩'), ('zhangjie', '张杰'), ('taozhe', '陶喆'), ('fangdatong', '方大同'), ('wangfei', '王菲'), ('maobuyi', '毛不易'), ('beyond', 'BEYOND')]
max_page = 10

for i in singers[-1:]:
    file_path_prefix = f"data/{i[0]}/"
    # 如果file_path_prefix不存在，则新建
    if not os.path.exists(file_path_prefix):
        os.makedirs(file_path_prefix)
    # 原始曲目数据采集
    song_data_raw = get_songs_data_raw(singger=i[0], max_page=max_page)
    df_song_data_raw = pd.DataFrame(song_data_raw)
    # 原始曲目保存
    df_song_data_raw.to_csv(file_path_prefix + 'raw_song_data.csv', index=False)
    # 重新读取数据
    df_song_data_raw_read = pd.read_csv(file_path_prefix + 'raw_song_data.csv')
    song_data_raw_read = df_song_data_raw_read.to_dict(orient='records')
    # 删除live歌曲
    df_songs = SongDataCleaner.clear_live_songs(df_song_data_raw_read)
    # 歌曲名清洗
    df_songs = SongDataCleaner.clear_song_name(df_songs)
    # 仅含歌手独唱歌曲
    df_songs = SongDataCleaner.clear_song_singer(df_songs, i[1])
    # 删除晚会歌曲
    df_songs = SongDataCleaner.clear_song_tv_show(df_songs, albums_to_delete)
    df_songs = df_songs.drop_duplicates(subset=['song_name_pure'], keep='first').reset_index(drop=True)

    df_songs_final = df_songs.head(130)
    df_songs_final['publish_date'] = df_songs_final['publish_time'].apply(
        lambda x: format_timestamp(x))
    df_songs_final = df_songs_final[df_songs_final['publish_date'].str.contains('-')]
    df_songs_final['publish_year'] = df_songs_final['publish_date'].apply(
        lambda x: x.split('-')[0])
    df_songs_final.to_csv(file_path_prefix + 'cleared_song_data.csv', index=False)
    # 歌词采集与清洗
    get_all_songs_lyric(file_path_prefix+'raw_lyric_data.json', df_songs_final)
    clear_and_save_lyric(file_path_prefix, df_songs_final)

# main

In [29]:
# file_path_prefix = "data/liuyuning/"
# singger = "刘宇宁"
# max_page = 14

# file_path_prefix = "data/liyuchun/"
# singer = "李宇春"
# max_page = 14

file_path_prefix = "data/fangdatong/"
singer = "方大同"
max_page = 10
if not os.path.exists(file_path_prefix):
    os.makedirs(file_path_prefix)

### 曲目采集

In [ ]:
# 原始曲目数据采集
song_data_raw = get_songs_data_raw(singger=singer, max_page=max_page)

In [ ]:
df_song_data_raw = pd.DataFrame(song_data_raw)
# 原始曲目保存
df_song_data_raw.to_csv(file_path_prefix + 'raw_song_data.csv', index=False)

In [30]:
# 重新读取数据
df_song_data_raw_read = pd.read_csv(file_path_prefix + 'raw_song_data.csv')
song_data_raw_read = df_song_data_raw_read.to_dict(orient='records')
df_song_data_raw_read

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time
0,5293866,003cSLOO35W3yP,特别的人,NaN,方大同,1066,003zHcYF44FVEV,危险世界,456882,000GvdTR0qcKh8,259,1397145600
1,415824,0028XLMG07oUms,Love Song,NaN,方大同,1066,003zHcYF44FVEV,未来,33619,003Ctb8A447AgL,269,1198771200
2,510240500,003BBkww3jWdeI,才二十三,NaN,方大同,1066,003zHcYF44FVEV,梦想家 The Dreamer,56828085,002abjXr4Gc7sw,224,1724947200
3,2550926,001lmD2a2YZYN3,麦恩莉,NaN,方大同,1066,003zHcYF44FVEV,回到未来,192334,000ih4iv3HCmno,288,1353600000
4,186041,002IFYcy4UMZNg,爱爱爱,NaN,方大同,1066,003zHcYF44FVEV,爱爱爱,15997,002kkyPO1moicK,213,1167321600
...,...,...,...,...,...,...,...,...,...,...,...,...
295,644326,0005AYWc1A30BV,Georgia On My Mind (Live),NaN,方大同,1066,003zHcYF44FVEV,Timeless演唱会,54808,000TcCeA1DrezM,320,1259251200
296,644339,000DQsSN2zcmEJ,You Are The Sunshine Of My Life (Live),NaN,方大同,1066,003zHcYF44FVEV,Timeless演唱会,54808,000TcCeA1DrezM,683,1259251200
297,235068152,002MANAn3fsYtP,Ten Reasons (Live),NaN,方大同,1066,003zHcYF44FVEV,方大同·专场,7257941,003wIRKV0Ye1zg,227,1564502400
298,334576271,004Rsy2Z3LdsTc,兄妹 (Live),NaN,"方大同,薛凯琪","1066,123","003zHcYF44FVEV,002H2FME3sl3Ne",NaN,0,NaN,215,1106150400
299,100892356,000ilPWx4c6fiS,妹妹 (Live),NaN,方大同,1066,003zHcYF44FVEV,This Love Live 2007,837715,001MpRHO4WdAgB,207,1132070400

### 清洗

In [31]:
# 删除live歌曲
df_songs = SongDataCleaner.clear_live_songs(df_song_data_raw_read)
# 歌曲名清洗
df_songs = SongDataCleaner.clear_song_name(df_songs)
# 仅含歌手独唱歌曲
df_songs = SongDataCleaner.clear_song_singer(df_songs, singer)
# 删除晚会歌曲
df_songs = SongDataCleaner.clear_song_tv_show(df_songs, albums_to_delete)
df_songs = df_songs.drop_duplicates(subset=['song_name_pure'], keep='first').reset_index(drop=True)
df_songs

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,song_name_unique,song_name_pure,album_name_pure
0,5293866,003cSLOO35W3yP,特别的人,NaN,方大同,1066,003zHcYF44FVEV,危险世界,456882,000GvdTR0qcKh8,259,1397145600,特别的人,特别的人,危险世界
1,415824,0028XLMG07oUms,Love Song,NaN,方大同,1066,003zHcYF44FVEV,未来,33619,003Ctb8A447AgL,269,1198771200,LoveSong,lovesong,未来
2,510240500,003BBkww3jWdeI,才二十三,NaN,方大同,1066,003zHcYF44FVEV,梦想家 The Dreamer,56828085,002abjXr4Gc7sw,224,1724947200,才二十三,才二十三,梦想家 The Dreamer
3,2550926,001lmD2a2YZYN3,麦恩莉,NaN,方大同,1066,003zHcYF44FVEV,回到未来,192334,000ih4iv3HCmno,288,1353600000,麦恩莉,麦恩莉,回到未来
4,186041,002IFYcy4UMZNg,爱爱爱,NaN,方大同,1066,003zHcYF44FVEV,爱爱爱,15997,002kkyPO1moicK,213,1167321600,爱爱爱,爱爱爱,爱爱爱
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,214680966,001ntbIf3aEa6Q,Saving Snowy,NaN,方大同,1066,003zHcYF44FVEV,Emi The Dream Catcher,4182762,003NGfUZ0pXZYf,183,1531411200,SavingSnowy,savingsnowy,Emi The Dream Catcher
138,108716748,001eWFJC2OR9EY,All Night,NaN,方大同,1066,003zHcYF44FVEV,JTW 西游记,1627251,001GJyjx4VpLiW,215,1474992000,AllNight,allnight,JTW 西游记
139,108716747,003UcBfL1vTcQD,悟空 2003 Demo,NaN,方大同,1066,003zHcYF44FVEV,JTW 西游记,1627251,001GJyjx4VpLiW,245,1474992000,悟空2003Demo,悟空2003demo,JTW 西游记
140,5079761,003wjwGL3aG4Li,You are the sunshine of my life,NaN,方大同,1066,003zHcYF44FVEV,The Soulboy Collection,446972,002oMaJh2rc9vK,183,1249920000,Youarethesunshineofmylife,youarethesunshineofmylife,The Soulboy Collection
141,125086240,001jrE8S3wCBOL,雪花飘 (Demo),NaN,方大同,1066,003zHcYF44FVEV,NaN,0,NaN,95,0,雪花飘,雪花飘,nan

In [ ]:
# 特别处理
df_songs = df_songs[~df_songs['song_name_pure'].str.contains('#maydayblue20th')]
df_songs

In [32]:
# 前130首
songs_list_all = df_songs['song_name_pure'].to_list()
songs_list_130 = df_songs.head(130)['song_name_pure'].to_list()

## 歌单确认

In [33]:
# 李宇春
songs_to_add = [
    '皇后与梦想', '下雨', '冰菊物语', '我的王国', '漂浮地铁', '今天有朵云爱我', '您所拨打的电话号码是空号',
    '一而再再而三地喜欢你', '人间乐园', 'TMD我爱你', '口音', '木兰', '开放'
]
songs_to_delete = ['今夜你会不会来', '春风十里', '情书', '那女孩对我说', '南方姑娘', '爱你所爱', '无心睡眠', '莫过于此', '天黑黑', '张三的歌', '漂洋过海来看你', '城里的月光', '不要对他说', '下个,路口,见']
# 陈奕迅
songs_to_delete = ['新曲+精选', 'K歌之王AIR', '慢慢喜欢你', '最冷一天']
# 任贤齐
songs_to_delete = ['伤心太平洋+心太软+我是一只鱼+对面的女孩看过来', '桥边姑娘', '你知道我在等你吗', '我是一只小小鸟', '外婆的澎湖湾2015', '海阔天空', '爱的路上只有你和我', '爱的初体验', '美丽的坏女人', '朋友的酒']
# 林俊杰
# songs_to_delete = ['开场白', '无聊', '起风了']
# 陈信宏
# songs_to_delete = ['玫瑰少年-FromTHEFIRSTTAKE', '疯狂世界+候鸟', '2010离开地球表面', '盛夏光年×HIPHOPMAN', 'Paradise+倔强', 'Hosee', 'SHERO']
# 蔡依林
# songs_to_delete = ['看我七十二变', '爱情36计']
# 伍佰
# songs_to_delete = ['少年吔,安啦！']
# 凤凰传奇
songs_to_delete = [
    '海底', 'mrs.leta', '好运来', '普通disco', '【拜新年】专辑歌曲串烧', '好汉歌', '狼的诱惑广场舞版',
    '专辑歌曲串烧', '歌曲串烧', 'dj天籁传奇', '天蓝蓝)'
]
# Beyond
songs_to_delete = [
    '为了你,为了我', '真的爱妳', '遥かなる夢に', '灰色軌跡', '遥かなる梦に〜Faraway〜',
    'リゾ·ラバ～International～', 'Cryin', '遥かなるゆめに～Faraway', '喜欢妳'
]

# 罗大佑
songs_to_delete = ['童年full']

# 方大同
songs_to_delete = ['假行僧']

songs_list_final = songs_list_130.copy()

In [ ]:
# 添加
for i in songs_to_add:
    if i not in songs_list_final:
        print(i)
        songs_list_final.append(i)

In [34]:
# 删除
for i in songs_to_delete:
    if i in songs_list_final:
        print(i)
        songs_list_final.remove(i)

假行僧

In [35]:
len(songs_list_final)

129

## 歌曲数据确认

In [36]:
df_songs_final = df_songs[df_songs['song_name_pure'].isin(
    songs_list_final)].reset_index(drop=True)

# df_songs_final = df_songs_final.drop(columns=['song_name_unique'])
# df_songs_final['song_name_unique'] = df_songs_final['song_name_pure']
df_songs_final['publish_date'] = df_songs_final['publish_time'].apply(
    lambda x: format_timestamp(x))
df_songs_final = df_songs_final[df_songs_final['publish_date'].str.contains('-')]
df_songs_final['publish_year'] = df_songs_final['publish_date'].apply(
    lambda x: x.split('-')[0])
df_songs_final

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,song_name_unique,song_name_pure,album_name_pure,publish_date,publish_year
0,5293866,003cSLOO35W3yP,特别的人,NaN,方大同,1066,003zHcYF44FVEV,危险世界,456882,000GvdTR0qcKh8,259,1397145600,特别的人,特别的人,危险世界,2014-04-11,2014
1,415824,0028XLMG07oUms,Love Song,NaN,方大同,1066,003zHcYF44FVEV,未来,33619,003Ctb8A447AgL,269,1198771200,LoveSong,lovesong,未来,2007-12-28,2007
2,510240500,003BBkww3jWdeI,才二十三,NaN,方大同,1066,003zHcYF44FVEV,梦想家 The Dreamer,56828085,002abjXr4Gc7sw,224,1724947200,才二十三,才二十三,梦想家 The Dreamer,2024-08-30,2024
3,2550926,001lmD2a2YZYN3,麦恩莉,NaN,方大同,1066,003zHcYF44FVEV,回到未来,192334,000ih4iv3HCmno,288,1353600000,麦恩莉,麦恩莉,回到未来,2012-11-23,2012
4,186041,002IFYcy4UMZNg,爱爱爱,NaN,方大同,1066,003zHcYF44FVEV,爱爱爱,15997,002kkyPO1moicK,213,1167321600,爱爱爱,爱爱爱,爱爱爱,2006-12-29,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,186053,002HoYFU1CJPfo,Love Outrolude (纯音乐),NaN,方大同,1066,003zHcYF44FVEV,爱爱爱,15997,002kkyPO1moicK,92,1167321600,LoveOutrolude,loveoutrolude,爱爱爱,2006-12-29,2006
125,149094,00168srj3jDbAv,跳,NaN,方大同,1066,003zHcYF44FVEV,Soulboy,13207,004J3oTJ2E4cuo,213,1132070400,跳,跳,Soulboy,2005-11-16,2005
126,108282169,002Wqlc83v0EbV,Once,NaN,方大同,1066,003zHcYF44FVEV,JTW 西游记 (Gold) [Explicit],1582772,000BjEpu1wy8th,171,1638892800,Once,once,JTW 西游记 (Gold) [Explicit],2021-12-08,2021
127,829563,004Iqqlc411g7A,Over Reprise,NaN,方大同,1066,003zHcYF44FVEV,15,70039,000HVhyy49acT8,167,1303228800,OverReprise,overreprise,15,2011-04-20,2011
128,351781404,003pAwqf1cVLDU,清楚点,NaN,方大同,1066,003zHcYF44FVEV,清楚点,26873253,002ZXgUe48Upou,214,1649865600,清楚点,清楚点,清楚点,2022-04-14,2022

In [37]:
df_songs_final.to_csv(file_path_prefix + 'cleared_song_data.csv', index=False)

## 歌词采集

In [15]:
get_all_songs_lyric(file_path_prefix+'raw_lyric_data.json', df_songs_final)

耶稣的另一个名字2020
仿莫扎特奏鸣练习曲

## 歌词清洗

In [38]:
clear_and_save_lyric(file_path_prefix, df_songs_final)

In [39]:
# 歌词数据查验
df_lyric = pd.read_json(f"{file_path_prefix}cleared_lyric_data.json")
df_lyric['lyric_length'] = df_lyric['lyrics_text'].apply(lambda x: len(x))
df_lyric.sort_values(by='lyric_length')

,song_id,song_name,start_time,has_lyric,lyricist,composer,arranger,lyrics_text,lyric_length
127,829563,Over Reprise,NaT,0,,,,,0
97,5302740,Welcome,2026-03-15 00:00:22,1,,方大同,,欢迎你。火车即将到站。请排好队。,16
87,624423,狂潮,2026-03-15 00:10:37,1,黄霑,顾嘉煇,,是他也是你和我。同相亲相爱也相争。大家偶遇在人海。你我各留痕。几许欢与笑。多少爱和恨。那狂潮...,125
86,5302743,桃花运,2026-03-15 00:00:19,1,小广,方大同,,春意等谁浓，青山等谁染红。结束萧瑟秋梦。一年开一重，有情人，才会懂。冬雪等谁融，旧枝等谁新种...,154
72,829559,二人游,2026-03-15 00:21:58,1,方大同,方大同,方大同,不要再过来。不要靠近我。绝别再诱我。也别再秀。你知不知道。何时可收。这不能把握。就别再进。我...,162
...,...,...,...,...,...,...,...,...,...
16,5293864,天气先生,2026-03-15 00:02:07,1,方大同,方大同,,Maybe，we，won&apos;t，see，the，sunrise。Maybe，we，w...,2040
88,108282161,Love You So Much,2026-03-15 00:11:27,1,方大同/小崔,方大同,,夜绚烂花火已熄灭。最刺心的是离别。痛在没有你的季节。回忆爱从快乐走到悲哀。紧握的手却松开。再...,2116
106,106725491,Gotta Make A Change,2026-03-15 01:29:22,1,方大同,方大同,,Gotta，make，a，change…。Gotta，make，a，change…。Gott...,2219
68,108282157,Ring Finger,2026-03-15 00:25:48,1,方大同/崔惟楷,方大同/周锡汉,,她一现身就像海啸。无辜表情眼睛在笑。愿为她把灵魂出卖掉。无法说不要。她是女神是女主角。三千佳...,2222
111,5073399,Lights Up,2026-03-15 00:33:08,1,方大同 & Fergus Chow,方大同 & Fergus Chow,,Wutcha，be，like。It's，a，good，life。In，the，limelig...,2271

In [40]:
# 歌词文本长度大于0
df_lyric = df_lyric[df_lyric['lyric_length'] > 20]
df_lyric

,song_id,song_name,start_time,has_lyric,lyricist,composer,arranger,lyrics_text,lyric_length
0,5293866,特别的人,2026-03-15 00:15:28,1,方大同,方大同,方大同,爱一个人或许要慷慨。若只想要被爱。最后没有了对白。必须有你我的情真。不求计分的平等。总有幸福...,461
1,415824,Love Song,2026-03-15 00:21:52,1,方大同,方大同,方大同,我写了这首歌，是一首简单的。不复杂也不难唱的那一种歌。这不是那种。只剩下那钢琴的歌。也不是那...,722
2,510240500,才二十三,2026-03-15 00:01:42,1,方大同,方大同,方大同,时间，等不了人。生活中，一不留神。转个眼秒杀了。随秒针蒸发了。昨天变成了今天。过去变成了现在...,380
3,2550926,麦恩莉,2026-03-15 00:01:22,1,C君,方大同,方大同,曾经受过一些伤害。曾经有些看不开。却也胆怯迎接将来。怕爱再卷来。所以我已停止爱。倒也过得挺自...,736
4,186041,爱爱爱,2026-03-15 00:16:46,1,周耀辉,方大同,,在哪里记载第一个桃花贼。谁在哪里典卖第一支紫玉钗。我在这里见怪更怪。见过电影里面人家的海。更...,374
...,...,...,...,...,...,...,...,...,...
123,624424,La Bamba,2026-03-15 00:11:33,1,,,,Para，bailar，la，bamba。Para，bailar，la，bamba。Se，n...,708
124,186053,Love Outrolude (纯音乐),2026-03-15 00:03:25,1,,方大同,,I，just，want，to，thank，you，everybody，for。Checkin...,985
125,149094,跳,2026-03-15 00:11:37,1,方大同,方大同,,今天所有混乱。新闻报纸登满。是非暗战伤人。难怪睡眠不安。左看拥有一切。右看只有分裂。这个痛苦...,881
126,108282169,Once,2026-03-15 00:13:42,1,方大同,方大同,,When，the，time，had，come。Many，times，before。Many，...,871
128,351781404,清楚点,2026-03-15 00:04:28,1,方大同,方大同,方大同,他要推给你的东西，真的好吗。物质变得像空气，真的豪华。仔细看它的成分。是否有那么的纯正。我们...,649

In [ ]:
# 删除有问题的
song_ids_to_delete = [1056503]
df_lyric = df_lyric[~df_lyric['song_id'].isin(song_ids_to_delete)]
df_lyric

In [41]:
# 覆盖原文件
df_lyric['start_time'] = df_lyric['start_time'].astype(str).apply(lambda x: x.split(' ')[1])
df_lyric_d = df_lyric.to_dict(orient='records')
with open(file_path_prefix + 'cleared_lyric_data.json', 'w',
              encoding='utf-8') as f:
        json.dump(df_lyric_d, f, ensure_ascii=False, indent=4)

## 特别处理

In [ ]:
df_lyric['lyricist'].unique()

In [ ]:
lyricist = ['阿信', '五月天阿信', '五月天 阿信', '阿信(五月天)']
df_lyric_flited = df_lyric[df_lyric['lyricist'].isin(lyricist)]
df_lyric_flited

In [ ]:
songs_to_delete_lyric = ['派对动物 + 离开地球表面 (live in the sky)', '伤心的人就听撑腰 (Life Live)', '明白 (后段) (Live)']
df_lyric_flited = df_lyric_flited[~df_lyric_flited['song_name'].isin(songs_to_delete_lyric)]
df_lyric_flited

In [ ]:
# 将df_lyric_flited保存为json
df_lyric_flited = df_lyric_flited.copy()
df_lyric_flited['start_time'] = df_lyric_flited['start_time'].astype(str).apply(lambda x: x.split(' ')[1])
df_lyric_flited_d = df_lyric_flited.to_dict(orient='records')
with open(file_path_prefix + 'cleared_lyric_data.json', 'w',
              encoding='utf-8') as f:
        json.dump(df_lyric_flited_d, f, ensure_ascii=False, indent=4)