# 歌词分词，词性标注

In [1]:

import json
import pandas as pd

import jieba
import jieba.posseg as pseg
from collections import Counter
from openai import OpenAI

In [2]:
# 可以选择是否加载
# jieba.load_userdict('data/mayday_dict_simple.txt')

In [3]:
import sys
sys.path.append('..')

# 歌曲数据

In [4]:
songs_file_path = 'data_output/liuyuning/qq_songs_data_ost.csv'
df_songs = pd.read_csv(songs_file_path)
df_songs

,song_id,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,tv_name,song_name_unique,publish_date,is_ost
0,633973719,0029blSZ16tCiJ,纵马踏歌行,《剑来》动画第二季插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,83047554,纵马踏歌行,003otjHh1KR2Lg,176,1768320000,剑来,纵马踏歌行,2026-01-14,1
1,629395245,003cEvPA3QuEqn,荣光,《风过留痕》影视剧片尾曲,刘宇宁,2241311,001Iu4Dv1NzRCD,81721431,荣光,002CbsMp1BXe73,265,1770084000,风过留痕,荣光,2026-02-03,1
2,370388317,001l38Gx3sl3kP,寻一个你,《苍兰诀》电视剧温情主题曲,刘宇宁,2241311,001Iu4Dv1NzRCD,33455648,苍兰诀 东方幻想影视原声带,001c5tj84NH6dH,267,1660010400,苍兰诀,寻一个你,2022-08-09,1
3,578702351,001QwWqP38bXCs,烽月,电视剧《折腰》情感主题曲/片尾曲,刘宇宁,2241311,001Iu4Dv1NzRCD,67523527,折腰 影视原声专辑,001NFTqM3zNUv2,265,1747411200,折腰,烽月,2025-05-17,1
4,285903302,004a6xSN489klN,当遇见你,《冰糖炖雪梨》电视剧片尾曲,刘宇宁,2241311,001Iu4Dv1NzRCD,15738588,当遇见你,0027ZeN63fdE93,191,1583769600,冰糖炖雪梨,当遇见你,2020-03-10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,448734874,001I5tmS3sA6jB,爱情之所以,《正青春》电视剧插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,43671782,正青春 电视剧原声带,004TS8Lz3FGMHs,207,1723478400,正青春,爱情之所以,2024-08-13,1
146,401100858,0009Ba6M3Rd0kp,望道,《望道》电影同名主题曲,刘宇宁,2241311,001Iu4Dv1NzRCD,36285879,望道,001SGs7l1BP05L,196,1678982400,望道,望道,2023-03-17,1
147,335548330,0032iLRJ3YH8fN,风起时再见,《迷雾追踪》影视剧主题曲,刘宇宁,2241311,001Iu4Dv1NzRCD,33427051,迷雾追踪 影视原声带,003V3TEN24Hj29,260,1607616000,迷雾追踪,风起时再见,2020-12-11,1
148,264776262,002rs2Tk3fYVGh,要替我幸福,《暖暖，请多指教》电视剧片尾曲,刘宇宁,2241311,001Iu4Dv1NzRCD,12373795,暖暖，请多指教 影视原声带,003eJOh54YBBK1,242,1589472000,暖暖，请多指教,要替我幸福,2020-05-15,1
149,297559879,000sfLHg43UbQo,苍穹之下,电视剧《斗罗大陆》戴沐白人物曲）,刘宇宁,2241311,001Iu4Dv1NzRCD,17500078,斗罗大陆 史兰客七怪音乐专辑,000uo5Ig1624LG,272,1613354400,斗罗大陆,苍穹之下,2021-02-15,1

# 分词，词频与词性分析

In [5]:
word_to_fix = {
    '阮': 'r',
    '袂': 'v'
}

In [6]:
def process_lyrics_with_jieba(text):
    # 1. 词性标注与分词
    # jieba.posseg 会同时返回词和词性
    words_with_pos = pseg.cut(text)

    
    # 2. 过滤无意义字符（标点、空格、单字符停用词）
    filtered_data = []
    for word, pos in words_with_pos:
        # 排除标点符号（x表示标点）及空白字符
        if pos != 'x' and len(word.strip()) > 0:
            if word in word_to_fix:
                filtered_data.append((word, word_to_fix[word]))
            else:
                filtered_data.append((word, pos))
    
    # 3. 统计词频
    word_counts = Counter([item[0] for item in filtered_data])
    
    # 4. 汇总信息 (词, 词性, 频数)
    # 我们以词为 Key，存储词性
    word_pos_map = {word: pos for word, pos in filtered_data}
    
    # 排序：按词频从高到低
    sorted_results = []
    for word, count in word_counts.most_common():
        sorted_results.append({
            "word": word,
            "pos": word_pos_map[word],
            "freq": count # 词频
        })
    
    return sorted_results

In [7]:
lyric_file_path = 'data_output/liuyuning/qq_lyric_data_cleared.json'
# 读取歌词文件
with open(lyric_file_path, 'r') as f:
    lyric_data = json.load(f)

In [8]:
lyric_words_dict = {}
for i in lyric_data:
    if i:
        lyric_words_dict[i['song_id']] = process_lyrics_with_jieba(i['lyrics_text'])
lyric_words_dict

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/zj/y5ymt78d6qd4p13cf1q_3rch0000gn/T/jieba.cache
Loading model cost 0.648 seconds.
Prefix dict has been built successfully.

{633973719: [{'word': '处', 'pos': 'n', 'freq': 4},
  {'word': '了', 'pos': 'ul', 'freq': 4},
  {'word': '把', 'pos': 'p', 'freq': 2},
  {'word': '江湖', 'pos': 'ns', 'freq': 2},
  {'word': '斟入', 'pos': 'v', 'freq': 2},
  {'word': '陈年', 'pos': 'nr', 'freq': 2},
  {'word': '酒', 'pos': 'n', 'freq': 2},
  {'word': '醉眼', 'pos': 'n', 'freq': 2},
  {'word': '望断', 'pos': 'v', 'freq': 2},
  {'word': '十二重', 'pos': 'm', 'freq': 2},
  {'word': '楼', 'pos': 'n', 'freq': 2},
  {'word': '锈剑', 'pos': 'n', 'freq': 2},
  {'word': '挑落', 'pos': 'v', 'freq': 2},
  {'word': '风雪', 'pos': 'n', 'freq': 2},
  {'word': '落款', 'pos': 'n', 'freq': 2},
  {'word': '梅花', 'pos': 'nr', 'freq': 2},
  {'word': '替', 'pos': 'p', 'freq': 2},
  {'word': '旧', 'pos': 'a', 'freq': 2},
  {'word': '恩仇', 'pos': 'nr', 'freq': 2},
  {'word': '长街', 'pos': 'ns', 'freq': 2},
  {'word': '悬满', 'pos': 'v', 'freq': 2},
  {'word': '褪色', 'pos': 'v', 'freq': 2},
  {'word': '灯笼', 'pos': 'n', 'freq': 2},
  {'word': '照见', 'pos': 'v', 'freq': 2},
  {'word': '指', 'pos': 'n', 'freq': 2},
  {'word': '间', 'pos': 'f', 'freq': 2},
  {'word': '烟霞', 'pos': 'n', 'freq': 2},
  {'word': '暗涌', 'pos': 'v', 'freq': 2},
  {'word': '马蹄', 'pos': 'n', 'freq': 2},
  {'word': '卷起', 'pos': 'v', 'freq': 2},
  {'word': '孤', 'pos': 'a', 'freq': 2},
  {'word': '烟', 'pos': 'n', 'freq': 2},
  {'word': '回首', 'pos': 'v', 'freq': 2},
  {'word': '残', 'pos': 'n', 'freq': 2},
  {'word': '碑刻', 'pos': 'n', 'freq': 2},
  {'word': '满', 'pos': 'a', 'freq': 2},
  {'word': '青松', 'pos': 'n', 'freq': 2},
  {'word': '至此', 'pos': 'd', 'freq': 2},
  {'word': '鲜花', 'pos': 'n', 'freq': 2},
  {'word': '赠', 'pos': 'v', 'freq': 2},
  {'word': '我', 'pos': 'r', 'freq': 2},
  {'word': '袖', 'pos': 'v', 'freq': 2},
  {'word': '纵马踏碎', 'pos': 'i', 'freq': 2},
  {'word': '琉璃', 'pos': 'n', 'freq': 2},
  {'word': '秋', 'pos': 't', 'freq': 2},
  {'word': '任它', 'pos': 'r', 'freq': 2},
  {'word': '九万里', 'pos': 'm', 'freq': 2},
  {'word': '星穹', 'pos': 'n', 'freq': 2},
  {'word': '压襟', 'pos': 'n', 'freq': 2},
  {'word': '头', 'pos': 'n', 'freq': 2},
  {'word': '斩断', 'pos': 'v', 'freq': 2},
  {'word': '宿命', 'pos': 'n', 'freq': 2},
  {'word': '向', 'pos': 'p', 'freq': 2},
  {'word': '白昼', 'pos': 'nr', 'freq': 2},
  {'word': '天河', 'pos': 'ns', 'freq': 2},
  {'word': '倾入', 'pos': 'v', 'freq': 2},
  {'word': '喉间', 'pos': 'n', 'freq': 2},
  {'word': '流', 'pos': 'n', 'freq': 2},
  {'word': '抖落', 'pos': 'v', 'freq': 2},
  {'word': '星辰', 'pos': 'n', 'freq': 2},
  {'word': '作剑', 'pos': 'n', 'freq': 2},
  {'word': '裘', 'pos': 'nr', 'freq': 2},
  {'word': '劈开', 'pos': 'v', 'freq': 2},
  {'word': '千仞', 'pos': 'nr', 'freq': 2},
  {'word': '山色', 'pos': 'n', 'freq': 2},
  {'word': '照', 'pos': 'n', 'freq': 2},
  {'word': '刀锋', 'pos': 'n', 'freq': 2},
  {'word': '瘦', 'pos': 'a', 'freq': 2},
  {'word': '明月', 'pos': 't', 'freq': 2},
  {'word': '悬', 'pos': 'v', 'freq': 2},
  {'word': '弓', 'pos': 'v', 'freq': 2},
  {'word': '射', 'pos': 'v', 'freq': 2},
  {'word': '傲愁', 'pos': 'a', 'freq': 2},
  {'word': '天地', 'pos': 'n', 'freq': 2},
  {'word': '同游', 'pos': 'j', 'freq': 2}],
 629395245: [{'word': '的', 'pos': 'uj', 'freq': 14},
  {'word': '像', 'pos': 'v', 'freq': 5},
  {'word': '光', 'pos': 'n', 'freq': 4},
  {'word': '只', 'pos': 'd', 'freq': 3},
  {'word': '希望', 'pos': 'v', 'freq': 3},
  {'word': '伸出', 'pos': 'v', 'freq': 3},
  {'word': '了', 'pos': 'ul', 'freq': 3},
  {'word': '臂膀', 'pos': 'n', 'freq': 3},
  {'word': '汗水', 'pos': 'n', 'freq': 2},
  {'word': '替代', 'pos': 'n', 'freq': 2},
  {'word': '泪水', 'pos': 'n', 'freq': 2},
  {'word': '重量', 'pos': 'n', 'freq': 2},
  {'word': '用', 'pos': 'p', 'freq': 2},
  {'word': '伤口', 'pos': 'n', 'freq': 2},
  {'word': '遮住', 'pos': 'v', 'freq': 2},
  {'word': '枪口', 'pos': 'n', 'freq': 2},
  {'word': '声响', 'pos': 'n', 'freq': 2},
  {'word': '没有', 'pos': 'v', 'freq': 2},
  {'word': '天生', 'pos': 'n', 'freq': 2},
  {'word': '不屈', 'pos': 'v', 'freq': 2},
  {'word': '倔强', 'pos': 'a', 'freq': 2},
  {'word': '因', 'pos': 'p', 'freq': 2},
  {'word': '总', 'pos': 'n', 'freq': 2},
  {'word': '有人', 'pos': 'r', 'freq': 2},
  {'word': '在', 'pos': 'p', 'freq': 2},
  {'word': '前方', 'pos': 'f', 'freq': 2},
  {'word': '挡', 'pos': 'zg', 'freq': 2},
  {'word': '下', 'pos': 'f', 'freq': 2},
  {'word': '风浪', 'pos': 'n', 'freq': 2},
  {'word': '变得', 'pos': 'v', 'freq': 2},
  {'word': '习以为常', 'pos': 'i', 'freq': 2},
  {'word': '就', 'pos': 'd', 'freq': 2},
  {'word': '成', 'pos': 'n', 'freq': 2},
  {'word': '你', 'pos': 'r', 'freq': 2},
  {'word': '模样', 'pos': 'n', 'freq': 2},
  {'word': '披着', 'pos': 'v', 'freq': 2},
  {'word': '只身', 'pos': 'v', 'freq': 2},
  {'word': '也', 'pos': 'd', 'freq': 2},
  {'word': '勇往', 'pos': 'v', 'freq': 2},
  {'word': '穿越', 'pos': 'v', 'freq': 2},
  {'word': '过', 'pos': 'ug', 'freq': 2},
  {'word': '命运', 'pos': 'n', 'freq': 2},
  {'word': '战场', 'pos': 'n', 'freq': 2},
  {'word': '赶', 'pos': 'v', 'freq': 1},
  {'word': '当', 'pos': 'p', 'freq': 1},
  {'word': '每', 'pos': 'r', 'freq': 1},
  {'word': '一次', 'pos': 'm', 'freq': 1},
  {'word': '不', 'pos': 'd', 'freq': 1},
  {'word': '平凡', 'pos': 'a', 'freq': 1},
  {'word': '只为', 'pos': 'c', 'freq': 1},
  {'word': '将', 'pos': 'd', 'freq': 1},
  {'word': '肩上', 'pos': 's', 'freq': 1},
  {'word': '徽章', 'pos': 'n', 'freq': 1},
  {'word': '擦亮', 'pos': 'v', 'freq': 1},
  {'word': '黑夜', 'pos': 'n', 'freq': 1},
  {'word': '中', 'pos': 'f', 'freq': 1},
  {'word': '暗涌', 'pos': 'v', 'freq': 1},
  {'word': '汇聚', 'pos': 'v', 'freq': 1},
  {'word': '站', 'pos': 'v', 'freq': 1},
  {'word': '当先', 'pos': 'd', 'freq': 1},
  {'word': '把', 'pos': 'p', 'freq': 1},
  {'word': '自我', 'pos': 'r', 'freq': 1},
  {'word': '遗忘', 'pos': 'v', 'freq': 1},
  {'word': '为', 'pos': 'p', 'freq': 1},
  {'word': '握拳', 'pos': 'nz', 'freq': 1},
  {'word': '宣誓', 'pos': 'v', 'freq': 1},
  {'word': '理想', 'pos': 'n', 'freq': 1},
  {'word': '尘埃', 'pos': 'n', 'freq': 1},
  {'word': '倒映', 'pos': 'v', 'freq': 1},
  {'word': '里', 'pos': 'f', 'freq': 1},
  {'word': '勾勒', 'pos': 'nrt', 'freq': 1},
  {'word': '会', 'pos': 'v', 'freq': 1},
  {'word': '照亮', 'pos': 'v', 'freq': 1},
  {'word': '正义', 'pos': 'n', 'freq': 1},
  {'word': '方向', 'pos': 'n', 'freq': 1}],
 370388317: [{'word': '不负', 'pos': 'v', 'freq': 12},
  {'word': '你', 'pos': 'r', 'freq': 9},
  {'word': '为', 'pos': 'p', 'freq': 5},
  {'word': '的', 'pos': 'uj', 'freq': 4},
  {'word': '不', 'pos': 'd', 'freq': 4},
  {'word': '此生', 'pos': 't', 'freq': 3},
  {'word': '相遇', 'pos': 'v', 'freq': 3},
  {'word': '我', 'pos': 'r', 'freq': 3},
  {'word': '偏向', 'pos': 'n', 'freq': 3},
  {'word': '苦海', 'pos': 'n', 'freq': 3},
  {'word': '去', 'pos': 'v', 'freq': 3},
  {'word': '只为', 'pos': 'c', 'freq': 3},
  {'word': '渡', 'pos': 'v', 'freq': 3},
  {'word': '不远万里', 'pos': 'i', 'freq': 3},
  {'word': '只', 'pos': 'd', 'freq': 3},
  {'word': '朝夕', 'pos': 'n', 'freq': 3},
  {'word': '纵', 'pos': 'n', 'freq': 3},
  {'word': '天下', 'pos': 's', 'freq': 3},
  {'word': '负尽', 'pos': 'v', 'freq': 3},
  {'word': '每', 'pos': 'zg', 'freq': 2},
  {'word': '一个', 'pos': 'm', 'freq': 2},
  {'word': '做', 'pos': 'v', 'freq': 2},
  {'word': '决定', 'pos': 'v', 'freq': 2},
  {'word': '故事', 'pos': 'n', 'freq': 2},
  {'word': '几经', 'pos': 'd', 'freq': 2},
  {'word': '辗转', 'pos': 'v', 'freq': 2},
  {'word': '未', 'pos': 'd', 'freq': 2},
  {'word': '落笔', 'pos': 'v', 'freq': 2},
  {'word': '一幕幕', 'pos': 'n', 'freq': 2},
  {'word': '曾经', 'pos': 'd', 'freq': 2},
  {'word': '脑海', 'pos': 'n', 'freq': 2},
  {'word': '放映', 'pos': 'v', 'freq': 2},
  {'word': '刻骨铭心', 'pos': 'i', 'freq': 2},
  {'word': '不想', 'pos': 'v', 'freq': 2},
  {'word': '念', 'pos': 'v', 'freq': 2},
  {'word': '听', 'pos': 'v', 'freq': 2},
  {'word': '心', 'pos': 'n', 'freq': 2},
  {'word': '也', 'pos': 'd', 'freq': 2},
  {'word': '不再', 'pos': 'd', 'freq': 2},
  {'word': '泛起', 'pos': 'v', 'freq': 2},
  {'word': '涟漪', 'pos': 'n', 'freq': 2},
  {'word': '天灯', 'pos': 'n', 'freq': 2},
  {'word': '亮', 'pos': 'v', 'freq': 2},
  {'word': '起', 'pos': 'v', 'freq': 2},
  {'word': '相聚', 'pos': 'v', 'freq': 2},
  {'word': '别离', 'pos': 'v', 'freq': 2},
  {'word': '人来人往', 'pos': 'i', 'freq': 2},
  {'word': '终', 'pos': 'd', 'freq': 2},
  {'word': '更替', 'pos': 'v', 'freq': 2},
  {'word': '沉迷在', 'pos': 'z', 'freq': 1},
  {'word': '清澈', 'pos': 'a', 'freq': 1},
  {'word': '眼睛', 'pos': 'n', 'freq': 1},
  {'word': '是', 'pos': 'v', 'freq': 1},
  {'word': '途经', 'pos': 'n', 'freq': 1},
  {'word': '最', 'pos': 'd', 'freq': 1},
  {'word': '难忘', 'pos': 'v', 'freq': 1},
  {'word': '风景', 'pos': 'n', 'freq': 1},
  {'word': '无人', 'pos': 'n', 'freq': 1},
  {'word': '可', 'pos': 'v', 'freq': 1},
  {'word': '比拟', 'pos': 'v', 'freq': 1},
  {'word': '那些', 'pos': 'r', 'freq': 1},
  {'word': '往昔', 'pos': 't', 'freq': 1},
  {'word': '灿若繁星', 'pos': 'i', 'freq': 1}],
 578702351: [{'word': '你', 'pos': 'r', 'freq': 9},
  {'word': '我', 'pos': 'r', 'freq': 7},
  {'word': '愿', 'pos': 'v', 'freq': 6},
  {'word': '的', 'pos': 'uj', 'freq': 6},
  {'word': '此生', 'pos': 't', 'freq': 5},
  {'word': '曾', 'pos': 'd', 'freq': 3},
  {'word': '跨越', 'pos': 'v', 'freq': 3},
  {'word': '山海', 'pos': 'ns', 'freq': 3},
  {'word': '赴', 'pos': 'v', 'freq': 3},
  {'word': '风月', 'pos': 'n', 'freq': 3},
  {'word': '等', 'pos': 'u', 'freq': 3},
  {'word': '白首', 'pos': 'n', 'freq': 3},
  {'word': '一如', 'pos': 'c', 'freq': 3},
  {'word': '初见', 'pos': 'v', 'freq': 3},
  {'word': '江南', 'pos': 'ns', 'freq': 3},
  {'word': '烟雨', 'pos': 'n', 'freq': 3},
  {'word': '不止', 'pos': 'v', 'freq': 3},
  {'word': '落', 'pos': 'v', 'freq': 3},
  {'word': '在', 'pos': 'p', 'freq': 3},
  {'word': '眉间', 'pos': 'n', 'freq': 3},
  {'word': '心上', 'pos': 's', 'freq': 3},
  {'word': '流连', 'pos': 'v', 'freq': 3},
  {'word': '斩断', 'pos': 'v', 'freq': 3},
  {'word': '宿命', 'pos': 'n', 'freq': 3},
  {'word': '护', 'pos': 'v', 'freq': 3},
  {'word': '笑眼', 'pos': 'n', 'freq': 3},
  {'word': '哪怕', 'pos': 'c', 'freq': 3},
  {'word': '身后', 'pos': 'f', 'freq': 3},
  {'word': '是', 'pos': 'v', 'freq': 3},
  {'word': '风雪', 'pos': 'n', 'freq': 3},
  {'word': '再', 'pos': 'd', 'freq': 3},
  {'word': '多', 'pos': 'm', 'freq': 3},
  {'word': '浮沉', 'pos': 'a', 'freq': 3},
  {'word': '只为', 'pos': 'c', 'freq': 3},
  {'word': '这', 'pos': 'r', 'freq': 3},
  {'word': '一程', 'pos': 'n', 'freq': 3},
  {'word': '思念', 'pos': 'n', 'freq': 3},
  {'word': '不', 'pos': 'd', 'freq': 3},
  {'word': '枉然', 'pos': 'z', 'freq': 3},
  {'word': '却', 'pos': 'd', 'freq': 2},
  {'word': '又', 'pos': 'd', 'freq': 2},
  {'word': '情字', 'pos': 'n', 'freq': 2},
  {'word': '尽头', 'pos': 'd', 'freq': 2},
  {'word': '无', 'pos': 'v', 'freq': 2},
  {'word': '所求', 'pos': 'n', 'freq': 2},
  {'word': '皆', 'pos': 'd', 'freq': 2},
  {'word': '执愿', 'pos': 'v', 'freq': 2},
  {'word': '辗转', 'pos': 'v', 'freq': 2},
  {'word': '朝暮', 'pos': 'n', 'freq': 2},
  {'word': '人间', 'pos': 'n', 'freq': 2},
  {'word': '难两全', 'pos': 'i', 'freq': 2},
  {'word': '烽火', 'pos': 'n', 'freq': 2},
  {'word': '中', 'pos': 'f', 'freq': 2},
  {'word': '聚散', 'pos': 'v', 'freq': 2},
  {'word': '相拥', 'pos': 'v', 'freq': 2},
  {'word': '刻下', 'pos': 'v', 'freq': 2},
  {'word': '温柔', 'pos': 'a', 'freq': 2},
  {'word': '缱绻', 'pos': 'a', 'freq': 2},
  {'word': '惊鸿', 'pos': 'n', 'freq': 2},
  {'word': '一眼', 'pos': 'm', 'freq': 2},
  {'word': '怎', 'pos': 'r', 'freq': 2},
  {'word': '能', 'pos': 'v', 'freq': 2},
  {'word': '忘却', 'pos': 'v', 'freq': 2},
  {'word': '月光', 'pos': 'n', 'freq': 1},
  {'word': '似', 'pos': 'd', 'freq': 1},
  {'word': '深海', 'pos': 'ns', 'freq': 1},
  {'word': '无言', 'pos': 'c', 'freq': 1},
  {'word': '隔岸', 'pos': 's', 'freq': 1},
  {'word': '呵气', 'pos': 'n', 'freq': 1},
  {'word': '将', 'pos': 'd', 'freq': 1},
  {'word': '梦', 'pos': 'n', 'freq': 1},
  {'word': '点燃', 'pos': 'v', 'freq': 1},
  {'word': '怅然', 'pos': 'd', 'freq': 1},
  {'word': '划过', 'pos': 'v', 'freq': 1},
  {'word': '指尖', 'pos': 'n', 'freq': 1},
  {'word': '悄然', 'pos': 'd', 'freq': 1},
  {'word': '拨动', 'pos': 'v', 'freq': 1},
  {'word': '了', 'pos': 'ul', 'freq': 1},
  {'word': '心弦', 'pos': 'n', 'freq': 1},
  {'word': '恍若', 'pos': 'z', 'freq': 1},
  {'word': '故人', 'pos': 'n', 'freq': 1},
  {'word': '隐忍', 'pos': 'v', 'freq': 1},
  {'word': '痴念', 'pos': 'n', 'freq': 1}],
 285903302: [{'word': '的', 'pos': 'uj', 'freq': 27},
  {'word': '你', 'pos': 'r', 'freq': 23},
  {'word': '像', 'pos': 'v', 'freq': 9},
  {'word': '了', 'pos': 'ul', 'freq': 7},
  {'word': '我', 'pos': 'r', 'freq': 7},
  {'word': '这', 'pos': 'r', 'freq': 6},
  {'word': '一秒', 'pos': 'm', 'freq': 6},
  {'word': '第一次', 'pos': 'm', 'freq': 5},
  {'word': '是', 'pos': 'v', 'freq': 5},
  {'word': '一般', 'pos': 'a', 'freq': 4},
  {'word': '眼睛', 'pos': 'n', 'freq': 4},
  {'word': '星星', 'pos': 'nz', 'freq': 4},
  {'word': '给', 'pos': 'p', 'freq': 4},
  {'word': '暖', 'pos': 'a', 'freq': 4},
  {'word': '在', 'pos': 'p', 'freq': 3},
  {'word': '如此', 'pos': 'c', 'freq': 3},
  {'word': '味道', 'pos': 'n', 'freq': 3},
  {'word': '信号', 'pos': 'n', 'freq': 3},
  {'word': '心', 'pos': 'n', 'freq': 3},
  {'word': '想', 'pos': 'v', 'freq': 3},
  {'word': '每个', 'pos': 'r', 'freq': 3},
  {'word': '爱', 'pos': 'v', 'freq': 3},
  {'word': '微笑', 'pos': 'vn', 'freq': 3},
  {'word': '梦', 'pos': 'n', 'freq': 2},
  {'word': '心跳', 'pos': 'v', 'freq': 2},
  {'word': '夜空', 'pos': 'n', 'freq': 2},
  {'word': '闪耀', 'pos': 'v', 'freq': 2},
  {'word': '牵', 'pos': 'v', 'freq': 2},
  {'word': '手心', 'pos': 'n', 'freq': 2},
  {'word': '乱', 'pos': 'd', 'freq': 2},
  {'word': '呼吸', 'pos': 'v', 'freq': 2},
  {'word': '沉迷', 'pos': 'v', 'freq': 2},
  {'word': '就', 'pos': 'd', 'freq': 2},
  {'word': '幸运', 'pos': 'a', 'freq': 2},
  {'word': '蜜', 'pos': 'n', 'freq': 2},
  {'word': '海岛', 'pos': 'ns', 'freq': 2},
  {'word': '微风', 'pos': 'n', 'freq': 2},
  {'word': '围绕', 'pos': 'v', 'freq': 2},
  {'word': '确定', 'pos': 'v', 'freq': 2},
  {'word': '不能', 'pos': 'v', 'freq': 2},
  {'word': '相信', 'pos': 'v', 'freq': 2},
  {'word': '湿', 'pos': 'a', 'freq': 2},
  {'word': '陪你去', 'pos': 'l', 'freq': 2},
  {'word': '天明', 'pos': 'nz', 'freq': 2},
  {'word': '带', 'pos': 'v', 'freq': 2},
  {'word': '飞行', 'pos': 'v', 'freq': 2},
  {'word': '啊', 'pos': 'zg', 'freq': 2},
  {'word': '抱紧', 'pos': 'v', 'freq': 2},
  {'word': '勇气', 'pos': 'n', 'freq': 2},
  {'word': '从此', 'pos': 'c', 'freq': 2},
  {'word': '分离', 'pos': 'v', 'freq': 2},
  {'word': '没有', 'pos': 'v', 'freq': 2},
  {'word': '道理', 'pos': 'n', 'freq': 2},
  {'word': '去', 'pos': 'v', 'freq': 2},
  {'word': '每', 'pos': 'r', 'freq': 2},
  {'word': '一个', 'pos': 'm', 'freq': 2},
  {'word': '只有', 'pos': 'c', 'freq': 1},
  {'word': '能够', 'pos': 'v', 'freq': 1},
  {'word': '明', 'pos': 'a', 'freq': 1},
  {'word': '像是', 'pos': 'v', 'freq': 1},
  {'word': '摘取', 'pos': 'v', 'freq': 1},
  {'word': '那般', 'pos': 'r', 'freq': 1},
  {'word': '拥抱', 'pos': 'v', 'freq': 1},
  {'word': '大大的', 'pos': 'nz', 'freq': 1},
  {'word': '世界', 'pos': 'n', 'freq': 1},
  {'word': '温柔', 'pos': 'a', 'freq': 1},
  {'word': '握紧', 'pos': 'v', 'freq': 1},
  {'word': '守护', 'pos': 'v', 'freq': 1},
  {'word': '秘密', 'pos': 'n', 'freq': 1},
  {'word': '触电', 'pos': 'v', 'freq': 1},
  {'word': '般的', 'pos': 'u', 'freq': 1},
  {'word': '惊喜', 'pos': 'a', 'freq': 1},
  {'word': '应许', 'pos': 'v', 'freq': 1},
  {'word': '不再', 'pos': 'd', 'freq': 1},
  {'word': '看到', 'pos': 'v', 'freq': 1},
  {'word': '丢', 'pos': 'v', 'freq': 1},
  {'word': '命中注定', 'pos': 'l', 'freq': 1},
  {'word': '和', 'pos': 'c', 'freq': 1},
  {'word': '拉', 'pos': 'v', 'freq': 1},
  {'word': '着手', 'pos': 'v', 'freq': 1},
  {'word': '到', 'pos': 'v', 'freq': 1},
  {'word': '彩虹', 'pos': 'nz', 'freq': 1},
  {'word': '上面', 'pos': 'f', 'freq': 1},
  {'word': '旅行', 'pos': 'vn', 'freq': 1},
  {'word': '摘', 'pos': 'v', 'freq': 1},
  {'word': '一颗', 'pos': 'm', 'freq': 1},
  {'word': '星', 'pos': 'n', 'freq': 1},
  {'word': '偷听', 'pos': 'v', 'freq': 1},
  {'word': '心情', 'pos': 'n', 'freq': 1},
  {'word': '让', 'pos': 'v', 'freq': 1},
  {'word': '圆', 'pos': 'vg', 'freq': 1},
  {'word': '梦境', 'pos': 'n', 'freq': 1},
  {'word': '收藏', 'pos': 'v', 'freq': 1},
  {'word': '表情', 'pos': 'n', 'freq': 1},
  {'word': '那', 'pos': 'r', 'freq': 1},
  {'word': '属于', 'pos': 'v', 'freq': 1},
  {'word': '四季', 'pos': 'm', 'freq': 1},
  {'word': '海风', 'pos': 'n', 'freq': 1},
  {'word': '微甜', 'pos': 'a', 'freq': 1},
  {'word': '阳光', 'pos': 'nr', 'freq': 1},
  {'word': '一样', 'pos': 'r', 'freq': 1},
  {'word': '水蜜桃', 'pos': 'n', 'freq': 1},
  {'word': '轻轻', 'pos': 'd', 'freq': 1},
  {'word': '咬', 'pos': 'v', 'freq': 1},
  {'word': '绽放', 'pos': 'v', 'freq': 1},
  {'word': '美妙', 'pos': 'a', 'freq': 1},
  {'word': '再', 'pos': 'd', 'freq': 1},
  {'word': '不', 'pos': 'd', 'freq': 1}],
 626997953: [{'word': '的', 'pos': 'uj', 'freq': 12},
  {'word': '任何', 'pos': 'r', 'freq': 9},
  {'word': '我', 'pos': 'r', 'freq': 9},
  {'word': '多少', 'pos': 'm', 'freq': 9},
  {'word': '有所', 'pos': 'n', 'freq': 9},
  {'word': '失去', 'pos': 'v', 'freq': 6},
  {'word': '后', 'pos': 'f', 'freq': 6},
  {'word': '一切', 'pos': 'r', 'freq': 6},
  {'word': '如常', 'pos': 't', 'freq': 6},
  {'word': '依然', 'pos': 'd', 'freq': 4},
  {'word': '就算', 'pos': 'v', 'freq': 4},
  {'word': '哦', 'pos': 'e', 'freq': 4},
  {'word': '希望', 'pos': 'v', 'freq': 3},
  {'word': '绝望', 'pos': 'v', 'freq': 3},
  {'word': '迷惘', 'pos': 'a', 'freq': 3},
  {'word': '都', 'pos': 'd', 'freq': 3},
  {'word': '不断', 'pos': 'd', 'freq': 3},
  {'word': '成就', 'pos': 'n', 'freq': 3},
  {'word': '勇敢', 'pos': 'a', 'freq': 3},
  {'word': '悲欢', 'pos': 'v', 'freq': 3},
  {'word': '起落', 'pos': 'v', 'freq': 3},
  {'word': '冷暖', 'pos': 'an', 'freq': 3},
  {'word': '每颗', 'pos': 'n', 'freq': 3},
  {'word': '泪水', 'pos': 'n', 'freq': 3},
  {'word': '换', 'pos': 'nz', 'freq': 3},
  {'word': '每次', 'pos': 'r', 'freq': 3},
  {'word': '成长', 'pos': 'v', 'freq': 3},
  {'word': '遗憾', 'pos': 'a', 'freq': 3},
  {'word': '取舍', 'pos': 'v', 'freq': 3},
  {'word': '信仰', 'pos': 'n', 'freq': 3},
  {'word': '日子', 'pos': 'n', 'freq': 3},
  {'word': '不过', 'pos': 'c', 'freq': 3},
  {'word': '原来', 'pos': 'd', 'freq': 3},
  {'word': '是', 'pos': 'v', 'freq': 3},
  {'word': '这样', 'pos': 'r', 'freq': 3},
  {'word': '选择', 'pos': 'v', 'freq': 3},
  {'word': '微笑', 'pos': 'vn', 'freq': 3},
  {'word': '模样', 'pos': 'n', 'freq': 3},
  {'word': '还', 'pos': 'd', 'freq': 3},
  {'word': '能', 'pos': 'v', 'freq': 3},
  {'word': '看起来', 'pos': 'v', 'freq': 3},
  {'word': '面对', 'pos': 'v', 'freq': 2},
  {'word': '早晨', 'pos': 't', 'freq': 1},
  {'word': '微露', 'pos': 'v', 'freq': 1},
  {'word': '阳光', 'pos': 'nr', 'freq': 1},
  {'word': '照亮', 'pos': 'v', 'freq': 1},
  {'word': '了', 'pos': 'ul', 'freq': 1},
  {'word': '眼里', 'pos': 's', 'freq': 1},
  {'word': '暗', 'pos': 'n', 'freq': 1},
  {'word': '生活', 'pos': 'vn', 'freq': 1},
  {'word': '满档', 'pos': 'b', 'freq': 1},
  {'word': '奔忙', 'pos': 'v', 'freq': 1},
  {'word': '从未', 'pos': 'd', 'freq': 1},
  {'word': '遗忘', 'pos': 'v', 'freq': 1},
  {'word': '过', 'pos': 'ug', 'freq': 1},
  {'word': '善良', 'pos': 'a', 'freq': 1},
  {'word': '偶尔', 'pos': 'd', 'freq': 1},
  {'word': '寂寞', 'pos': 'a', 'freq': 1},
  {'word': '来', 'pos': 'v', 'freq': 1},
  {'word': '探望', 'pos': 'v', 'freq': 1},
  {'word': '一路上', 'pos': 'l', 'freq': 1},
  {'word': '回忆', 'pos': 'v', 'freq': 1},
  {'word': '快', 'pos': 'a', 'freq': 1},
  {'word': '闪', 'pos': 'v', 'freq': 1},
  {'word': '曾经', 'pos': 'd', 'freq': 1},
  {'word': '坠落', 'pos': 'v', 'freq': 1},
  {'word': '坚强', 'pos': 'v', 'freq': 1},
  {'word': '终究', 'pos': 'd', 'freq': 1},
  {'word': '需要', 'pos': 'v', 'freq': 1},
  {'word': '时间', 'pos': 'n', 'freq': 1},
  {'word': '帮点', 'pos': 'n', 'freq': 1},
  {'word': '忙', 'pos': 'v', 'freq': 1},
  {'word': '这', 'pos': 'r', 'freq': 1},
  {'word': '世界', 'pos': 'n', 'freq': 1}],
 585294829: [{'word': '为', 'pos': 'p', 'freq': 10},
  {'word': '的', 'pos': 'uj', 'freq': 9},
  {'word': '我', 'pos': 'r', 'freq': 7},
  {'word': '愿', 'pos': 'v', 'freq': 6},
  {'word': '携', 'pos': 'v', 'freq': 6},
  {'word': '衣袖', 'pos': 'n', 'freq': 6},
  {'word': '扬起', 'pos': 'v', 'freq': 6},
  {'word': '长风', 'pos': 'n', 'freq': 6},
  {'word': '不必', 'pos': 'd', 'freq': 6},

In [9]:
rows = []
for song_id, word_list in lyric_words_dict.items():
    for item in word_list:
        # 创建新字典，保留原始数据并加入歌曲ID列
        new_row = {
            'song_id': song_id,
            'word': item['word'],
            'pos': item['pos'],
            'freq': item['freq']
        }
        rows.append(new_row)

# 3. 转换为 DataFrame
df_word = pd.DataFrame(rows)
df_word

         song_id word pos  freq
0      633973719    处   n     4
1      633973719    了  ul     4
2      633973719    把   p     2
3      633973719   江湖  ns     2
4      633973719   斟入   v     2
...          ...  ...  ..   ...
13880  297559879   血泪   n     1
13881  297559879   挥洒   v     1
13882  297559879   书写   n     1
13883  297559879    新   a     1
13884  297559879   神话   n     1

[13885 rows x 4 columns]

In [10]:
# 合并
# 1. 确保 df_word 的 song_id 是字符串
df_word['song_id'] = df_word['song_id'].astype(str)

# 2. 确保 df_unique 的 song_id 是字符串（并去掉可能存在的空格）
df_songs['song_id'] = df_songs['song_id'].astype(str).str.strip()

# 3. 执行合并
df_merged = df_word.merge(df_songs, on='song_id', how='left')

# 4. 删除空值
df_merged = df_merged.dropna()

df_merged

,song_id,word,pos,freq,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,tv_name,song_name_unique,publish_date,is_ost
0,633973719,处,n,4,0029blSZ16tCiJ,纵马踏歌行,《剑来》动画第二季插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,83047554,纵马踏歌行,003otjHh1KR2Lg,176,1768320000,剑来,纵马踏歌行,2026-01-14,1
1,633973719,了,ul,4,0029blSZ16tCiJ,纵马踏歌行,《剑来》动画第二季插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,83047554,纵马踏歌行,003otjHh1KR2Lg,176,1768320000,剑来,纵马踏歌行,2026-01-14,1
2,633973719,把,p,2,0029blSZ16tCiJ,纵马踏歌行,《剑来》动画第二季插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,83047554,纵马踏歌行,003otjHh1KR2Lg,176,1768320000,剑来,纵马踏歌行,2026-01-14,1
3,633973719,江湖,ns,2,0029blSZ16tCiJ,纵马踏歌行,《剑来》动画第二季插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,83047554,纵马踏歌行,003otjHh1KR2Lg,176,1768320000,剑来,纵马踏歌行,2026-01-14,1
4,633973719,斟入,v,2,0029blSZ16tCiJ,纵马踏歌行,《剑来》动画第二季插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,83047554,纵马踏歌行,003otjHh1KR2Lg,176,1768320000,剑来,纵马踏歌行,2026-01-14,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13880,297559879,血泪,n,1,000sfLHg43UbQo,苍穹之下,电视剧《斗罗大陆》戴沐白人物曲）,刘宇宁,2241311,001Iu4Dv1NzRCD,17500078,斗罗大陆 史兰客七怪音乐专辑,000uo5Ig1624LG,272,1613354400,斗罗大陆,苍穹之下,2021-02-15,1
13881,297559879,挥洒,v,1,000sfLHg43UbQo,苍穹之下,电视剧《斗罗大陆》戴沐白人物曲）,刘宇宁,2241311,001Iu4Dv1NzRCD,17500078,斗罗大陆 史兰客七怪音乐专辑,000uo5Ig1624LG,272,1613354400,斗罗大陆,苍穹之下,2021-02-15,1
13882,297559879,书写,n,1,000sfLHg43UbQo,苍穹之下,电视剧《斗罗大陆》戴沐白人物曲）,刘宇宁,2241311,001Iu4Dv1NzRCD,17500078,斗罗大陆 史兰客七怪音乐专辑,000uo5Ig1624LG,272,1613354400,斗罗大陆,苍穹之下,2021-02-15,1
13883,297559879,新,a,1,000sfLHg43UbQo,苍穹之下,电视剧《斗罗大陆》戴沐白人物曲）,刘宇宁,2241311,001Iu4Dv1NzRCD,17500078,斗罗大陆 史兰客七怪音乐专辑,000uo5Ig1624LG,272,1613354400,斗罗大陆,苍穹之下,2021-02-15,1
13884,297559879,神话,n,1,000sfLHg43UbQo,苍穹之下,电视剧《斗罗大陆》戴沐白人物曲）,刘宇宁,2241311,001Iu4Dv1NzRCD,17500078,斗罗大陆 史兰客七怪音乐专辑,000uo5Ig1624LG,272,1613354400,斗罗大陆,苍穹之下,2021-02-15,1

In [11]:
words_file_path = 'data_output/liuyuning/qq_words_data.csv'
df_merged.to_csv(words_file_path, index=False)

In [13]:
df_merged[df_merged['word'] == '云']

,song_id,word,pos,freq,song_mid,song_name,song_subname,artist_name,artist_id,artist_mid,album_name,album_id,album_mid,duration,publish_time,tv_name,song_name_unique,publish_date,is_ost
1351,615276233,云,n,3,003iHNqk3GEuUU,那朵花,《四喜》电视剧主题曲,刘宇宁,2241311,001Iu4Dv1NzRCD,77827929,四喜 电视剧原声带,000pSMGF4U3SCx,273,1762565400,四喜,那朵花,2025-11-08,1
1994,423942396,云,n,4,001XlHtu40S3Mw,就在江湖之上,《莲花楼》影视剧片头曲,刘宇宁,2241311,001Iu4Dv1NzRCD,40335736,莲花楼 电视剧原声专辑,002CIQEt41OeLt,187,1690106400,莲花楼,就在江湖之上,2023-07-23,1
3750,357646651,云,n,3,003z3gS02JaAd5,凌云寂,《说英雄谁是英雄》网剧插曲,刘宇宁,2241311,001Iu4Dv1NzRCD,28396337,说英雄谁是英雄 网剧原声带,000Eb9LR3t6knO,249,1653616800,说英雄谁是英雄,凌云寂,2022-05-27,1
4432,476897109,云,n,1,004CFtTw0fwohb,世世,《与凤行》电视剧「铭刻入骨」主题曲,刘宇宁,2241311,001Iu4Dv1NzRCD,48449281,与凤行 电视剧原声带,004G90F50JcL55,252,1710727200,与凤行,世世,2024-03-18,1
5458,547010137,云,ns,1,000BLRzY38NExV,年长,《蜀锦人家》影视剧人物情感曲,刘宇宁,2241311,001Iu4Dv1NzRCD,59577263,蜀锦人家 影视原声带,002MgFQM3UJmr4,181,1733191200,蜀锦人家,年长,2024-12-03,1
8008,331063452,云,ns,1,001UXg1r3RmNRf,造化,《魔道祖师》动画魏无羡角色曲,刘宇宁,2241311,001Iu4Dv1NzRCD,23109695,造化,003S7TNB0Y1VKT,282,1635645600,魔道祖师,造化,2021-10-31,1
10864,270355541,云,n,2,000S2jb20DSuC8,浪,《河神2》电视剧主题曲,刘宇宁,2241311,001Iu4Dv1NzRCD,13240340,河神2 网剧原声带,002IbIhh03HaQM,251,1594000800,河神2,浪,2020-07-06,1